### ISSUE TITLE
Support for graceful shutdown

### ISSUE THREAD

**Issue by pradels** [vagrant-libvirt/vagrant-libvirt#10]
Support Vagrant settings config.vm.graceful_halt_retry_count and config.vm.graceful_halt_retry_interval.

**Comment by infernix** [comment]
This is (since 1.8.1) called `graceful_halt_timeout`:  `The time in seconds that Vagrant will wait for the machine to gracefully halt when vagrant halt is called. Defaults to 60 seconds.`

I think this is as trivial as changing the hardcoded 30 seconds here https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/halt_domain.rb#L22 to use the `config.vm.graceful_halt_timeout` variable, but would need to test.

**Comment by infernix** [comment]
As mentioned in #191 by @sciurus, graceful shutdown needs an overhaul:

> Use the builtin [GracefulHalt](https://github.com/mitchellh/vagrant/blob/v1.5.4/lib/vagrant/action/builtin/graceful_halt.rb) instead of VagrantPlugins::ProviderLibvirt::Action::HaltDomain. Sample usage [here](https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/action.rb#L123). We'll still need our own action action to run if graceful halt fails.

So when addressing the timeout, this should be properly implemented to begin with.

**Comment by electrofelix** [comment]
While it would be nice to use the builtin GracefulHalt, there is no way to support calling domain.shutdown which allows for libvirt to send a single to the machine for it to shutdown gracefully as this error is currently swallowed by vagrant at https://github.com/hashicorp/vagrant/blob/3e4b4646f4ad5f4edc03bddec2729389a1124b31/lib/vagrant/action/builtin/graceful_halt.rb#L62

So for now with the improvements around #1236 and #1265, this is possible the best we can do.

**Comment by electrofelix** [comment]
I've logged hashicorp/vagrant#12368, if that gets added, I'll look at revisiting.
