### ISSUE TITLE
waiting for domain to get ip

### ISSUE THREAD

**Issue by talat-shaheen** [vagrant-libvirt/vagrant-libvirt#1032]
### Steps to reproduce
1.  vagrant box add centos/7 --provider=libvirt
2. vagrant up --provider libvirt --debug
3.

### Expected behaviour
Vm should be up & running

### Actual behaviour
Stuck at getting IP address. Dnsmasq does not provide IP using dhcp
### System configuration
# uname -a
Linux pts00453-vm1 3.10.0-957.21.3.el7.ppc64le #1 SMP Fri Jun 14 06:58:05 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux

**Libvirt version:**

**
# vagrant plugin list
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

sahara (0.0.17, global)
vagrant-libvirt (0.0.45, global)
  - Version Constraint: > 0
vagrant-mutate (1.2.0, global)
vagrant-proxyconf (2.0.5, global)
vagrant-sshfs (1.3.1, global)
# vagrant version
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installed Version: 2.2.6.dev
Latest Version: 2.2.5
**

vagrant debug output

**
```
**INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x0000010009f2b188>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000010009f2b098>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworks:0x0000010009f2b070>
 INFO create_networks: Using default at 192.168.122.0/24 as the management network nat is the mode
DEBUG create_networks: In config found network type forwarded_port options {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :network_name=>"default", :ip=>"192.168.122.0", :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :guest_ipv6=>"yes", :autostart=>false, :bus=>nil, :slot=>nil}
DEBUG create_networks: looking up network with ip == 192.168.122.0
DEBUG create_networks: Checking that network name does not clash with ip
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x000001000ab88a20>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x000001000ab889a8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces:0x000001000ab88980>
 INFO create_network_interfaces: Using default at 192.168.122.0/24 as the management network nat is the mode
DEBUG create_network_interfaces: In config found network type forwarded_port options {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
DEBUG create_network_interfaces: Adapter not specified so found slot 0
DEBUG create_network_interfaces: Found network by name
 INFO create_network_interfaces: Creating network interface eth0 connected to network default.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x00000100097744f8>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000010009774480>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetBootOrder:0x0000010009774458>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x0000010009be14f0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000010009be13d8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x0000010009be13b0>
 INFO interface: info: Starting domain.
 INFO interface: info: ==> cent-01: Starting domain.
==> cent-01: Starting domain.
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x0000010009e92618>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000010009e92500>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x0000010009e924d8>
DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:72:fd:75
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> cent-01: Waiting for domain to get an IP address...
==> cent-01: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|

  ##### DEFINE VM for oob-mgmt-server #####
  config.vm.define "cent-01" do |config|
  config.vm.hostname = "cent-01"
  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.provider :libvirt do |v|
    v.memory = 1024
    v.video_type = "virtio"
v.management_network_name = "default"
    v.management_network_address = "192.168.122.0/24"
    end
  end
end
~

```

**Are you using upstream vagrant package or your distros package?**
all latest source code have to compiled for ppc64le

**Comment by talat-shaheen** [comment]
More inputs:
[root@pts00453-vm1 test]# virsh list
 Id    Name                           State
----------------------------------------------------

[root@pts00453-vm1 test]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 docker-machines      active     yes           yes
 vagrant-libvirt      active     no            yes

 [root@pts00453-vm1 test]# brctl show
bridge name     bridge id               STP enabled     interfaces
docker0         8000.0242b769ce28       no
virbr0          8000.525400779930       yes             virbr0-nic
virbr1          8000.525400774d5a       yes             virbr1-nic
virbr2          8000.525400a7e6d7       yes             virbr2-nic

[root@pts00453-vm1 test]#  /bin/systemctl status libvirtd
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-08-07 15:54:12 IST; 8s ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 132617 (libvirtd)
    Tasks: 23 (limit: 32768)
   Memory: 2.7G
   CGroup: /system.slice/libvirtd.service
           ├─108190 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─108191 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─108300 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/vagrant-libvirt.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─108301 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/vagrant-libvirt.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─109305 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─109307 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           └─132617 /usr/sbin/libvirtd --listen

Aug 07 15:54:12 pts00453-vm1 systemd[1]: Started Virtualization daemon.
Aug 07 15:54:13 pts00453-vm1 dnsmasq[109305]: read /etc/hosts - 2 addresses
Aug 07 15:54:13 pts00453-vm1 dnsmasq[108190]: read /etc/hosts - 2 addresses
Aug 07 15:54:13 pts00453-vm1 dnsmasq[109305]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Aug 07 15:54:13 pts00453-vm1 dnsmasq[108190]: read /var/lib/libvirt/dnsmasq/docker-machines.addnhosts - 0 addresses
Aug 07 15:54:13 pts00453-vm1 dnsmasq-dhcp[108190]: read /var/lib/libvirt/dnsmasq/docker-machines.hostsfile
Aug 07 15:54:13 pts00453-vm1 dnsmasq-dhcp[109305]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Aug 07 15:54:13 pts00453-vm1 dnsmasq[108300]: read /etc/hosts - 2 addresses
Aug 07 15:54:13 pts00453-vm1 dnsmasq[108300]: read /var/lib/libvirt/dnsmasq/vagrant-libvirt.addnhosts - 0 addresses
Aug 07 15:54:13 pts00453-vm1 dnsmasq-dhcp[108300]: read /var/lib/libvirt/dnsmasq/vagrant-libvirt.hostsfile

 [root@pts00453-vm1 test]#  /bin/systemctl status dnsmasq
● dnsmasq.service - DNS caching server.
   Loaded: loaded (/usr/lib/systemd/system/dnsmasq.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-08-06 16:29:41 IST; 23h ago
 Main PID: 36267 (dnsmasq)
    Tasks: 1
   Memory: 3.3M
   CGroup: /system.slice/dnsmasq.service
           └─36267 /usr/sbin/dnsmasq -k

Aug 06 16:29:41 pts00453-vm1 systemd[1]: Started DNS caching server..
Aug 06 16:29:41 pts00453-vm1 dnsmasq[36267]: started, version 2.76 cachesize 150
Aug 06 16:29:41 pts00453-vm1 dnsmasq[36267]: compile time options: IPv6 GNU-getopt DBus no-i18n IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSS...ct inotify
Aug 06 16:29:41 pts00453-vm1 dnsmasq[36267]: reading /etc/resolv.conf
Aug 06 16:29:41 pts00453-vm1 dnsmasq[36267]: using nameserver 10.77.224.100#53
Aug 06 16:29:41 pts00453-vm1 dnsmasq[36267]: read /etc/hosts - 2 addresses
Aug 07 13:53:59 pts00453-vm1 dnsmasq[36267]: reading /etc/resolv.conf
Aug 07 13:53:59 pts00453-vm1 dnsmasq[36267]: using nameserver 10.77.224.101#53
Aug 07 13:53:59 pts00453-vm1 dnsmasq[36267]: using nameserver 10.77.224.100#53
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by electrofelix** [comment]
For the version of libvirt you are using, it should be retrieving the address via libvirts dhcp leases api, you can check out the what it should be seeing via:
```
for net in $(virsh net-list --name); do virsh net-dhcp-leases ${net}; done
```

The error `The specified wait_for timeout (2 seconds) was exceeded` normally means there was an excessive delay in the response being returned, so it would suggest that the above was slow.

Not sure if being empty would result in the same, however you need to make sure that there is something being returned for `virsh net-dhcp-leases <network>` for the network that the VM is attached to, otherwise vagrant-libvirt can't do anything. This can mean there is something wrong with the host environment or with the VM not requesting an address via DHCP.

**Comment by talat-shaheen** [comment]
Thanks @electrofelix for helping me out.
I am using vagrant box add centos/7 --provider=libvirt. I assume that VM would be requesting for IP. Can I debug it by some way.

```
[root@pts00453-vm1 ~]# for net in $(virsh net-list --name); do virsh net-dhcp-leases ${net}; done
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------

 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------

 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
```
Host OS is RHEL 7.6.
```
[root@pts00453-vm1 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
```

Vagrant up gets stuck but the following virt-install works for the same image where dhcp is enabled for eth0.

`virt-install --machine=pseries --name=xenial1   --network=default,model=virtio --disk path=/var/lib/libvirt/images/xenial1.qcow2,format=qcow2,bus=virtio,cache=none --memory=2048 --vcpu=1 --os-type=linux --os-variant=ubuntu16.04 --cdrom=./ubuntu-16.04.6-server-ppc64el.iso  --nographics`

The vagrant output if the working image(by virt-install) is used is [here](https://github.com/talat-shaheen/test/blob/master/vagrant.output)

Interesting thing to note is that the same image is not issuing dhcp request when run with vagrant. With virt-install it does but with vagrant box its not.
```
[root@pts00453-vm1 ~]# /bin/systemctl status libvirtd
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-08-07 15:54:12 IST; 19h ago
     Docs: man:libvirtd(8)
           https://libvirt.org
 Main PID: 132617 (libvirtd)
    Tasks: 24 (limit: 32768)
   Memory: 2.7G
   CGroup: /system.slice/libvirtd.service
           ├─108190 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─108191 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/docker-machines.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─108300 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/vagrant-libvirt.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─108301 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/vagrant-libvirt.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─109305 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           ├─109307 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           └─132617 /usr/sbin/libvirtd --listen

Aug 08 10:41:41 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPREQUEST(virbr0) 192.168.122.42 52:54:00:fb:e7:a8
Aug 08 10:41:41 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPACK(virbr0) 192.168.122.42 52:54:00:fb:e7:a8 ubuntu16
Aug 08 10:46:40 pts00453-vm1 libvirtd[132617]: 132622: warning : qemuDomainObjTaint:7521 : Domain id=7 name='xenial' uuid=279ece55-337f-4d9c-9e07-c4a4a32e0...privileges
Aug 08 10:47:10 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPREQUEST(virbr0) 192.168.122.42 52:54:00:fb:e7:a8
Aug 08 10:47:10 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPACK(virbr0) 192.168.122.42 52:54:00:fb:e7:a8 ubuntu16
Aug 08 11:15:14 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPREQUEST(virbr0) 192.168.122.42 52:54:00:fb:e7:a8
Aug 08 11:15:14 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPACK(virbr0) 192.168.122.42 52:54:00:fb:e7:a8 ubuntu16
Aug 08 11:17:08 pts00453-vm1 dnsmasq-dhcp[109305]: DHCPRELEASE(virbr0) 192.168.122.42 52:54:00:fb:e7:a8
Aug 08 11:17:09 pts00453-vm1 libvirtd[132617]: 132617: error : qemuMonitorIO:718 : internal error: End of file from qemu monitor
Aug 08 11:24:17 pts00453-vm1 libvirtd[132617]: 132619: warning : qemuDomainObjTaint:7521 : Domain id=8 name='box_test_vagrant' uuid=6be14c33-bfea-4b02-92c5...privileges
Hint: Some lines were ellipsized, use -l to show in full.
[root@pts00453-vm1 ~]# virsh list
 Id    Name                           State
----------------------------------------------------
 8     box_test_vagrant               running


```

**Comment by jwcmd** [comment]
I'm hitting a similar problem with Opensuse42, the behavior is very much the same. OpenSuse42 hangs at 'Waiting for domain to get an IP address...' and I'm having trouble making progress troubleshooting this. 

Creating an OpenSuse host with virt-install works.
Creating a Debian 8, Debian 9, Centos 6, Centos 7 and various Amazon Linux hosts all work, but specifically OpenSuse42 is failing for me. 

I've compared the network section of the XML output for 'virsh dumpxml' for the VMs that vagrant creates and compared it against working vagrant VMs and OpenSuse42 from virt-install, but don't see any obvious problems.

`for net in $(virsh net-list --name); do virsh net-dhcp-leases ${net}; done` Shows that opensuse42 indeed never gets an address, and when I tcpdump the virtual interface attached to that VM early in the boot process and look for DHCP requests, I don't see them.

If anyone has any extra info for debugging this please do let us know!
This Vagrantfile is being run on the same host as libvirt, but I have been using a slightly modified version remotely with success with debian9 as well.
I've left in centos/7 incase it's helpful for @talat-shaheen.

```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = "qemu:///system"
  end
  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "centos/7"
    centos7.vm.synced_folder ".", "/vagrant", disabled: true
  end
  config.vm.define "opensuse42" do |opensuse42|
    opensuse42.vm.box = "nwbtco/opensuse42.2"
    opensuse42.vm.synced_folder ".", "/vagrant", disabled: true
  end
end
```

When I 'vagrant up opensuse42' and then try to attach a console with `virsh console $VMNAME` I'm dropped into the VM console but it's unresponsive to any input except CTRL+] which is the console escape character.

I'm currently thinking that something is preventing certain VMs or distros from connecting the networking within the VM up correctly, and/or that the boot process is failing *very* early on. I'm looking into how to get all console output sent to a logfile on the hypervisor host to try and debug further, if anyone has thoughts on troubleshooting this further pls let us know. 

I'm posting this comment here because despite using libvirt+vagrant locally and with a different OS than reported above, the behavior that I'm seeing is almost identical, leading me to believe it's the same problem.

Hypervisor's /etc/os-release file:
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

All pending upgrades have been applied to the hypervisor and the problem persists.

I've tried multiple baseboxes:
- generic/opensuse42
- roboxes/opensuse42
- nwbtco/opensuse42.2 (after converting with vagrant-mutate)
- generic/opensuse15

None of them boot successfully on my systems when brought up with vagrant, so I'm pretty sure it's not the images I'm trying.

**Comment by swilmet** [comment]
I have the same problem, on Fedora 30 (host) with the `generic/fedora30` box.

**Comment by swilmet** [comment]
It looks like the same problem as this downstream bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1283989

**Comment by talat-shaheen** [comment]
My problem got resolved when I switched from centos/7 to ppc64le/centos76 since I was using power platform.

**Comment by jwcmd** [comment]
Little bit more info, creating a vagrant basebox by hand by installing opensuse with virt-install and packaging that up into a basebox (as per https://unix.stackexchange.com/questions/222427/how-to-create-custom-vagrant-box-from-libvirt-kvm-instance) and then trying to use the new basebox produces the same hanging behavior as the other publicly available base boxes. I suspect the way vagrant-libvirt sets up the VM for opensuse causes problems for opensuse but not other OSs. Still exploring.

**Comment by jwcmd** [comment]
I've now tried to vagrant up an opensuse box, and then saved the resulting XML config from virsh, and created a new VM from that config (after updating it to point to the base img). The image boots, but doesn't get an IP which is perhaps just an XML config issue.  I still feel like based on the lack of console responsiveness to keystrokes, that the failed-to-boot VMs are failing very early on and that the fact vagrant hangs waiting for an IP is a red herring.

As of yet, I'm not able to reproduce the hanging behavior produced by vagrant+libvirt when I create a VM manually. Chewing on how else to troubleshoot this, but I might have to tackle https://github.com/vagrant-libvirt/vagrant-libvirt/pull/695 before I'll be able to get the console logs I'm looking for.

**Comment by jwcmd** [comment]
It's also worth noting that I've reproduced this on a second similar hardware host so I don't believe it's related to the hardware I'm using.

**Comment by jwcmd** [comment]
Tried 18.04 as the OS on the hardware instead of 16.04. No change, opensuse still hangs at boot.

**Comment by jwcmd** [comment]
I'm getting the same behavior trying to bring up generic/fedora30 as well.
At this point I'm not sure I can continue investing time into vagrant+libvirt, we may have to just abandon it in favor of OpenStack in light of these problems.

**Comment by electrofelix** [comment]
Sometimes it can help by connecting a vncviewer to the default port to see where in the boot sequence the machine is stuck, looks to me like there may be a problem with the `generic/fedora30` image in that I'm seeing the following appear in the boot screen

![boot-generic-fedora](https://user-images.githubusercontent.com/912324/66486641-ef2fce80-eaa2-11e9-94df-0a6194d42ee5.png)

Based on this I'm not sure that's a good image to work with, looks like it hasn't been cleaned before packaging correctly because it's expecting a specific disk device to be connected.

Maybe try the following:
```
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/30-cloud-base"
  config.vm.box_version = "30.20190425.0"
end
```

If you have multiple VMs, you can get the correct port by running the following with the appropriate name
```
virsh dumpxml <name> | grep vnc
```
which for me outputted
```
    <graphics type='vnc' port='5900' autoport='yes' listen='127.0.0.1' keymap='en-us'>
```

**Comment by swilmet** [comment]
> Maybe try the following:
> 
> ```
> Vagrant.configure("2") do |config|
>   config.vm.box = "fedora/30-cloud-base"
>   config.vm.box_version = "30.20190425.0"
> end
> ```

It works for me! Thanks a lot. So it's a problem with certain images.

**Comment by electrofelix** [comment]
@jwcmd I've found the problem the opensuse images, it appears that when it was packaged up, the file `/etc/udev/rules.d/70-persistent-net.rules` was left in place which contains the old network mac address, combined with the default configuration to only have eth0 attached means that in libvirt the dynamically created nic would not have a matching address.

Similarly to building one yourself, you would need to make sure this file is deleted before shutdown and package up of the box image.

One trick for the nwbtco/opensuse42.2 image is to add the following block to your Vagrantfile:
```
  config.vm.provider "libvirt" do |lv|
    lv.management_network_mac = "0800271dfee1"
  end
```
This tells libvirt to use the same MAC address for the management nic as is hardcoded into the image. That will allow the network device to be assigned as eth0 and get an IP address.

Sorry it took so long to point you in the right direction
```

**Comment by jwcmd** [comment]
> Sometimes it can help by connecting a vncviewer to the default port to see where in the boot sequence the machine is stuck

> vncviewer or virt-viewer [are] probably the quickest way to establish what was happening during the boot of your images

> one of the issues with the console is that you also need to build the image used to tell the kernel to output to the console during boot, and typically most do not have this built in.

These are exactly the pieces I've been missing, I can't thank you enough @electrofelix !!
Can confirm that connecting with vnc-viewer lets me see exactly the output I expected to see on the console, I'm elated! 

I'll submit a patch to the Readme to add a Troubleshooting section that mentions much of what you've covered here to help anyone who may follow in our steps, again I can't thank you enough for helping out with this!

**Comment by ladar** [comment]
@electrofelix if you notice problems with `generic` boxes. and know the fix, I'd welcome a pull request. It's hard to test every host/guest/vagrant/libvirt version combination. This bug stems from issues with how `virtio`, `scsi`, and `virtio-scsi` is handled on some systems. I stumbled across this issue while looking for something to fix that issue.

As for the generic configs. I believe the SYS-V guests all wipe the `/etc/udev/rules.d/70-persistent-net.rules` file to prevent the network bug you mentioned. I don't recall how the issue is handled with the various `systemd` configs.

**Comment by electrofelix** [comment]
@ladar catching up, I've found the problem for the disks, so hopefully will improve compatibility once I've sorted out how to enable the right settings automatically if possible rather than requiring addition config.

Regarding the systemd issue the nwbtco/opensuse42.2 image is systemd based as well, though it's early enough that it may still have been managing persisting network devices the old way but at the same time not have the automatic clean up you mentioned. Don't know if it affects many others.

**Comment by alexanderadam** [comment]
> @electrofelix if you notice problems with `generic` boxes. and know the fix, I'd welcome a pull request.

I don't know a fix but I'm having the problem with [`generic/ubuntu2204`](https://app.vagrantup.com/generic/boxes/ubuntu2204) right now.

**Comment by alexanderadam** [comment]
Does anyone know an Ubuntu 22.04 solution that's not running into this issue?

**Comment by electrofelix** [comment]
@alexanderadam if this is a box you've built yourself, probably need to look at mimicking what is done in https://github.com/lavabit/robox/blob/master/scripts/ubuntu2204/network.sh

Otherwise you'll need to follow the initial steps from the troubleshooting section of the README at https://github.com/vagrant-libvirt/vagrant-libvirt#troubleshooting-vms and post an issue regarding what details from the boot sequence you encounter. It may just require seeing what the Mac address is hard coded to be and using it, but the only way to see that is via vncviewer and getting access to the console.

**Comment by ladar** [comment]
@[alexanderadam I'll fire off a quick test.

But just to clarify, you've started up the `generic/ubuntu2204` on this host before? And you weren't trying to start up or destroy any other virtual machines at the same time? And finally, the default libvirt network used by Vagrant already exists and was started/available? See the screenshot.

Finally, you were using a system controlled libvirtd service and not a user local QEMU session?

If all that is true, I did notice one issue last week that I've been meaning to mention to @electrofelix but haven't fully investigated yet.  It appeared that when I was using multiple jobs to create/destroy VMs I would get failures because one box would be sutting down, and destroy a network before another box had finished initializing. 

It was just a theory, but I recently noticed a lot of new libvirt network setup/destruction options have been added, along with separate management network setup/destruction options. So it makes that the behaviour would have changed.

It's also worth double checking that you don't have an existing DHCP  record for the same default host/box name.

**Comment by ladar** [comment]
![Screenshot from 2022-05-20 17-58-49](https://user-images.githubusercontent.com/1434008/169623515-730dcc4a-bac8-48aa-9876-f88ca2fd5c9e.png)

**Comment by electrofelix** [comment]
@ladar there was a option added to prevent networks from being destroyed by default as part of fixing the network teardown if it wasn't in use, however it seems that has shaken out a bug or two more from the sounds of things. I think though it wouldn't just hang at the getting an IP address if this is what is happening.

**Comment by ladar** [comment]
@electrofelix can't he get that info like so?

```
# For guest interfaces.
virsh --connect=qemu:///system list --all
virsh --connect=qemu:///system domiflist generic-fedora30-libvirt_default
# Host interfaces.
virsh --connect=qemu:///system net-list --all 
virsh --connect=qemu:///system net-dumpxml default
virsh --connect=qemu:///system net-dumpxml vagrant-libvirt
```
That should give him all the host/guest interfaces and there mac addresses like so:

```
#$ virsh --connect=qemu:///system list --all
 Id    Name                           State
----------------------------------------------------
 -     generic-fedora30-libvirt_default shut off

#$ virsh --connect=qemu:///system domiflist generic-fedora30-libvirt_default
Interface  Type       Source     Model       MAC
-------------------------------------------------------
-          network    vagrant-libvirt virtio      52:54:00:8d:84:e4
-          network    default    virtio      52:54:00:12:7c:6c

#$ virsh --connect=qemu:///system net-list --all 
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 vagrant-libvirt      active     yes           yes

#$ virsh --connect=qemu:///system net-dumpxml default
<network>
  <name>default</name>
  <uuid>e8494997-1329-42dd-8e8c-1677c5f67590</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:f8:6f:db'/>
  <ip address='192.168.122.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.122.2' end='192.168.122.254'/>
    </dhcp>
  </ip>
</network>

#$ virsh --connect=qemu:///system net-dumpxml vagrant-libvirt
<network ipv6='yes'>
  <name>vagrant-libvirt</name>
  <uuid>3e8105e0-5f48-40a8-9e05-b69284133038</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:e9:05:40'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.1' end='192.168.121.254'/>
    </dhcp>
  </ip>
</network>

```

**Comment by ladar** [comment]
Well it seemed like the box start the setup process, for example Vagrant would SSH and replace the key, and then disconnect. But before it could reconnect and finish, the other job would tear down the interface.

As I recall, if there was no vagrant-libvirt network, it would get created automatically. But wouldn't get destroyed, and if existed, but was stopped, it would start. Then I think the auto start got removed, so I had to change the config on the network settings so it got started with the OS.

Although this all got done so long ago, it's hard to recall specifics at this point.

**Comment by ladar** [comment]
@electrofelix I'm not so sure that you created bugs, so much as the deault behaviour changed, and I haven't found the right options yet to avoid issues.  Let me see if I can catch you via IM.

**Comment by electrofelix** [comment]
@ladar if there is a hardcover MAC, it won't show up on the libvirt side because the network devices attached to the VM will be given new MAC addresses, but the existing default device in the guest will only perform DHCP on the device containing the old MAC. The request never gets sent from the guest to libvirt because there is no network device for it to be sent via.

The problem with the network disappearing from under the guest is concerning, I thought that libvirt would reject a destroy request while the network was still in use, though maybe I missed something when I checked that.

**Comment by ladar** [comment]
@electrofelix your scenario could be right. I never confirmed what was happening live, I was just guessing based on logs after the fact. And I made that guess because of this issue:  [SSH port forwarding conflicts cause vagrant up to fail (race condition) ](https://github.com/hashicorp/vagrant/issues/12729) that issue was involved the VirtualBox plugin, and a different guest, that was completely isolated from the another Vbox+Vagrant environment, would somehow take over an SSH port mapping. Anyways, it turned I found out later on, part of the blame was with Packer: [base_mac added to bundled Vagrantfiles is causing reuse of MAC addresses](https://github.com/hashicorp/packer-plugin-virtualbox/issues/64) ... because I was running the same base image in isolated environments on the same host, they were conflcting. 

Anyways, I checked a few of the libvirt boxes, and they were also getting a bundled value, but not base mac. I believe it was accelerator = kvm.

**Comment by ladar** [comment]
Anyways, after looking over the docs, I think I started by trying to keep the network around all the time like [so](https://github.com/lavabit/robox/blob/bb4d3312054e42e00b4f52e390a8643b09cfa09f/check/ubuntu2204.tpl). And eliminating the parallel jobs, so wouldn't confluct. And I think the single file run fixed most issues. It's all a bit of a blur at this point because I had to refocus on getting the next set of boxes building, and I think I finally fixed the last of the issues last night, so they're building now. 

I shoot every 2 weeks. Sometimes sooner (if something new comes out, or I fix something), and sometimes longer, if things break or I need to time to get a new config setup. But I try to keep it undre 4 weeks, and we're coming up on that max, so I havent followed up yet.

**Comment by alexanderadam** [comment]
> Does anyone know an Ubuntu 22.04 solution that's not running into this issue?

**UPDATE:** I'm using [`barbosaaob/ubuntu2204`](https://app.vagrantup.com/barbosaaob/boxes/ubuntu2204) now which seem to work [after I had to install the Vagrant DEB package](https://stackoverflow.com/questions/71987581/openssl-3-0-error-when-booting-vagrantbox) manually and [uninstalling `pkg-config` from homebrew](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1498#issuecomment-1133594122).
All of the other Ubuntu 22.04 images (regardless whether they're libvirt or Virtualbox) didn't work for me.

What an Odysee :laughing:
