### ISSUE TITLE
Vagrant failed to load a configured plugin source

### ISSUE THREAD

**Issue by mnuestc** [vagrant-libvirt/vagrant-libvirt#1033]
I work on a restrictive network which can not be accessible to https://gems.hashicorp.com/. I have also tried to install offline, but failed with same result. 

### Steps to reproduce
1. my vagrant version is 2.25
2. I have updated my vagrant plug, and it shows "All plugins are up to date".
3. "vagrant plugin install vagrant-vbguest" always be faild with below info：
     
“”Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  no such name (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/“”

### System configuration
**OS/Distro version:**:

31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Libvirt version:**
virsh -v 1.3.1

**Output of `vagrant version; vagrant plugin list`:**
No plugins installed

**Comment by mnuestc** [comment]
![image](https://user-images.githubusercontent.com/36103788/62673155-e6058100-b9cf-11e9-9da5-d255f1befdbd.png)
 I also have tried install offline ,but failed with same result

**Comment by electrofelix** [comment]
This is something you'll need to raise with https://github.com/hashicorp/vagrant as you would need vagrant itself to be capable of performing an offline install.

Otherwise you're looking at trying to use vendoring and `bundle exec` to run vagrant with the plugin + dependencies loaded by bundle.

Our solution here was to build a docker image containing vagrant + vagrant-libvirt and then export and load that on the target environment and just run in with `--host net` and `-v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock` along with scripting inside of the container to set the user/group permissions appropriately.

**Comment by electrofelix** [comment]
Closing as we can't solve this within the plugin, it requires solving within vagrant. For some plugins that have no dependencies the localinstall might work, but that's just speculation.

**Comment by mnuestc** [comment]
thanks


> This is something you'll need to raise with https://github.com/hashicorp/vagrant as you would need vagrant itself to be capable of performing an offline install.
> 
> Otherwise you're looking at trying to use vendoring and `bundle exec` to run vagrant with the plugin + dependencies loaded by bundle.
> 
> Our solution here was to build a docker image containing vagrant + vagrant-libvirt and then export and load that on the target environment and just run in with `--host net` and `-v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock` along with scripting inside of the container to set the user/group permissions appropriately.
