### ISSUE TITLE
Address … does not match with network name …

### ISSUE THREAD

**Issue by poige** [vagrant-libvirt/vagrant-libvirt#1053]
This is "guest"-side config so why enforcing that address match at all?

In this very case I have a libvirtd bridge based network which doesn't have any IP-address assigned to it. No matter what I'd expect that if "guest" is told to have given IP on its corresponding interface it should be configured.

**Comment by poige** [comment]
Looking at the sources I've realised that specifying `:libvirt__forward_mode => "veryisolated"` might have helped and it looks like it did.

OTOH in the docs it's said to be "used only when creating new network".

**Comment by electrofelix** [comment]
This sounds like you specified a network name to use which already exists and has a particular network address assigned to it, but you've also specified a network address which does not match the existing network that you've requested to use.

The solution is typically not to specify those unless you have some problem you are attempting to work around. Perhaps share the Vagrantfile and what you are trying to accomplish and I might be able to help?

**Comment by poige** [comment]
> which already exists

It (obviously) does (and did).

> and has a particular network address assigned to it

My point was that its address should irrelevant. It might be even lacking of any and still it shouldn't be stopping from VMs to be configured.

**Comment by electrofelix** [comment]
So you are saying that it should silently ignore explicit user configuration that is in direct conflict with the current system and cannot be applied, which would require the requested network to be automatically configured on an unexpected network address or not configured at all.

This is the equivalent of asking a CLI to silently ignore an unrecognized argument, what's the difference between a typo that requires correction and an invalid configuration? What's the use case here?

Given that a valid default network happens to be required to config the VM for subsequent access by both users and provisioners, or in the case of multi machine configs, not configuring one due to an conflict in the specified configuration seems like it will cause far more problems that are confusing for users than it will solve.

**Comment by poige** [comment]
You seem to have misunderstood what I've explained.

First of all let's have things properly separated. _Housekeeping network_ (Vagrant's native network) is one thing and it's always there being, say, a hallmark. It's NAT based network by Vagrant's requirement.

Now users might want to have _additional networks_. By definition such networks and adapters aren't crucial for Vagrant's own functioning. So my point is those checks are adverse.

All I needed in my case is to have Vagrant set-up the boxes to be ready to use that additional network. But at the hosting node level it didn't even have IP assigned. That's outside of Vagrant boxes domain by definition. They could communicate to each other though — still.

**Comment by jwcmd** [comment]
Just thinking out loud, vagrant-libvirt is just an interface to libvirt, so if libvirt doesn't let you create a VM that's attached to a network that doesn't exist yet then there isn't much vagrant-libvirt can do about that.

Has anyone tried creating a libvirt VM with an XML definition that uses a network that doesn't exist yet? Please note I haven't tried this myself, but as a thought experiment I'm thinking that such a VM would fail to boot. In which case you would need to take this up with the libvirt project as a feature request. 

I agree that what you've proposed (@poige) should work in principle, I'd be interested in seeing support for that, but vagrant-libvirt is probably the wrong place to start that discussion. Hope this helps!

**Comment by electrofelix** [comment]
Just because the additional networks aren't _required_ for vagrant to be able to manage the VM created by vagrant-libvirt through it's management network, they are often used by provisioners.

It sounds like the core of what you are asking is that if a configuration specifies that an additional network be created and configured with a specific network address (based on the IP address assigned to the VM), it should continue even if that is not possible?

Or is that what you are asking for? I did suggest posting a Vagrantfile for more details, because I'm wondering if what you meant is not that it should be ignored, but rather the code should work out that the bridge network is fine to use without an IP address on the VM, however the error you mention should only be seen if you explicitly set an IP address for a VM along a network to use. Hence confusion on what exactly you are encountering.

So how about starting from scratch by providing the Vagrantfile and details of the existing network configuration via `virsh net-dumpxml <network-name>`, so that we're working off of the same page.

**Comment by poige** [comment]
> they are often used by provisioners

So what? If someone wants it that way, it's theirs problems. The problem I'm seeing is that Boxes won't be instantiated at all due to some extra checks done by "vagrant-libvirt". This is wrong because "vagrant-libvirt" shouldn't get into the way users do use theirs "additional networks".

> that an additional network be created

This needs being way more specific. Define "network", define "created"?

I didn't create Libvirt's network with Vagrant. In my case I used already pre-created Libvirt network.
Can't see why this would need `Vagrantfile` to be understood.
As to virsh net-dump — it's plain bridge interface w/o any IP on it. If I need it to have an IP I can add it with anything starting from `sudo ip addr`.

Summary: I think Vagrant shouldn't abort creating VMs just due to that Libvirt (system-wide one) interface didn't have IP-address inside that IP network that I used in Vagrantfile for Boxes that would be attached to this (bridged) network.

Also, as I've already explained, I've found a way to cease that behaviour, but it's kinda not that obvious from current docs.

**Comment by poige** [comment]
Not sure if this would help to understand but imagine that additional network (which is a bridge `br7` at system-wide level) would have more that single IP network — let's say, 5 IP networks. There's no point to check if boxes that are about to be spawned would have theirs IP among those networks only.

Also, as I already pointed out, in some use cases IP connectivity over this additional network from parent system to any of those boxes won't be needed at all, if the only point is boxes interaction between them.

**Comment by electrofelix** [comment]
You're describing what would work for you with a bridge, while ignoring that this has the potential to cause problems that only appear after the VM is going through the provisioning phase for others.

I've suggested that you provide an example of the network device XML dump and corresponding Vagrantfile and it can be be looked at to see if the current behaviour is just down to a bug because it was never written with your particular configuration in mind.

**Comment by poige** [comment]
Did "others" ask you that you should verify or it was your own spark of genius?

**Comment by poige** [comment]
Did "others" ask you that you should verify or it was your own spark of genius?

— May be you can show reported issues saying smth like "You're not checking that IP I'm assigning to an _additional network interface_ of a box can be reached from parent system!!!". I can easily foresee that some users might need this network to be Internet connected, and until it's verified that "has the potential to cause problems".

If you're into absurd that much I can't help, alas.

**Comment by electrofelix** [comment]
Wow, just wow.

The code in that area is 7 years old and has had many different authors through out that files history, fully understanding the different conditions to protect against requires a lot of time to go through and test the different combinations even if it is just to eliminate them as no longer required or not ever having been needed, time which is voluntary and in scarce supply. So rather than create more problems down the road that require more time, I've asked for example of your Vagrantfile configuration and libvirt network config to see if I can limit the amount of effort it would require to resolve your issue without exposing additional issues and leave a note in the code that there is a question over the current checking and whether it's necessary.

**Comment by poige** [comment]
> The code in that area is 7 years old

wow-just-wow © does it make it a sacred cow now or what? )

**Comment by jeffWelling** [comment]
It's not often that I see a feature request that would be sane, if not for the attitude and tone that the op used to request it.  Very much, wow. 

@poige, please, in the interest of getting you the answers your looking for next time, you need to read this and take it to heart: https://raspi.tv/2017/how-to-ask-for-and-receive-technical-help-on-the-internet

Is arguing and talking past the person who's trying to help you going to help or hurt your cause?

I would have instead approached this as "I see what you mean, other people are probably going to want some basic sanity checks. Maybe we can do both though: perhaps we can disable the sanity checks with a flag in the Vagrantfile, so that sanity checks are the default but so that I can turn them off when desirable. "

Food for thought, and and happy hacking.

**Comment by poige** [comment]
> the person who's trying to help you going to help 

that person is me, actually. You might have misread but I’ve explained I’ve solved it for myself and explained how exactly. But later I have thought that others could also bump into this. And all that shit started.
