### ISSUE TITLE
Question: Rootless vagrant on libvirt?

### ISSUE THREAD

**Issue by Kreyren** [vagrant-libvirt/vagrant-libvirt#1078]
Disclaimer: I was unable to find the answer in documentation and so i am submitting an issue.

I'm working on contribution to fix https://github.com/gitpod-io/gitpod/issues/1251 which expects rootless vagrant running inside of a docker environment using libvirt since virtualbox has ongoing vulnerability https://www.cybersecurity-help.cz/vdb/SB2018110701?affChecked=1 that prevents deploy for production.

Using this dockerfile (ignore the notice it is invalid):
https://github.com/Kreyren/gitpod-tests1/blob/d3c7179618c720e7f76142891eeaf72a75516786/gitpod/gitpod.Dockerfile

where running `vagrant up --provider=libvirt` results in:
```
gitpod@hostname:/workspace/gitpod-tests1$ vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/gitpod/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```

That should be provided in package `vagrant-libvirt` on debian.

I assume this being problem with configuration to run rootless libvirt where i don't know how this should be configured properly.

Redirected from https://github.com/hashicorp/vagrant/issues/11408

**Comment by Kreyren** [comment]
seems that i am able to fix this myself, will reopen if i fail and provide a solution

**Comment by electrofelix** [comment]
@Kreyren `/var/run/libvirt/libvirt-sock` provided by the libvirtd service running in the background, it's a socket that allows clients to connect and talk to the daemon libvirtd to manage VMs.

Typically you would want the host machine to provide the /dev/kvm and expose that into the container to be used by the libvirtd process. I'm not familiar with gitpod, however if the host kernel hasn't loaded the kvm module, you're not going to be able to inject the kvm module into the kernel without a privileged container.

So I would suggest starting there to see if the /dev/kvm device is available from the host and whether it is acceptable to make use of it.

The other issue I can see, is whether the /dev/kvm device can be shared, if you have one instance of libvirtd looking to talk to it, I suspect that will block any other container from running and making use of it.

However if it is acceptable to have the host system provide kvm and libvirtd, it should be possible to have the container mount in /var/run/libvirt/libvirt-sock and if you create a separate user for each container I think it is likely possible that by only allowing use of qemu:///session/ rather than qemu:///system that each container would only be able to manage the VM associated with it.

**Comment by electrofelix** [comment]
@Kreyren `/var/run/libvirt/libvirt-sock` provided by the libvirtd service running in the background, it's a socket that allows clients to connect and talk to the daemon libvirtd to manage VMs.

Typically you would want the host machine to provide the /dev/kvm and expose that into the container to be used by the libvirtd process. I'm not familiar with gitpod, however if the host kernel hasn't loaded the kvm module, you're not going to be able to inject the kvm module into the kernel without a privileged container.

So I would suggest starting there to see if the /dev/kvm device is available from the host and whether it is acceptable to make use of it.

The other issue I can see, is whether the /dev/kvm device can be shared, if you have one instance of libvirtd looking to talk to it, I suspect that will block any other container from running and making use of it.

However if it is acceptable to have the host system provide kvm and libvirtd, it should be possible to have the container mount in /var/run/libvirt/libvirt-sock and if you create a separate user for each container I think it is likely possible that by only allowing use of qemu:///session/ rather than qemu:///system that each container would only be able to manage the VM associated with it.

**Comment by Kreyren** [comment]
Thanks for info, appreciated!

**Comment by rudrakshkarpe** [comment]
### I am facing this issue with ```vagrant up``` command in Ubuntu
Could you please suggest how to resolve it? it's getting really annoying to fix it  
```
Bringing machine 'default' up with 'libvirt' provider...
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/rudrakshkarpe/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```
