### ISSUE TITLE
vagrant-2.2.7: incompatible library version ruby-libvirt-0.7.1/lib/_libvirt.so 

### ISSUE THREAD

**Issue by ssbarnea** [vagrant-libvirt/vagrant-libvirt#1081]
It seems that following the official installation method on RPM systems produces a broken driver.

This can be reproduced at least on
* CentOS 8
* Fedora 30/31

### Steps to reproduce

```
sudo /usr/bin/dnf install -y https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.rpm`

CONFIGURE_ARGS='with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64'

vagrant up --no-provision
Bringing machine 'default' up with 'libvirt' provider...
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /home/zuul/.vagrant.d/gems/2.4.9/gems/ruby-libvirt-0.7.1/lib/_libvirt.so (LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/zuul/.vagrant.d/gems/2.4.9/gems/ruby-libvirt-0.7.1/lib/libvirt.rb:11:in `<top (required)>'

```

### Expected behaviour
Usable driver.

### Actual behaviour
Driver compiles and installs but fails to run.

### System configuration
**OS/Distro version:**: CentOS 8, Fedora 30/31

**Libvirt version:**
libvirt-4.5.0

**Output of `vagrant version; vagrant plugin list`:**
+ vagrant version
Installed Version: 2.2.7
Latest Version: 2.2.7

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine310"
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream.

Full log available at https://dashboard.zuul.ansible.com/t/ansible/build/8c763d090c294e5d88cc92c93d86b2ef/console

**Comment by abbbi** [comment]
hi,

there have been similiar issues in the past, it seems related to ruby-libvirt and how it is linked against the embedded ruby version or not, maybe some of the workarounds mentioned in the old issues will help you, see:

 https://github.com/vagrant-libvirt/vagrant-libvirt/issues/541

**Comment by electrofelix** [comment]
I suspect that following the instructions at https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions would resolve this, I'll try and test tomorrow using a CentOS 8 with nested virtualization enabled to see if I can reproduce. It's a bit messy, but until vagrant 3.0 or a release distributed via EPEL that is linked against the distro ruby, having to use the CONFIGURE_ARGS seems to only work sometimes.

**Comment by electrofelix** [comment]
OK, I've confirmed that https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions works for CentOS8, needed to remember not to set `CONFIGURE_ARGS` when installing the plugin afterwards. 

The instructions I've come up with are, firstly install vagrant as normal:
```
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
sudo dnf -y install vagrant
```

Next install dependencies for vagrant-libvirt:
```
# compile steps below will require some of the libraries pulled in here
sudo dnf install -y gcc libvirt libvirt-devel libxml2-devel make ruby-devel libguestfs-tools
sudo systemctl restart libvirtd
sudo usermod -a -G libvirt ${USER}
```
Need to start a new session at this point, or subsequently use sg to switch groups when running vagrant otherwise vagrant-libvirt will not be able to access libvirt.

Then perform the following to patch vagrant for vagrant-libvirt
```
function setup() {
  pkg="$1"
  rpmname="${2:-${pkg}}"

  git clone https://git.centos.org/rpms/${pkg}
  cd ${pkg}
  nvr=$(rpm -q --queryformat "${pkg}-%{version}-%{release}" ${rpmname})
  nv=$(rpm -q --queryformat "${pkg}-%{version}" ${rpmname})
  git checkout imports/c8s/${nvr}
  into_srpm.sh -d c8s
  cd BUILD
  tar xf ../SOURCES/${nv}.tar.*z

  DIR=${nv}
}

sudo dnf install -y byacc git rpm-build
mkdir patches
cd patches
git clone https://git.centos.org/centos-git-common
export PATH=$(readlink -f ./centos-git-common):$PATH
basedir=$(pwd)

setup libssh
mkdir ${DIR}-build
cd ${DIR}-build
cmake ../${DIR} -DOPENSSL_ROOT_DIR=/opt/vagrant/embedded/
make
sudo cp lib/libssh* /opt/vagrant/embedded/lib64

cd ${basedir}

setup krb5 krb5-libs
cd ${DIR}/src
./configure
make
sudo cp -P lib/crypto/libk5crypto.* /opt/vagrant/embedded/lib64/
```

Finally proceed to install and use vagrant-libvirt as normal
```
cd ~
vagrant plugin install vagrant-libvirt
mkdir test
cd test
vagrant init generic/fedora33
vagrant up --provider libvirt
```
I've found that sometimes I have to reboot the host after installing libvirt for this last step to work, not completely sure why, does seem like sometimes networking/dnsmasq doesn't quite work consistently.

Not fantastic, but at least it appears to be consistent, and avoids the need to adjust the scripts for each version/release change of krb5/libssh.

If you're testing this in a nested CentOS8 libvirt VM the Vagrantfile of the nested vagrant machine will need to look like the following to prevent collisions with the default network:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora33"
  config.vm.provider :libvirt do |libvirt|
    libvirt.management_network_address = '192.168.123.0/24'
  end
end
```

If you bump into it complaining about the `Network is already in use by interface eth0` you can run the following and then fix up the Vagrantfile:
```
virsh -c qemu:///system net-undefine vagant-libvirt
```
May need to restart libvirt or reboot the machine at this point, I've found it has issues properly configuring the network when the networking setup has gone wrong.

**Comment by Red54** [comment]
> `virsh -c qemu:///system net-undefine vagant-libvirt`

`virsh -c qemu:///system net-undefine vagrant-libvirt`

**Comment by electrofelix** [comment]
@Red54 thanks, I've edited to include your correction

**Comment by electrofelix** [comment]
Better installation instructions are now available at https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html, which can expanded as needed over time to provide more detail. There is also now a script at https://github.com/vagrant-libvirt/vagrant-libvirt-qa/blob/main/scripts/install.bash which is recommended in the installation instructions were looking to use the upstream vagrant.
