### ISSUE TITLE
Ubuntu 18.04 stuck at Waiting for domain to get an IP address...

### ISSUE THREAD

**Issue by darkn3rd** [vagrant-libvirt/vagrant-libvirt#1097]
### Steps to reproduce

On a new Ubuntu 19.10 host, I ran the following:

```bash
# install KVM stuffs
sudo apt-get install -y \
 bridge-utils \
 cpu-checker \
 libguestfs-tools \
 libvirt-dev \
 qemu-kvm \
 virt-manager
sudo apt-get -y build-dep

# Vagrant Stuffs
sudo apt install -y vagrant
vagrant plugin update
vagrant plugin install vagrant-libvirt
export VAGRANT_DEFAULT_PROVIDER=libvirt

# Build Image
sudo apt-get install packer
git clone https://github.com/jakobadam/packer-qemu-templates.git
cd ubuntu
# Workaround: https://github.com/jakobadam/packer-qemu-templates/issues/40
sed -Ei 's/(.*)(ubuntu-18.04.2)(.*)/\1ubuntu-18.04.4\3/' ubuntu1804.json
sed -Ei 's/("iso_checksum": ")(.*)(",)/\1e2ecdace33c939527cbc9e8d23576381c493b071107207d2040af72595f8990b\3/' ubuntu1804.json

# build new image
packer build -var-file=ubuntu1804.json ubuntu-vagrant.json

# install new image into vagrant
vagrant box add --provider libvirt --name $USER/ubuntu1804 box/libvirt/ubuntu1804-1.box

# run new image
mkdir -p ~/vms/ubuntu1804 && cd ~/vms/ubuntu1804
export VAGRANT_DEFAULT_PROVIDER=libvirt
vagrant init $USER/ubuntu1804
vagrant up
```

### Expected behaviour

I get a new system, and can `vagrant ssh`.

### Actual behaviour

It is continually stuck in a loop:

```
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

I went to `vnc://localhost:5900`, and see the system in prompt mode.  I can log into the system using `vagrant`/`vagrant` using vnc, or using Virtual Machine Manager.

### System configuration
**OS/Distro version:**:
```
Distributor ID:	Ubuntu
Description:	Pop!_OS 19.10
Release:	19.10
Codename:	eoan
```

**Libvirt version:**
```
libvirt-dev/eoan-updates,now 5.4.0-0ubuntu5.2 amd64 [installed]
```
**Output of `vagrant version; vagrant plugin list`:**
```
Installed Version: 2.2.3

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com

vagrant-libvirt (0.0.45, system)
vagrant-mutate (1.2.0, system)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/5559149/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro

Using package that comes with the distro:

```
Package: vagrant
Architecture: all
Version: 2.2.3+dfsg-1ubuntu2
Priority: optional
Section: universe/admin
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Ruby Team <pkg-ruby-extras-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3022
Depends: libarchive-tools, curl, openssh-client, rsync, ruby, ruby-bcrypt-pbkdf (>= 1.0.0), ruby-childprocess (>= 0.6.0), ruby-ed25519 (>= 1.2.4), ruby-erubis (>= 2.7.0), ruby-i18n (>= 0.7.0), ruby-listen (>= 3.1.5), ruby-log4r (>= 1.1.9), ruby-net-scp (>= 1.2.0), ruby-net-sftp (>= 2.1), ruby-net-ssh (>= 5.1.0), ruby-rest-client (>= 1.6.0), ruby-vagrant-cloud (>= 2.0.2), ruby-zip (>= 1.2.2)
Recommends: vagrant-libvirt
Suggests: virtualbox (>= 4.0)
Filename: pool/universe/v/vagrant/vagrant_2.2.3+dfsg-1ubuntu2_all.deb
Size: 412360
MD5sum: f068aea9dea350e4b90283302379abc8
SHA1: 320b8c372e5a3740dd103f3df074978d54be5958
SHA256: 30101ee3b663b6bcda725c8f151de9fbb95a1c780ade23c82e08a8dfe5e7c101
Homepage: https://www.vagrantup.com
Description-en: Tool for building and distributing virtualized development environments
 This package provides the tools to create and configure lightweight,
 reproducible, and portable virtual environments.
 .
 Vagrant uses Oracle’s VirtualBox to create its virtual machines and then
 uses Chef or Puppet to provision them.
Description-md5: d6
```

**Comment by abbbi** [comment]
check the console of the box you booted via virt-viewer or likewise. Probably the image does not boot correctly or fails to register an ip address using DHCP. That doesnt seem like an issue in vagrant-libvirt, more like an issue with the box you are trying to spin up. Try one from the known to work vagrantcloud.com boxes to verify functionality.

**Comment by electrofelix** [comment]
Looks like the boxes maybe broken an no longer issue a dhcp request on the default interface for some reason.

**Comment by electrofelix** [comment]
The underlying issue is to do with predictable device names. When packer created the image it used pci slot 3, so netplan configured the assigned device ens3 to use dhcp. However when libvirt is booting in vagrant-libvirt it gets pci slot 5 which results in systemd creating the network device as ens5.

Unfortuntately vagrant-libvirt cannot work around this behaviour as it doesn't yet have the ability to pre-allocate the bus and pci slots assigned to network devices during domain creation which would allow adding the following:
```
  config.vm.provider "libvirt" do |lv|
    lv.management_network_pci_bus = "0x00"
    lv.management_network_pci_slot = "0x03"
  end
```
To your Vagrantfile to force the network device to use the same bus and slot. At the moment though this bus and slot is automatically assigned by libvirt when the domain definition is sent to libvirt without network devices declared. Consequently it uses it for other devices first and prevents re-allocation.

I think while it might be nice for vagrant-libvirt to support such a workaround in the future, essentially the issue lies with how the box is generated since it requires advanced knowledge to know to go into the machine launched in libvirt to retrieve this information to be able to configured it correctly.

The correct solution is probably to have the image build disable predictable network devices so that the first device attached is seen as eth0 and always gets configured to issue a dhcp request. Other than this, end up needing packer to configure the bus and slot explicitly and then insert this information into the Vagrantfile bundled with the box.

**Comment by kennyr87** [comment]
Troubleshooting this problem bought me here and to GH-1211. After checking the console of the box I booted I got the same log messages displayed there. Ultimately the solution suggested there worked, i.e. configuring vagrant to use the Qemu Agent to extract the management interface configuration from the booted VM.

**Comment by electrofelix** [comment]
Ultimately the solution to prevent issues like this will be to default to using the qemu agent, #1221 covers the enhancement to supporting the agent fully to replace the ssh communicator. Going to close this in favour of tracking it all there.
