### ISSUE TITLE
vagrant-libvirt unsparsifies boxes

### ISSUE THREAD

**Issue by purpleidea** [vagrant-libvirt/vagrant-libvirt#111]
After downloading a centos6.5 box, vagrant installs it. The installation process is basically just an extraction of the tar ball "box":

Here we can see the box installed, and note that it is a sparse volume (this is good):
$ pwd
~/.vagrant.d/boxes/centos6.5/libvirt
$ ls -lAhs
total 1.1G
1.1G -rw-r--r--. 1 james  41G Jan  3 16:52 box.img
4.0K -rw-rw-r--. 1 james   84 Jan  3 16:52 metadata.json
4.0K -rw-rw-r--. 1 james 1.6K Jan  3 16:52 Vagrantfile

When vagrant-libvirt copies the base image to the libvirt storage pool, it "unsparsifies" it! This means it is taking up 41G of disk instead of 1G. It also takes 40x longer to copy!
# pwd

/var/lib/libvirt/images
# ls -lAhs

total 41G
 41G -rwxr--r--. 1 root root  41G Jan  3 17:05 centos6.5_vagrant_box_image.img

This is obviously very serious. Patches and workaround wanted :)

Cheers

**Comment by raghavendra-talur** [comment]
It looks like this is because of virtual size of qcow2 image and not the sparse nature of file.

The size shown in "qemu-img info box.img | grep "virtual size"" is *reserved* by libvirt(or fog) when the file is added to libvirt domain.

Only way to reduce this size is by creating images of lesser virtual size.
End-users otherwise have to go down the route of resize partition,resize image file and then upload box.
