### ISSUE TITLE
How to use bridged network as management network?

### ISSUE THREAD

**Issue by vm200** [vagrant-libvirt/vagrant-libvirt#1124]
I would like to use a bridged network as the management network and default gateway. I can't find anything relevant in the docs. 

Here is my Vagrantfile:
```ruby

# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.socket = "/var/run/libvirt/libvirt-sock"
    libvirt.memory = 2048
    libvirt.cpus = 1
    libvirt.default_prefix = ''
  end

  config.vm.define "test" do |config|
    config.vm.hostname = "test"
    config.vm.box = "generic/debian10"
    config.vm.network :public_network,
      dev: "enp7s0", bridge: "enp7s0", mode: "bridge", ip: "192.168.1.5"
  end

end

```

**Comment by abbbi** [comment]
The Management network depends on DHCP functionality, this wont work they way you plan it. 
The Default Management network is allways managed by libvirt backend and assigns an IP to the vagrant virtual machine. Using the mac address of the virtual machine, vagrant is then able to find out which IP was assigned to the VM that you just deployed.

As such, all boxes are configured to use DHCP on the management network, and assigning an static IP wont work!

If you want to have your management network reachable from the outside without nat, you have to setup a routed libvirt network with dhcp. Of course that network must be setup to be routed correctly by our other network devices. (such as the default GW has to know the route via the libvirt host).

**Comment by electrofelix** [comment]
@vm200 it might help if you share what problem you are trying to solve.

Fundamentally, as @abbbi, vagrant-libvirt expects to be able to connect to the VM brought up in order to perform various actions such as configure additional networks within the VM, set the hostname, mount any sync-ed folders, as well as any actions specified in provisioner steps. So it needs to be able to connect into the VM via a discoverable IP address in order to perform additional actions.

It might be possible to modify vagrant-libvirt to support use of a network where the dhcp is managed outside of the host system provided also provide some way to retrieve the IP address that is allocated to the VM.

The other alternative is a VM that is pxebooted => https://github.com/vagrant-libvirt/vagrant-libvirt#no-box-and-pxe-boot, which disables any attempt to connect to the box as well, so you would subsequently require some other method to connect and configure, though if you were using a host ansible provisioner that could retrieve the information needed from the pxe system, that might work.
