### ISSUE TITLE
Loosing VM when different user (root) executes `vagrant status`

### ISSUE THREAD

**Issue by cejkato2** [vagrant-libvirt/vagrant-libvirt#1129]
### Steps to reproduce
1. Let's have one user (uid) called vms, who creates VM in `/data/vms/m1/` (vagrant up).
2. Another user (root) enters the same directory and executes `vagrant status` - VM is not created.
3. The original user vms runs `vagrant status` again and VM is lost with message "not created", meanwhile virsh list says VM is there.

### Expected behaviour
From my opinion, it'd be ok to tell "VM is not created" to the different user (root in this case), but that must not affect original user vms, who is not able to even halt or destroy VM any more after that.

### System configuration
**OS/Distro version:**: Fedora 32, x86_64, installed from repository (dnf install vagrant vagrant-libvirt) because manual installation `vagrant plugin install vagrant-libvirt` fails due to #1127 .

**Libvirt version:**

```
$ virsh version
Compiled against library: libvirt 6.1.0
Using library: libvirt 6.1.0
Using API: QEMU 6.1.0
Running hypervisor: QEMU 4.2.0
```

**Output of `vagrant version; vagrant plugin list`:**

```
$ vagrant plugin list
vagrant-libvirt (0.0.45, system)
vagrant-sshfs (1.3.5, system)
```
I hope I provided enough information. Could anyone confirm the same behavior? Thanks a lot!

**Comment by timhughes** [comment]
This may be caused by the following. Fedora is trying to make the user experience as simple as possible by making anything that uses libvirt use `qemu:///session` when run as a user and `qemu:///system` when run as root. 

You can see where the current VMs are running by running the following two commands. 
```
virsh --connect=qemu:///system list --all
```
```
virsh --connect=qemu:///session list --all
```

Take a look at https://github.com/vagrant-libvirt/vagrant-libvirt#qemu-session-support 

Fedora patches vagrant-libvirt https://src.fedoraproject.org/rpms/vagrant-libvirt/blob/master/f/vagrant-libvirt-0.0.45-enable-qemu-session-by-default.patch  

Adding `libvirt.uri = 'qemu:///system'` to your vagrant files will restore the old behaviour 
```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.uri = 'qemu:///system'
  end
end
```

For some tools such as `virsh` you can add an environment variable `LIBVIRT_DEFAULT_URI` but I don't think this works for `vagrant-libvirt`
```
export LIBVIRT_DEFAULT_URI=qemu:///system
```

**Comment by electrofelix** [comment]
@timhughes the use of `LIBVIRT_DEFAULT_URI` is respected in recent versions of vagrant-libvirt, just shortly after you mentioned it here, see #1141 

@cejkato2  it looks like when the other user `root` runs status the contents of the directory containing the machine state information gets wiped. Have a look under `.vagrant/machines/default/libvirt/` before and after running the commands as the second user.

When I do this with a log:
```
 INFO driver: Connecting to Libvirt (qemu:///system?no_verify=1&keyfile=/root/.ssh/id_rsa) ...
DEBUG driver: machine 6e9d7668-5ecf-433d-bcc4-9464cb904b6d not found Call to virDomainLookupByUUID failed: Domain not found: no domain with matching uuid '6e9d7668-5ecf-433d-bcc4-9464cb904b6d'.
 INFO machine: New machine ID: nil
 INFO interface: Machine: metadata ["provider", :libvirt, {:target=>:default}]
```
So because the machine domain is not found, it appears that the existing metadata is wiped


I can simulate this with the same user by doing the following:
```
export VAGRANT_DEFAULT_PROVIDER=libvirt
LIBVIRT_DEFAULT_URI=qemu:///session vagrant up
```
check the status
```
LIBVIRT_DEFAULT_URI=qemu:///session vagrant status
Current machine states:

default                   running (libvirt)

The Libvirt domain is running. To stop this machine, you can run
`vagrant halt`. To destroy the machine, you can run `vagrant destroy`.
```
Now switch the connection to system
```
LIBVIRT_DEFAULT_URI=qemu:///system vagrant status
Current machine states:

default                   not created (libvirt)

The Libvirt domain is not created. Run `vagrant up` to create it.
```

Even if we saved the connection details the session for the other user wouldn't show the machine, as it would be under a different session, so I'm not sure how we could protect here as there isn't an easy way to distinguish between a stale machine state and state belonging to another user. Once we return nil to vagrant for the machine not being found, it will remove the files as best I can tell. Returning something other than nil if we can't find the VM with the correct id would break the ability to clear out stale state by running `vagrant destroy -f`.

Best I could think of is to try and detect if the state files are owned by a different user and ask if it should continue, but I'm not sure if the provider is the right place for this, because it would impact every location that is querying the provider for the machine.
