### ISSUE TITLE
cannot create networks

### ISSUE THREAD

**Issue by zeddit** [vagrant-libvirt/vagrant-libvirt#1153]
I just followed the configuration in README to create a private network and public network, but there is no NIC interfaces show up in guest machine. 

I am using the latest qemu and libvirt, with latest vagrant. 

More, I noticed that the grammar used in vagrant-libvirt README seems not the most updated one. e.g.
```sh
# new style used in vagrant official site
test_vm1.vm.network "private_network", ip: "10.20.30.40"
```
vs.
```
test_vm1.vm.network :private_network, :ip => "10.20.30.40"
```

### Steps to reproduce
1. configure vm network in Vagrantfile as mentioned in README
2. vagrant up && vagrant ssh
3. ip link or ip addr to check out the NICs

### Expected behaviour
There should be dedicated NICs for each network configuration in Vagrantfile

### Actual behaviour
The number of NICs is the same with Vagrantfile of `vagrant init`, which called `eth0` with a IP of `192.168.121.41`

### System configuration
**OS/Distro version:**: ubuntu 18.04, kernel 5.4.0-48-generic

**qemu version:** 5.1.0, installed from source.

**Libvirt version:** 6.6.0, installed from tar source.

**Output of `vagrant version; vagrant plugin list`:** vagrant 2.2.10, vagrant-libvirt plugin 0.2.1

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
vagrant up --provider=libvirt
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
     config.vm.box = "generic/ubuntu1804"
     config.vm.network "private_network", ip: "192.168.33.10"
     config.vm.network "public_network", dev: "br0", mode: "bridge", type: "bridge"
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by uniqx** [comment]
Running into the same issue on Debian 10, with vanilla Debian 10 packages.

**Comment by electrofelix** [comment]
I don't have a bridge network handy to test this with at the moment, so might be a while to reproduce. If you have the ability to generate the debug log and attach it that would help.

Generally when it comes to networking and VMs it's a mixture of how the box was build, vagrant's networking scripts for the particular distro, and the provider itself.

To start narrowing it down with the `generic/ubuntu1804` image, it's worth checking which version you have, as I have a couple of versions:
```
vagrant box list | grep generic/ubuntu1804
generic/ubuntu1804              (libvirt, 1.9.12)
generic/ubuntu1804              (libvirt, 2.0.6)
generic/ubuntu1804              (libvirt, 3.1.6)
```

You can also use some of the suggestions in https://github.com/vagrant-libvirt/vagrant-libvirt#troubleshooting-vms to see what is happening.

I've just attempted to bring up the latest box without the `public_network` configured as I'm missing a bridge, and that worked as expected, so if you can confirm that you get both the management and private network when you remove the public network option it'll confirm that the source of the problem is likely something to do with the settings of the public network.

If you could run `virsh dumpxml <machine-name>` where machine name is a combination of the basename of the current directory and the vm name (would be 'default' in the above config). That will allow confirming whether vagrant-libvirt has put together the correct XML. Based on your comments, it's probably wrong if the additional nics are missing. The debug output will help me see what it thought it was passing to vagrant at that point as well.

**Comment by electrofelix** [comment]
With some help another person was able to get a public network created correctly for their machine in #1477. Based on being able to create one with the management network and private network and lack of further updates to this I'm having to assume that it's not related to vagrant-libvirt
