### ISSUE TITLE
Support OpenRC

### ISSUE THREAD

**Issue by 6543** [vagrant-libvirt/vagrant-libvirt#1175]
### Steps to reproduce
1. install ArtiX with OpenRC
2. install vagrant & libvirtd
3. try to do  `vagrant up`

### Expected behaviour
should start/check via `rc-service`

### Actual behaviour
```
Bringing machine 'default' up with 'libvirt' provider...
sh: systemctl: command not found
```

### System configuration
**OS/Distro version:** ArtiX

**Libvirt version:** 6.5.0

**Output of `vagrant version; vagrant plugin list`:**
```
> vagrant version
Installed Version: 2.2.14
Latest Version: 2.2.14

> vagrant plugin list
vagrant-libvirt (0.3.0, global)
```

**Comment by electrofelix** [comment]
@6543 AFAIK the execution of systemctl isn't coming from this project, as the code here never calls systemctl directly. A quick grep of all of the dependencies in my development workspace also suggest none of the dependencies call it either.

It's most likely caused by the hosts plugins from vagrant itself combined with incorrect host detection, https://github.com/hashicorp/vagrant/tree/main/plugins/hosts contains various plugins such as one for helping with NFS, there are some that help handle networking, etc. These are generally tailored to specific distributions as well as in some cases specific verisons. At a guest I'd say there is none defined for the ArtiX distribution and it's falling back to the detecting as arch linux which assumes systemctl is installed for various actions.

If you follow the docs at https://www.vagrantup.com/docs/vagrantfile/vagrant_settings#available-settings you should be able to force the host detection to a variant that doesn't use systemctl. I think the default linux one may try to detect either sysv or systemctl dynamically, but that might get other steps wrong compared to arch. Best solution is to ask the vagrant devs to create the various definitions for ArtiX
