### ISSUE TITLE
Got IP address, even though it's empty

### ISSUE THREAD

**Issue by leblowl** [vagrant-libvirt/vagrant-libvirt#1239]
Hey! Thanks for all your hard work on this project! I think there is a regression from 0.2.1 to 0.4.0. I am troubleshooting a VM and in 0.2.1 it would fail to retrieve the IP address (loop on `Waiting for domain to get an IP address...`), however in 0.4.0 it says `Got IP address ` (but doesn't actually list an IP address, because there is none) and then it hangs while connecting via SSH.

### Steps to reproduce
1. Using custom Vagrantfile
2. Run `VAGRANT_LOG=debug vagrant up`
3. Notice that it says `INFO wait_till_up: Got IP address ` (the IP address is empty) and then continues attempting to connect via SSH

### Expected behaviour
In 0.2.1 it would hang on `Waiting for domain to get an IP address...`, so that's what I was expecting and seems like the most user-friendly approach

### Actual behaviour
Continues trying to connect via SSH and fails

### System configuration
**OS/Distro version:**:
OpenSuse Tumbleweed

**Libvirt version:**
7.1.0

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 2.2.14
Latest Version: 2.2.14
 
You're running an up-to-date version of Vagrant!
vagrant-libvirt (0.4.0, global)

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
```
[vagrant.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6233234/vagrant.txt)
```
[vagrant.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/6233234/vagrant.txt)

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "opensuse-tw"

end
```
The Vagrantfile isn't really helpful by itself since it's a custom box, so here is the Packer file:
```
source "qemu" "opensuse-tw-base" {
  iso_url           = "https://download.opensuse.org/tumbleweed/appliances/openSUSE-Tumbleweed-JeOS.x86_64-kvm-and-xen.qcow2"
  iso_checksum      = "sha256:0969dd93babe86c90a669572647e7a95f92aa666425188f80876f5af7c209323"
  vm_name           = "opensuse-tw-base"
  disk_size         = "25G"
  format            = "qcow2"
  accelerator       = "kvm"
  disk_interface    = "virtio"
  disk_image        = true
  boot_wait         = "20s"
  boot_command      = [
    "<enter><enter><enter><enter>",
    "root<enter>",
    "root<enter>"
  ]
  ssh_username      = "root"
  ssh_password      = "root"
  ssh_timeout       = "5m"
  shutdown_command  = "shutdown now"
  output_directory  = "target"
}

build {
  sources = ["source.qemu.opensuse-tw-base"]

  post-processor "vagrant" {
    keep_input_artifact = true
  }
}
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
Distro

**Comment by leblowl** [comment]
Also noticing the empty IP address in a known working Vagrant box.

**In 0.2.1:**
```
 INFO wait_till_up: Got IP address 192.168.121.107
 INFO wait_till_up: Time for getting IP: 9.115898847579956
```

**In 0.4.0:**
```
 INFO wait_till_up: Got IP address 
 INFO wait_till_up: Time for getting IP: 3.0162413120269775
 INFO interface: info: Waiting for SSH to become available...
 INFO interface: info: ==> default: Waiting for SSH to become available...
==> default: Waiting for SSH to become available...
DEBUG ssh: Checking whether SSH is ready...
 INFO driver: Timeout at waiting for an ip address for machine default
 INFO driver: No arp table entry found for machine default
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHNotReady: The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.>
```

**Vagrantfile:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "opensuse/Tumbleweed.x86_64"

end
```

**Comment by electrofelix** [comment]
@leblowl so there is definitely an issue in failing to spot that the IP address hasn't been detected, currently looking at that.

However there is also an issue with your packer configuration and resulting box, in that it will use predictable device names, that unfortunately appears to be an issue with opensuse because it means it doesn't configure the device detected subsequently during boot in vagrant as the network device added by libvirt ends up being resolved with a different name to the device the VM was originally built using.

I'd suggest starting with looking at https://github.com/openSUSE/vagrant/blob/05c8c1959d9433d3c5245d48a539142095b41d9b/definitions/tumbleweed-x86_64.json#L89-L92 which I believe will ensure eth0 is used by default instead of ensX, where X changes from boot to boot, combined with https://github.com/openSUSE/vagrant/blob/05c8c1959d9433d3c5245d48a539142095b41d9b/scripts/base/cleanup.sh (specifically https://github.com/openSUSE/vagrant/blob/05c8c1959d9433d3c5245d48a539142095b41d9b/scripts/base/cleanup.sh#L14) and any of the other scripts there used to ensure any VMs created will reinitialize the network device eth0 and that should result in an image that can pick up an IP address subsequently. Possibly worth picking up some of the other scripts as well.

**Comment by leblowl** [comment]
@electrofelix Thanks for the fix! And yes, I figured out the issue was due to the device naming, but I wasn't sure how to pin the device at `eth0`. The link you shared looks like they were able to do that with some boot option `netdevice=eth0`, so that's great. Thank you so much for the help!
