### ISSUE TITLE
Export/Import Box as Original VM with `virsh dumpxml` and `virsh define`?

### ISSUE THREAD

**Issue by hswong3i** [vagrant-libvirt/vagrant-libvirt#1256]
A Standard Virtualbox Vagrant box `metadata.json` coming with following simple data structure, then reading all VM definition from bundled `box.ovf`:
```
{
  "provider": "virtualbox"
}
```

Currently our box `metadata.json` coming with following custom format, e.g.
```
{
  "format": "qcow2",
  "provider": "libvirt",
  "virtual_size": 128
}
```

For #602 and #1143 we are discussing add multiple disk support in our Vagrant box format, by [adding additional key/value into `metadata.json`](https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1143/files#diff-515fec02588d6d41f3df9bce232b39a18d0352959c7b51f68fa459f55ef97a52R18-R30), e.g.
```
{
  "provider": "libvirt",
  "format": "qcow2",
  "disks": [
    {
      "virtual_size": 2
    },
    {
      "path": "disk2.qcow2",
      "virtual_size": 10
    }
  ]
}
```

With this direction, if we going to support additional NIC/USB/COM/etc device into vagrant-libvirt, we will keep bumping the custom structure into `metadata.json`, which is not scalable ;-(

What if we [export our VM with `virsh dumpxml`, then import it with `virsh define`](https://serverfault.com/a/707564/628984)? This come with a lot of benefits:

- Keeping `metadata.json` clean and tidy
- Support all original VM definition, e.g. `box.xml` (similar as Virtualbox's `box.ovf` format and functionality)

 
### Steps to reproduce
During `vagrant package`:
1. Export VM definition with `virsh dumpxml`
2. Search the exported `box.xml` for the disk image path and copy to local directory for packaging
3. Package both `metadata.json`, `Vagrantfile`, `box.xml`, and `*.qcow2` as our Vagrant Box archive

During `vagrant up`:
1. Restore original VM definition with `virsh define`
2. Search the `box.xml` for disk image filename, and copy to target directory, and update the VM definition with new disk image absolute path
3. Regenerate a new `<uuid>` for the imported VM
4. Remove some parameters that may conflict, e.g. `<cpu>`, `<interface>`, etc
4. Overwrite other else VM definition as per our existing logic

### Expected behaviour
Extracted box archive should coming with following files, e.g.:
```
box.xml
metadata.json
alvistack-VAGRANTSLASH-ubuntu-20.04_vagrant_box_image_20210425.0.0_0.img
vagrant-libvirt-vagrant-libvirt_default-vdb.qcow2
Vagrantfile
```

Where `metadata.json` simplified as: 
```
{
  "provider": "libvirt"
}
```

And `box.xml` in format that export by `virsh xmldump` and could import by `virsh define`, e.g.
```
<domain type='kvm' id='1'>
  <name>vagrant-libvirt-vagrant-libvirt_default</name>
  <uuid>778d5ab8-997e-4b11-82a6-cb6eb595cb32</uuid>
  <memory unit='KiB'>524288</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-hirsute'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Icelake-Client</model>
    <vendor>Intel</vendor>
    <feature policy='require' name='ss'/>
    <feature policy='require' name='vmx'/>
    <feature policy='require' name='pdcm'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='tsc_adjust'/>
    <feature policy='require' name='avx512f'/>
    <feature policy='require' name='avx512dq'/>
    <feature policy='require' name='avx512ifma'/>
    <feature policy='require' name='clflushopt'/>
    <feature policy='require' name='avx512cd'/>
    <feature policy='require' name='sha-ni'/>
    <feature policy='require' name='avx512bw'/>
    <feature policy='require' name='avx512vl'/>
    <feature policy='require' name='rdpid'/>
    <feature policy='require' name='fsrm'/>
    <feature policy='require' name='md-clear'/>
    <feature policy='require' name='stibp'/>
    <feature policy='require' name='arch-capabilities'/>
    <feature policy='require' name='xsaves'/>
    <feature policy='require' name='pdpe1gb'/>
    <feature policy='require' name='ibpb'/>
    <feature policy='require' name='amd-stibp'/>
    <feature policy='require' name='amd-ssbd'/>
    <feature policy='require' name='rdctl-no'/>
    <feature policy='require' name='ibrs-all'/>
    <feature policy='require' name='skip-l1dfl-vmentry'/>
    <feature policy='require' name='mds-no'/>
    <feature policy='require' name='pschange-mc-no'/>
    <feature policy='disable' name='hle'/>
    <feature policy='disable' name='rtm'/>
    <feature policy='disable' name='mpx'/>
    <feature policy='disable' name='intel-pt'/>
    <feature policy='disable' name='wbnoinvd'/>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/vagrant-libvirt-vagrant-libvirt_default.img' index='2'/>
      <backingStore type='file' index='3'>
        <format type='qcow2'/>
        <source file='/var/lib/libvirt/images/alvistack-VAGRANTSLASH-ubuntu-20.04_vagrant_box_image_20210425.0.0_0.img'/>
        <backingStore/>
      </backingStore>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/vagrant-libvirt-vagrant-libvirt_default-vdb.qcow2' index='1'/>
      <backingStore/>
      <target dev='vdb' bus='virtio'/>
      <alias name='virtio-disk1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='piix3-uhci'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <interface type='network'>
      <mac address='52:54:00:44:28:8f'/>
      <source network='vagrant-libvirt' portid='bb3069b0-92c0-47db-b19f-f7855db885f4' bridge='virbr1'/>
      <target dev='vnet0'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
    <serial type='pty'>
      <source path='/dev/pts/4'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
    <console type='pty' tty='/dev/pts/4'>
      <source path='/dev/pts/4'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <input type='mouse' bus='ps2'>
      <alias name='input0'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input1'/>
    </input>
    <graphics type='vnc' port='5900' autoport='yes' listen='127.0.0.1' keymap='en-us'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <stats period='5'/>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='apparmor' relabel='yes'>
    <label>libvirt-778d5ab8-997e-4b11-82a6-cb6eb595cb32</label>
    <imagelabel>libvirt-778d5ab8-997e-4b11-82a6-cb6eb595cb32</imagelabel>
  </seclabel>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+0:+0</label>
    <imagelabel>+0:+0</imagelabel>
  </seclabel>
</domain>
```

**Comment by electrofelix** [comment]
@hswong3i if you look at the domain template vagrant-libvirt constructs and sends to libvirt, you'll notice that libvirt itself makes quite a few modifications and changes depending on both host environment and other machines running. The short summary is it may be possible, it's not clear if it makes things much better, has some downsides, and would likely need a fair amount of effort to implement. If you believe this is a good way to go, I'm happy to provide pointers around some of the areas that would need some initial work to allow it to be implemented in parallel without breaking the existing supported behaviour.

For example:
```
      <mac address='52:54:00:44:28:8f'/>
      <source network='vagrant-libvirt' portid='bb3069b0-92c0-47db-b19f-f7855db885f4' bridge='virbr1'/>
      <target dev='vnet0'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
```

The mac address, source network and bridge are both provided by vagrant-libvirt depending on what is defined, ideally we may need to remove `<target dev='vnet0'/>` and let libvirt auto allocate it to avoid other issues, the model type depends on settings in vagrant-libvirt, and the address element is typically automatically defined by libvirt and may depend on how it wants to lay things out.

The following is likely ubuntu specific and there are different blocks added on fedora, meaning this would depend entirely on the distro:
```
  <seclabel type='dynamic' model='apparmor' relabel='yes'>
    <label>libvirt-778d5ab8-997e-4b11-82a6-cb6eb595cb32</label>
    <imagelabel>libvirt-778d5ab8-997e-4b11-82a6-cb6eb595cb32</imagelabel>
  </seclabel>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+0:+0</label>
    <imagelabel>+0:+0</imagelabel>
  </seclabel>
```

The path in the following is specific to the host and I believe also depends on the order VMs are started
```
    <serial type='pty'>
      <source path='/dev/pts/4'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
```

Port number for vnc depends on what other VMs are running and what port they are using
```
    <graphics type='vnc' port='5900' autoport='yes' listen='127.0.0.1' keymap='en-us'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
```

The problem around having specific devices in the XML for each box is that the vagrant-libvirt code needs to understand them all, and be able to modify a number of them to allow libvirt to auto regenerate in some cases and retain in others. This might be more flexible than the current approach, but at the same time it may also be more fragile. So I suspect it would take a decent amount of investigation.

There is the added complexity of newer versions of libvirt adding additional elements/settings that may not be supported on older versions of libvirt and vagrant-libvirt on those would have to adjust the XML to be compatible or at package time would have to tidy the XML up, or embed a libvirt verions and have vagrant-libvirt on the system trying to bring it up ensure that libvirt is new enough, because dumpxml, while it supports generating migratable output, doesn't necessary cover generating output compatible with older releases. It may well be capable of doing so, but there is no guarantee.

Also for consideration is that tools like packer would have to have the vagrant + libvirt builder switch to supporting generating XML, note that packer doesn't use libvirt at all, it uses qemu directly and then wraps the box image file with a simple metadata.json and Vagrantfile generated from templates.

Note the Vagrantfile packaged with each box can already include additional devices configuration that are then automatically applied by vagrant-libvirt. So technically you can have a box create an additional storage when it is brought up. What it can't handle is referencing the additional disks bundled with the box. Technically there is nothing stopping putting that knowledge into the bundled Vagrantfile instead of the metadata.json.

Using the XML to describe the bundled box could be worked towards over time, in fact one of the reasons to have a driver.rb was partly to try and move some of the pieces that might have to be different between versions and approaches to facilitate multiple versions of the driver where we can't provide compatibility between the approaches, and simply need to have a different implementation.

**Comment by hswong3i** [comment]
@electrofelix What if we refine the import logic: load in the box.xml, selectively apply as our default value during box creation, rather than our current hard-coded default value?

This could keep the export logic simple with 'virsh dumpxml' for 3rd party implementation, e.g. packer which I am using daily.

On the other hand the dumped xml should be the most complete structure for defining a running VM, so we could avoid another round of matadata.json structure upgrade if additional feature added.

Selectively apply as default value could also reduce the complexity for implementing a complete phaser for the dumped xml across multiple version of libvirt (or, shall we utilize the ruby-libvirt for fetching our target distilled default value?)

For backward compatibility, just simply keep our existing logic and default value if the 'box.xml' not found (e.g. assume the root disk with file name 'box.img').

**Comment by hswong3i** [comment]
@electrofelix the result of `virt-v2v -i libvirt -o local` looks clean and elegant and portable enough as a startup template during initial import phase, therefore we could overwrite our custom parameters on top of it without difficulties? 

```
$ cat box.xml
<?xml version='1.0' encoding='utf-8'?>
<domain type='kvm'>
  <!-- generated by virt-v2v 1.44.0 -->
  <name>box</name>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo='http://libosinfo.org/xmlns/libvirt/domain/1.0'>
      <libosinfo:os id='http://ubuntu.com/ubuntu/20.04'/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit='KiB'>524288</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
  <vcpu>1</vcpu>
  <features>
    <acpi/>
    <apic/>
  </features>
  <os>
    <type arch='x86_64' machine='q35'>hvm</type>
  </os>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <devices>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/tmp/tmp.jZxYGXnnn7/box-sda'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/tmp/tmp.jZxYGXnnn7/box-sdb'/>
      <target dev='vdb' bus='virtio'/>
    </disk>
    <interface type='network'>
      <source network='vagrant-libvirt'/>
      <model type='virtio'/>
      <mac address='52:54:00:09:6b:e9'/>
    </interface>
    <video>
      <model type='qxl' ram='65536' heads='1'/>
    </video>
    <graphics type='vnc' keymap='en-us' autoport='yes' port='-1'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
    </rng>
    <memballoon model='virtio'/>
    <panic model='isa'>
      <address type='isa' iobase='0x505'/>
    </panic>
    <viosock model='none'/>
    <input type='tablet' bus='usb'/>
    <input type='mouse' bus='ps2'/>
    <console type='pty'/>
  </devices>
</domain>
```
