### ISSUE TITLE
disk_device has no effect

### ISSUE THREAD

**Issue by rgl** [vagrant-libvirt/vagrant-libvirt#1353]
### Steps to reproduce

Call `lv.disk_device = 'sda'` in a Vagranfile like:

```
Vagrant.configure('2') do |config|
  config.vm.provider :libvirt do |lv, config|
    lv.disk_bus = 'scsi'
    lv.disk_device = 'sda'
    lv.disk_driver :bus => 'scsi', :discard => 'unmap', :cache => 'unsafe'
```

### Expected behaviour

I expected to see a `/dev/sda` device inside the VM, but it still shows as `/dev/vda`.

### Actual behaviour

The disk device is still `/dev/vda` as displayed by virt-manager:

![screenshot](https://user-images.githubusercontent.com/43356/133895539-94c57660-dce3-49e3-85b2-854e6997adda.png)

### System configuration

**OS/Distro version:** Ubuntu 20.04

**Libvirt version:** 6.0.0-0ubuntu8.14

**Comment by rgl** [comment]
Hummm even though the libvirt domain xml has `vda`, linux will map it as `sda`. So I'm not sure if this issue actually matters in practice. Feel free to close it.

**Comment by electrofelix** [comment]
It might do, however it's supposed to use the device leading characters as a hint as to which type of disk it should be, and in any case it should be setting it as according to the vagrant-libvirt documentation.

Looks like we introduced a bug when adding latent support for multiple disks in a box image.

Following should fix it, but currently untested.
```
--- lib/vagrant-libvirt/action/create_domain.rb
+++ lib/vagrant-libvirt/action/create_domain.rb
@@ -145,6 +145,10 @@ module VagrantPlugins
             else
                 pool_name = @storage_pool_name
             end
+
+            # special handling for domain volume
+            env[:box_volumes][0][:device] = env[:box_volumes][0].fetch(:device, @disk_device)
+
             @logger.debug "Search for volumes in pool: #{pool_name}"
             env[:box_volumes].each_index do |index|
               suffix_index = index > 0 ? "_#{index}" : ''
@@ -152,8 +156,9 @@ module VagrantPlugins
                 name: "#{@name}#{suffix_index}.img"
               ).find { |x| x.pool_name == pool_name }
               raise Errors::DomainVolumeExists if domain_volume.nil?
+
               @domain_volumes.push({
-                :dev => (index+1).vdev.to_s,
+                :dev => env[:box_volumes][0].fetch(:device, (index+1).vdev.to_s),
                 :cache => @domain_volume_cache,
                 :bus => @disk_bus,
                 :path => domain_volume.path,
```

**Comment by rgl** [comment]
It worked! Now the libvirt xml has `sda` :-)

`lv.storage :file, :device => 'sda', :bus => 'scsi'` works too.

Thank you!

**Comment by electrofelix** [comment]
I'm a couple of yaks deep in trying to fix this. In order to fix it I have to make it work correctly with multi disk boxes, and as such I need to fix the resolving of the disk device names, where the default behaviour is to assume that only the first device is reserved and any additional storage added in the vagrantfile can start at `vdb` as only `vda` was reserved. With the advent of multi disk boxes, it will be necessary to move resolving of disk devices to after when the box is downloaded, which will then allow the `@disk_device` to be respected (and used to control whether the box volumes use `vdX` or `sdX` to be consistent with the entire set).

While I have that working, it turns out removing the code with the invalid assumptions from the config object breaks domain destroy, because it contains a series of now incorrect assumptions around disk devices being resolved at this stage as well as there being only a single box disk.

But to solve this properly, it will need parsing the domain XML and iterating over the disk devices listed in this domain definition, and since the box may have been removed at this point, cannot perform the same device resolution in order to establish which disk devices to remove and which to retain.

So, parked fixing this until I rework the domain destroy. It shouldn't be too hard, but likely requires walking the list of disk devices in reverse, ignoring `cdroms`, and deleting any disks that should be removed, then deleting the remaining disks that are associated with the box. Doing it this way should allow this to work for both single and multi disk boxes without needing to rely on having the box metadata around to inspect.

As part of this work, I'm likely going to add aliases to all the disk devices in order to make them easier to delete at a future stage, but will need domains to have been created with the new code before then.

Fun times, in case you're wondering why it's taking a while to apply what initially looked like a simple fix ;-)

Might try and finish off the hidden support for packaging into a V2 box format initially and then come back at this to fix the delete and then subsequently fix the resolving of disk devices, and as part of that respect the value set for `@disk_device`. Alternatively I may just move the fix to only be respected for V1 boxes for now, but I'll still have to fix it for V2 style boxes in order for them to now cause lots of issues anyway.

**Comment by rgl** [comment]
Thank you for sharing the details! It sure seems fun getting all of those details aligned!

And no worries about parking this :-)

**Comment by electrofelix** [comment]
Oh it's interesting and while I was aware of some of the underlying problems, which likely need to be fixed to release the V2 packaging support either way, I just didn't expect this particular problem to end up needing to address them at the same time

**Comment by electrofelix** [comment]
Latest code should now fix this correctly, though might be a couple of weeks before I do another release as the rework on the destroy domain and here for the device handling is sufficiently different that I don't think I could call it a bugfix release anymore.
