### ISSUE TITLE
support podman in addition to docker

### ISSUE THREAD

**Issue by ikke-t** [vagrant-libvirt/vagrant-libvirt#1357]
Instructions are made to run vagrant-libvirt with docker. Please guide the same for podman.

### Steps to reproduce
1. podman run -it --rm \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
  vagrantlibvirt/vagrant-libvirt:latest \
    vagrant status
2.
3.

### Expected behaviour
it should work

### Actual behaviour

```
IGNORE_MISSING_LIBVIRT_SOCK=true podman run -it --rm \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
  vagrantlibvirt/vagrant-libvirt:latest vagrant up
WARNING! Running as root, if this breaks, you get to keep both pieces
Starting with UID: 0, GID: 0
chown: invalid user: 'vagrant:users'
Unless you are using this to connect to a remote libvirtd it is
necessary to mount the libvirt socket in as /var/run/libvirt/libvirt-sock

Set IGNORE_MISSING_LIBVIRT_SOCK to silence this warning
error: failed switching to "vagrant": unable to find user vagrant: no matching entries in passwd file
```

### System configuration
**OS/Distro version:**:

RHEL8

**Libvirt version:**

libvirt-6.0.0-35.1.module+el8.4.0+11273+64eb94ef.x86_64

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
vagrant-2.2.7-1.x86_64

**Comment by AverageHumanoid** [comment]
I was able to get Podman to work by manually creating `~/.vagrant.d/{boxes,data,tmp}` then adding

```
--security-opt label=disable \
--entrypoint /bin/bash \
```
to the run time options.

**Comment by electrofelix** [comment]
@ikke-t can you try running with the edge tagged image `vagrantlibvirt/vagrant-libvirt:edge`, the latest image points to the latest release and there are a number of fixes on the main branch that should help.

@AverageHumanoid the edge release should remove the need for creating the `~/.vagrant.d/{boxes,data,tmp}` directories by hand.

**Comment by ikke-t** [comment]
```
IGNORE_MISSING_LIBVIRT_SOCK=true podman run -it --rm \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
  vagrantlibvirt/vagrant-libvirt:edge vagrant up
WARNING! Running as root, if this breaks, you get to keep both pieces
Starting with UID: 0, GID: 0
chown: invalid user: 'vagrant:users'
Unless you are using this to connect to a remote libvirtd it is
necessary to mount the libvirt socket in as /var/run/libvirt/libvirt-sock

Set IGNORE_MISSING_LIBVIRT_SOCK to silence this warning
error: failed switching to "vagrant": unable to find user vagrant: no matching entries in passwd file
```

**Comment by AverageHumanoid** [comment]
You can't use a rootless container, you need to run Podman with root privileges.

**Comment by ikke-t** [comment]
```
IGNORE_MISSING_LIBVIRT_SOCK=true sudo podman run  -u vagrant -it --rm \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
  vagrantlibvirt/vagrant-libvirt:edge vagrant up
Error: unable to find user vagrant: no matching entries in passwd file
```

**Comment by AverageHumanoid** [comment]
You also need to disable SELinux for add `--security-opt label=disable`

**Comment by AverageHumanoid** [comment]
and don't run with `-u vagrant`

**Comment by ikke-t** [comment]
ok, i forgot that when i tried to get rid of the wanrnings. Now it seems selinux likely blocks it, as it tries to connect as root into my home dirs:
``
sudo podman run -it --rm -e IGNORE_MISSING_LIBVIRT_SOCK \     
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
  vagrantlibvirt/vagrant-libvirt:edge vagrant up
Starting with UID: 27210, GID: 27210
Unless you are using this to connect to a remote libvirtd it is
necessary to mount the libvirt socket in as /var/run/libvirt/libvirt-sock

Set IGNORE_MISSING_LIBVIRT_SOCK to silence this warning
Traceback (most recent call last):
	12: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant:231:in `<main>'
	11: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:290:in `cli'
	10: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/cli.rb:67:in `execute'
	 9: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/plugins/commands/up/command.rb:87:in `execute'
	 8: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/plugin/v2/command.rb:105:in `with_target_vms'
	 7: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/plugin/v2/command.rb:105:in `any?'
	 6: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/plugin/v2/command.rb:106:in `block in with_target_vms'
	 5: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:724:in `machine_index'
	 4: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:724:in `new'
	 3: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:52:in `initialize'
	 2: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `with_index_lock'
	 1: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `open'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `initialize': Permission denied @ rb_sysopen - /vagrant/data/machine-index/index.lock (Errno::EACCES)
	11: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant:234:in `<main>'
	10: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant:234:in `ensure in <main>'
	 9: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:775:in `unload'
	 8: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:526:in `hook'
	 7: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:34:in `run'
	 6: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:206:in `block in action_runner'
	 5: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:724:in `machine_index'
	 4: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:724:in `new'
	 3: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:52:in `initialize'
	 2: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `with_index_lock'
	 1: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `open'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `initialize': Permission denied @ rb_sysopen - /vagrant/data/machine-index/index.lock (Errno::EACCES)
```

**Comment by electrofelix** [comment]
@ikke-t with your testing has `~/.vagrant.d` or some of the files under it ended up being owned by root?

a `sudo chown -R $(id -u):$(id -g) ${HOME}/.vagrant.d` might be needed to get them back to the correct owner before running the container again.

**Comment by ikke-t** [comment]
same error

**Comment by ikke-t** [comment]
```-rw-r--r--. 1 itengval itengval unconfined_u:object_r:user_home_t:s0 0 24. 9. 16:15 /home/itengval/.vagrant.d/data/machine-index/index.lock
```

**Comment by electrofelix** [comment]
I don't see the option ` --security-opt label=disable` in the command line you posted as mentioned above by @AverageHumanoid in https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1357#issuecomment-930118751

Is that missing?

**Comment by ikke-t** [comment]
BTW,  it works just fine without sudo when there is no label checks

**Comment by AverageHumanoid** [comment]
Running without root privilege doesn't work for me with the message:

```
WARNING! Running as root, if this breaks, you get to keep both pieces
Starting with UID: 0, GID: 0
chown: invalid user: 'vagrant:users'
groupmod: GID '65534' already exists
```

**Comment by electrofelix** [comment]
So it allows the container to run with uid 0 in the pod, just that it's mapped to a different user than root on the host? Root is only needed in the entrypoint of the container to ensure that some files can be moved around at:
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/5de17b0d011bee6e3a73d19a67987706e9e30eaa/entrypoint.sh#L101-L112

Consequently it's necessary to create a user with the same uid/gid as the external user and do some group set to allow access to the socket paths.

To access the ansible files, if you change the argument `-v $(realpath "${PWD}"):${PWD}` to something like `  -v $(realpath "${PWD}../"):$(realpath "${PWD}/..")`, it should mount in the parent directory instead of the current directory. Just as long as you keep `-w $(realpath "${PWD}")` it will still start off with the correct working path to find the Vagrantfile within the running container.

If you resolve the path in the Vagrantfile for anything using `'~/<path>'` you can try mounting in the files/directories e.g. `-v ${HOME}/.ssh:${HOME}/.ssh`. Might be lucky that if the access is direct, won't need to read the parent directories created automatically in the container by runc, as they should be executable by default.

**Comment by electrofelix** [comment]
I'd recommend avoiding trying to run via root, you can override the entrypoint to use `/bin/bash` if you need to do so and then tinker with what ever is desired. Could probably fix the script to simply exit before trying to set up the custom user in that case at least.

**Comment by AverageHumanoid** [comment]
Ok using `--entrypoint /bin/bash` when using a rootless container works. So should I remove `sudo` add `--entrypoint /bin/bash` back in #1359?

**Comment by AverageHumanoid** [comment]
Actually if we are bypassing `entrypoint.sh` then the `latest` tag also works and don't need `edge`.

**Comment by electrofelix** [comment]
@AverageHumanoid the container has `VAGRANT_HOME` set to `/vagrant/` in the container to allow it to pick up the previously built vagrant-libvirt plugin, but that also means that any boxes downloaded and machines index created end up under `/vagrant/` and will be discarded when the container exists unless the user directories are added to the correct places e.g. host `~/.vagrant.d/boxes` mounted in container as `/vagrant/boxes` and host `~/.vagrant.d/data` mounted in container as `/vagrant/data`.

However if the effective uid/gid of the container is different to the host user, those files will then either be unwritable in the container or become unwritable if you also use vagrant outside with virtualbox.

Maybe podman has solved this problem that impacts docker (and maybe rootless docker also solves it), I'm not familiar enough with how it works to determine. The entrypoint is trying to work avoid some of the issues with what uid/gid created files end up having, and ensure that boxes and the index are persisted between runs. If these problems don't exist for podman then the instructions can be simplified and the entrypoint replaced.

**Comment by AverageHumanoid** [comment]
When using rootless Podman, `root` inside the container maps to the uid/gid of host user outside so there shouldn't be any conflict from bypassing the entrypoint.

**Comment by electrofelix** [comment]
@AverageHumanoid just need to alter the mount paths so, instead of `-v ~/.vagrant.d:/.vagrant.d`, use `-v ~/.vagrant.d/boxes:/vagrant/boxes -v ~/.vagrant.d/data:/vagrant/data` so that both boxes and machine index files are available under the correct paths inside the container.

Otherwise it won't persist after container exit (you could avoid removing it and restart the same container each time to avoid this, but probably easier to change the mount paths).

**Comment by AverageHumanoid** [comment]
Done.

**Comment by alexanderadam** [comment]
I wanted to give the Podman solution a try since [the native solution didn't work](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1498) on Ubuntu 22.04 (Jammy Jellyfish).
But the Podman way resulted in

```
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
```

I used [the function mentioned in the README](https://github.com/vagrant-libvirt/vagrant-libvirt#using-podman) so `--security-opt label=disable` should be included.

![Error while connecting to Libvirt: Error making a connection to libvirt URI qemu:///system: Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied](https://user-images.githubusercontent.com/372620/169642108-74a96d6f-0ac5-41cb-bec6-4ddcb6985a92.png)

Any idea what I might be missing?

**Comment by electrofelix** [comment]
@alexanderadam can you confirm that your user can access the socket from the host first?

The following should make sure that virsh uses the socket directly, if you can't access this, likely need to confirm groups are configured correctly
```
virsh -c qemu+unix:///system?/var/run/libvirt/libvirt-sock list --all
```

If that works, then I suggest running the podman command without the trailing `vagrant $@` so that you are dropped into the container shell and then inspect the contents of `/var/run/libvirt/` to see what is shown when inside.

As I don't use podman directly myself I've been relying on others to confirm the expected behaviour with it, will look at spinning up a ubuntu 22.04 environment at some stage to test podman inside to try and understand a bit more.

**Comment by alexanderadam** [comment]
````bash
❯ virsh -c qemu+unix:///system?/var/run/libvirt/libvirt-sock list --all
 Id   Name    State
------------------------
 -    someVmName   shut off
```

> If that works, then I suggest running the podman command without the trailing `vagrant $@` so that you are dropped into the container shell and then inspect the contents of `/var/run/libvirt/` to see what is shown when inside.

Hm, when I call

```bash
podman run -it --rm -e LIBVIRT_DEFAULT_URI -v /var/run/libvirt/:/var/run/libvirt/ -v ~/.vagrant.d/boxes:/vagrant/boxes -v ~/.vagrant.d/data:/vagrant/data -v ~/.vagrant.d/tmp:/vagrant/tmp -v $(realpath "${PWD}"):${PWD} -w $(realpath "${PWD}") --network host --entrypoint /bin/bash --security-opt label=disable docker.io/vagrantlibvirt/vagrant-libvirt:latest
```

and navigate to `/var/run/libvirt/` I'm seeing this:

![image](https://user-images.githubusercontent.com/372620/169647334-0dac67b9-2820-440a-bbcf-aeec8675d7c9.png)

**Comment by gigi206** [comment]
Same issue here, it seems to work if you add the **--group-add=keep-groups** to the podman command
