### ISSUE TITLE
Please support Libvirt Modular Daemons

### ISSUE THREAD

**Issue by pvalena** [vagrant-libvirt/vagrant-libvirt#1405]
**Describe the bug**
Libvirt Modular Daemons are installed by default in Fedora 35. This means that with a fresh installaton, to use Vagrant, running a service is needed:

```
$ sudo systemctl start virtnetworkd.service
```

**To Reproduce**
```
There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: internal error: /usr/libexec/qemu-bridge-helper --use-vnet --br=virbr0 --fd=27: failed to communicate with bridge helper: Transport endpoint is not connected
stderr=failed to get mtu of bridge `virbr0': No such device 
```
Please refer to original bug for more: https://bugzilla.redhat.com/show_bug.cgi?id=2025202

**Comment by electrofelix** [comment]
This doesn't sound like something that can be fixed from this end, as essentially this project is calling the libvirt API and relying on it to take care of what it needs.

Sounds like a bug in the packaging or the modular daemons in that either a required service should be running automatically after install or is failing to be activated by libvirt performing an action and thus requires manual starting.

Unless virt-manager does something in addition when talking to libvirt, that all other apps are supposed to do as well, I don't think there will be anything to be done here.

**Comment by pvalena** [comment]
Makes sense, thanks!

**Comment by electrofelix** [comment]
This looks suspiciously like the same issue as #1258

**Comment by FollieHiyuki** [comment]
Hi. I'm new to vagrant and messing around with my system :) but here is my experience so far.

When I strictly enable only modular services (instead of the monolithic `libvirtd`), libvirt will communicate through sockets `/var/run/libvirt/virt${DRIVER}d-*sock` instead of `/var/run/libvirt/libvirt-sock` so running for example `vagrant status` will now fail, since the monolithic socket doesn't exist.

It would be nice if `vagrant-libvirt` supports the new modular daemons, while still provides backward compatible with the historical socket (until it is deprecated by upstream).

For reference, here is the official docs for modular daemons: https://libvirt.org/daemons.html

**Comment by electrofelix** [comment]
@FollieHiyuki The latest vagrant-libvirt doesn't select which socket to talk to, it relies completely on the behaviour of the libvirt API and when using sessions it will call the networking API that results in the networking part being up and available. The fix for the networking part is not yet released so would require installing from the latest commit.

Alternatively if you want to continue using the packaged version persuade Fedora to pick up the patch in https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1409 and carry it until they can pick up a subsequent release.

You'll also need to reboot after installing libvirt as Fedora does not support libvirt being available until after a reboot. So AFAIK the code is working provided the latest code is used and the host system is rebooted after install.

I don't have the ability to spin up a Fedora 35 VM to experiment as there hasn't been a box published yet.

Installation instructions to use latest vagrant-libvirt:
```
# if you've enabled the hashicorp repo, will need to disable it
sudo dnf config-manager --set-disabled hashicorp

sudo dnf update
sudo dnf install @virtualization vagrant-libvirt
dependencies=$(sudo dnf repoquery --qf "%{name}" $(for dep in $(sudo dnf repoquery --depends vagrant-libvirt 2>/dev/null | cut -d' ' -f1); do echo "--whatprovides ${dep} "; done) 2>/dev/null)
sudo dnf mark install ${dependencies}
sudo dnf remove vagrant-libvirt
# you can reboot now or after the remaining steps, but must reboot before attempting to use libvirt

git clone https://github.com/vagrant-libvirt/vagrant-libvirt
cd vagrant-libvirt
bundle config set --local path `pwd`/vendor
bundle install
bundle exec rake build

vagrant plugin install $(ls -1 pkg/vagrant-libvirt-*.gem | tail -n 1)

# reboot now if not done so previously.
```

**Comment by FollieHiyuki** [comment]
Thanks for the clarification.

For context, I was using the latest Docker image in Alpine. That probably was the reason why it was not working. I tried to build from source yesterday as you suggested and it works now.
