### ISSUE TITLE
Potential plugins collision

### ISSUE THREAD

**Issue by magaboomchen** [vagrant-libvirt/vagrant-libvirt#1419]
**Describe the bug**

When I only install vagrant-libvirt, it works.
But, when I also install following plugins, i.e. vagrant-vbguest  and vagrant-disksize.
PS:vagrant-disksize-0.1.3
vagrant-vbguest-0.30.0
Then I can't turn up Vagrant using libvirt.

**To Reproduce**

**Expected behavior**

**Screenshots**

Here is the record of my commandline:
smith@dell-r740-4:/data/VagrantBox/fedora$ vagrant up --provider="libvirt"
Bringing machine 'test_vm' up with 'libvirt' provider...
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

**Versions (please complete the following information):**:
- Libvirt version:    0.7.0
- Vagrant version [output of `vagrant version`]:  2.2.19
- Vagrant flavour [Upstream or Distro]: 
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
```
Delete this text and drag and drop the log file for github to attach and add a link here
```

**A Vagrantfile to reproduce the issue:**
```
[Insert Vagrantfile inside quotes here (remove sensitive data if needed)](https://app.vagrantup.com/zvfvrv/boxes/osm7
host OS: ubuntu 20.04 
KVM)
```

**Comment by electrofelix** [comment]
This is caused by vagrant-disksize attempting to load VirtualBox when that plugin is loaded, unfortunately nothing we can do about it in this plugin.

See https://github.com/sprotheroe/vagrant-disksize/issues/45 for a previous bug report against the upstream project that doesn't appear to have received any attention.

The only solution is to not install vagrant-disksize unless you plan on using VirtualBox or install VirtualBox but don't use it.
