### ISSUE TITLE
installation fails on RHEL 8

### ISSUE THREAD

**Issue by notklaatu** [vagrant-libvirt/vagrant-libvirt#1428]
When I run `vagrant plugin install vagrant-libvirt`, I get this error:

```
racc requires Ruby version >= 2.5.
```

However, I have a Ruby version meeting that requirement:

```
$ ruby -v
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
```

I've also tried building the gem locally and installing it, but I get the same error.

I've also run this based on the README:

```
$ CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt
```

Vagrant version is the latest from hashicorp, libvirt is current, etc:

```
$ vagrant -v
Vagrant 2.2.7
$ dnf info libvirt
Name         : libvirt
Version      : 6.0.0
[...]
```

OS version:

```
$ cat /etc/os-release | grep VERS
VERSION="8.5 (Ootpa)"
VERSION_ID="8.5"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
```

Anything obvious I'm missing?

**Comment by electrofelix** [comment]
Latest version of vagrant would be 2.2.19, rather than 2.2.7. I'd recommend upgrading as earlier releases had issues resolving depending versions correctly.

Note that when you use vagrant from hashicorp, the package has its own version of ruby bundled, it doesn't use the system version.

You may find following the script at https://github.com/vagrant-libvirt/vagrant-libvirt-qa/blob/9e699e2c8f72721c1556b4daf14b1a9f3d771ea1/scripts/install.bash for how vagrant and vagrant-libvirt are installed on CentOS may be needed to install correctly. It's still a work in progress but it's should show you what is needed fairly well

**Comment by notklaatu** [comment]
Thanks for that. I didn't even notice that I'd accidentally installed Vagrant from a different repo.

I uninstalled, and re-installed the *actual* hashicorp RPM and everything is working as intended.

```
$ CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Fetching fog-libvirt-0.9.0.gem
Fetching vagrant-libvirt-0.7.0.gem
Installed the plugin 'vagrant-libvirt (0.7.0)'!
```

Success, cheers.
