### ISSUE TITLE
Docker installation: user vagrant does not exist

### ISSUE THREAD

**Issue by canozyurt** [vagrant-libvirt/vagrant-libvirt#1442]
**Describe the bug**
Docker installation steps lead to "user vagrant does not exist" error

**To Reproduce**
1. Fresh 18.04, installed libvirt and docker-ce. kvm-ok returns positive. libvirt-sock in place.
2. Run
```
docker run -it --rm \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
  vagrantlibvirt/vagrant-libvirt:latest \
    vagrant status
```

**Debug Log**
```
WARNING! Running as root, if this breaks, you get to keep both pieces
Starting with UID: 0, GID: 0
error: failed switching to "vagrant": unable to find user vagrant: no matching entries in passwd file
error: failed switching to "vagrant": unable to find user vagrant: no matching entries in passwd file
error: failed switching to "vagrant": unable to find user vagrant: no matching entries in passwd file
chown: invalid user: 'vagrant:users'
usermod: user 'vagrant' does not exist
```

**Comment by electrofelix** [comment]
Sorry took a while to look at this properly, the problem is the following lines in the documentaiton:
```
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
```

They should read either:
```
  -v $(realpath "${PWD}"):${PWD} \
  -w ${PWD} \
```
or
```
  -v $(realpath "${PWD}"):$(realpath "${PWD}") \
  -w $(realpath "${PWD}") \
```

Because otherwise if PWD is returning `/home/user/workdir/project` where `workdir` is a symlink to something like `git/github.com/my-org`, the values resolve to the following:
```
  -v /home/user/git/github.com/my-org/project:/home/user/workdir/project \
  -w /home/user/git/github.com/my-org/project \
```
Which will use `/home/user/git/github.com/my-org/project` as the working directory when inside the image while `/home/user/workdir/project` was the actually mount bind point. The consequence is that the working directory will be created automatically and owned by the root user and this is then the path that is used to detect what uid to use.

**Comment by electrofelix** [comment]
My guess is the path you ran this under had a symlink which is why I couldn't reproduce when I originally tried to run and I left it until I had time to have a closer look at the docker image and how it is put together.
