### ISSUE TITLE
Unable to install plugin on Ubuntu 20.04

### ISSUE THREAD

**Issue by gpomykala** [vagrant-libvirt/vagrant-libvirt#1474]
**Describe the bug**
Unable to install plugin on Ubuntu 20.04

**To Reproduce**
1. vagrant plugin install vagrant-libvirt

**Versions (please complete the following information):**:
- Libvirt version: vagrant-libvirt/focal,focal,now 0.0.45-2 all [installed,automatic]
- Vagrant version [output of `vagrant version`]: 2.2.6
- Vagrant flavour [Upstream or Distro]: 
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8404840/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Comment by electrofelix** [comment]
The log doesn't contain any debug information, appears to only have stdout/stderr, which suggests an issue with vagrant first. Also you are reporting that you already have vagrant-libvirt 0.0.45-2 installed from the Ubuntu repositories which may well interfere.

You'll have to work out how to get the distro vagrant to generate debug output and attach the output from that to allow any further suggestions.

**Comment by electrofelix** [comment]
I've tested with an ubuntu-20.04 VM brought up using the following using the Vagrantfile at https://github.com/vagrant-libvirt/vagrant-libvirt-qa
```
VAGRANT_LIBVIRT_DEPLOY=false vagrant up ubuntu-20.04
vagrant ssh ubuntu-20.04
sudo sed -i "s/# deb-src/deb-src/" /etc/apt/sources.list
```
Not sure if that last step is required for a native ubuntu-20.04 installation.

Then following the README instructions from https://github.com/vagrant-libvirt/vagrant-libvirt#installation:
```
# following the vagrant install steps first
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install vagrant

# then the specific steps for vagrant-libvirt
sudo apt-get build-dep vagrant ruby-libvirt
sudo apt-get install qemu libvirt-daemon-system libvirt-clients ebtables dnsmasq-base libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev libguestfs-tools

# then the plugin install
vagrant plugin install vagrant-libvirt
```
results in the following output:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching formatador-1.1.0.gem
Fetching fog-core-2.3.0.gem
Fetching fog-json-1.2.0.gem
Fetching nokogiri-1.13.3-x86_64-linux.gem
Fetching fog-xml-0.1.4.gem
Fetching ruby-libvirt-0.8.0.gem
Building native extensions. This could take a while...
Fetching fog-libvirt-0.9.0.gem
Fetching vagrant-libvirt-0.7.0.gem
Installed the plugin 'vagrant-libvirt (0.7.0)'!
```

Since I cannot reproduce following the documented repo instructions, I must assume that something different occurred through a mixture of installing the distro packaged vagrant and plugin and attempting to subsequently install the latest version.

I recommend retrying following the known working instructions and if you have a specific need for the distro version of vagrant to limit to installing that from the distro repositories.
