### ISSUE TITLE
Order of interfaces with pci passthrough

### ISSUE THREAD

**Issue by hprem** [vagrant-libvirt/vagrant-libvirt#1475]
**Description**
With pci passthrough, the management interface comes after the passed-through interfaces. But I would like to make the management interface as the first interface (as I use cloud-init, which enables dhcp on first interface, by default)

**Issue**
On creating a VM with 2 passed-through NICs using the following vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |ubuntu|

    ubuntu.vm.box = "/space/disk/ubuntu.21.10.box"
    ubuntu.vm.hostname = "host"
    ubuntu.vm.provider :libvirt do |libvirt|
        libvirt.machine_type = "q35"
        libvirt.pci :domain => '0x0000', :bus => "0x31", :slot => "0x00", :function => "0x0"
        libvirt.pci :domain => '0x0000', :bus => "0x31", :slot => "0x00", :function => "0x1"

    end
  end
end
```

the management interface gets slot number "06", which is higher than that of the passed through nics ("03" and "04")

```
gnos@host:~$ lspci | grep -i eth
03:00.0 Ethernet controller: Intel Corporation Ethernet Controller E810-C for QSFP (rev 02)
04:00.0 Ethernet controller: Intel Corporation Ethernet Controller E810-C for QSFP (rev 02)
06:00.0 Ethernet controller: Red Hat, Inc. Virtio network device (rev 01)   <===<<< Management intf
```

But I am using cloud-init, which tries to enable dhcp on the first interface; so I would like to make the management interface to be the first interface

So I tried adding the following extra config, to specify the slot number I want the management interface to appear at

```ruby
        libvirt.management_network_domain = "0x0000"
        libvirt.management_network_pci_bus = "0x03"
        libvirt.management_network_pci_slot = "0x00"
```

But  this resulted in the below mentioned error
```
Error while attaching new device to domain. Call to virDomainAttachDeviceFlags failed: XML error: Attempted double use of PCI Address 0000:03:00.0
```

**Expected behavior**
The management interface should get the specified domain/slot/port and the passed-through interfaces should appear after it.

**Comment by electrofelix** [comment]
The error is coming from libvirt itself, so you will need to generate a debug log so I can see what XML was being sent to libvirt and I can then look at providing suggestions on how to adjust the parameters to get what you want.

**Comment by hprem** [comment]
Here is the full vagrant log file
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8413152/vagrant.log)

And here is the snippet from libvirt xml config, showing how the pci slots are assigned to various devives of interest
```xml
...
...
    <interface type='network'>
      <mac address='b0:03:e8:01:02:00'/>
      <source network='vagrant-libvirt'/>
      <model type='virtio'/>
      <alias name='ua-net-0'/>
      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
    </interface>
...
...
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0xb1' slot='0x00' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </hostdev>
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address domain='0x0000' bus='0xb1' slot='0x00' function='0x1'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </hostdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </memballoon>
```

**Comment by electrofelix** [comment]
I'm not seeing any debug output in the log file, it looks like it's just the normal output that was captured?

**Comment by hprem** [comment]
Sorry... The debugs got redirected to stderr it seems
Here is the proper set of debugs

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8413468/vagrant.log)

**Comment by electrofelix** [comment]
Ugh, so it's conflicting with the auto assigned PCI bus for the other devices that are generated by libvirt itself, before the network device is attached so it's not aware of any assigned to the network devices.

While I can't test this as I'm only on my phone at the moment, I'd guess that it would be best to try and use the slot value to control the order. It may be necessary to use `bus='0x06'` for all three network devices and then assign slot in the order you want them to appear and see if that works better. If it does, might want to experiment to see if you can skip setting the bus and just set the slot then, otherwise pick a bus explicitly high enough that even if you make other config changes, it's unlikely to get assigned to any other device by accident.

**Comment by hprem** [comment]
I would be happy to manually assign the bus/slot info for all the network devices (both for management and passed-through  interfaces).
But how do I specify the bus/slot info for passed-through devices? I dont see any hint in the documentation

**Comment by electrofelix** [comment]
I see we've done something rather stupid. For the `.pci` config option, `domain`, `bus`, `slot`, and `function` are for the source, while for the vagrant networks, they are the target definition.

Think it's not going to work until after adding options to support configuring the target devices the passthrough pci devices should appear as, since currently the values are automatically populated only.
