### ISSUE TITLE
Fedora 36 guest does not get static private network ip

### ISSUE THREAD

**Issue by tuupola** [vagrant-libvirt/vagrant-libvirt#1501]
**Describe the bug**

Fedora 36 guest does not get static private network ip. Problem does not exist with Fedora 35 nor CentOS 7 guests. Did not test with other guests. Not sure if this belongs here or Fedora bugtracker.

**To Reproduce**

Use the Vagrantfile from below and run `$ vagrant up`.

**Expected behavior**

Expect guest machine to get ip address `192.168.56.54`. 

**Screenshots**

Fedora 36 guest seems to get the correct network `192.168.56` it is the ip address which is wrong `192.168.56.232`.

```
$ cat /etc/redhat-release 
Fedora release 36 (Thirty Six)

$ ip addr
...
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:5f:9b:a7 brd ff:ff:ff:ff:ff:ff
    altname enp0s6
    altname ens6
    inet 192.168.56.232/24 brd 192.168.56.255 scope global dynamic noprefixroute eth1
       valid_lft 3511sec preferred_lft 3511sec
    inet6 fe80::aead:33fb:1ad:51ea/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

Fedora 35 guest gets both correct.

```
$ cat /etc/redhat-release 
Fedora release 35 (Thirty Five)

$ ip addr
...
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:27:d8:81 brd ff:ff:ff:ff:ff:ff
    altname enp0s6
    altname ens6
    inet 192.168.56.54/24 brd 192.168.56.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe27:d881/64 scope link 
       valid_lft forever preferred_lft forever
```

**Versions (please complete the following information):**:
- Libvirt version: 
`8.1.0-2.fc36`
- Vagrant version [output of `vagrant version`]: 
`Installed Version: 2.2.19`
- Vagrant flavour [Upstream or Distro]: 
Distro
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
vagrant-cachier (1.2.1, system)
vagrant-libvirt (0.7.0, system)
vagrant-sshfs (1.3.6, system)
```

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`

https://gist.github.com/tuupola/8dcbc3753b0c9c671c98e85585a26e74

Gist includes both non-working Fedora 36 and working Fedora 35 log plus their diff.

**A Vagrantfile to reproduce the issue:**

```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
    # libvirt.uri = 'qemu:///system'
  end

  # config.vm.box = "fedora/35-cloud-base"
  # config.vm.box_version = "35.20211026.0"
  config.vm.box = "fedora/36-cloud-base"
  config.vm.box_version = "36-20220504.1"
  # config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.56.54"
end
```

**Comment by tuupola** [comment]
Not sure if related:  https://docs.fedoraproject.org/en-US/fedora/latest/release-notes/sysadmin/Networking/

**Comment by electrofelix** [comment]
Typically there are 3 different possible sources of issues with networking in guests
- issues with guest box not having been cleaned correctly before packaging
- vagrant-libvirt failing to pass through some information on the network device correctly (MAC address, or connecting to wrong host network/routing by misconfiguring libvirt)
- vagrant not yet supporting a recent distro that changed how the networking is configured.

In this case, since vagrant-libvirt is guest distro agnostic, it's unlikely to be the source as it is working for fedora 35 guests and it would be passing the same information for configuring the private network to vagrant for fedora 36.

Vagrant-libvirt's job here is to make sure there is a virtual device attached to the VM for the network device and to attach it to the correct network on the host for routing between guests and/or out to the wider network along with capturing some information such as the Mac address for the device. It simply passes this information on to vagrant itself which will attempt to configure the network within the guest to use the ipaddress given or DHCP if enabled.

But as part of configuring a network on the host, vagrant-libvirt will create it to allow for DHCP clients unless explicitly told not to in case some machines are also added to the same network and you do not want to statically assign the IP address.

What I'm guessing is that the cloud box has a second network device definition that is left around, and by default this is enabled to use DHCP by default. And coupled with this vagrant is not able to configute fedora 36 guest networking correctly yet.

So when the VM boots it asks for a DHCP address and then vagrant fails to override this with a statically assigned one.

Can see this in the logs
```
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :always_destroy=>true, :ip=>"192.168.56.54", :protocol=>"tcp", :id=>"01ee1cce-8fd7-43d4-a059-b2c291eb441d"}
DEBUG create_networks: looking up network with ip == 192.168.56.0
DEBUG create_networks: generating name for network
DEBUG create_networks: looking up network named test0
DEBUG create_networks: generating name for network
DEBUG create_networks: looking up network named test1
DEBUG create_networks: generating name for bridge
DEBUG create_networks: looking up bridge named virbr0
DEBUG create_networks: looking up bridge named virbr1
DEBUG create_networks: looking up bridge named virbr2
DEBUG create_networks: looking up bridge named virbr3
DEBUG create_networks: looking up bridge named virbr4
DEBUG create_networks: found available bridge name virbr4
DEBUG create_networks: Creating private network with XML:
<network ipv6='yes'>
  <name>test1</name>
  <bridge name="virbr4" stp="on" delay="0" />


      <forward mode="nat" />

    <ip address="192.168.56.1" netmask="255.255.255.0">
      <dhcp>
        <range start="192.168.56.1" end="192.168.56.254" />
      </dhcp>
    </ip>


</network>

DEBUG create_networks: created network
```

You can set `:libvirt__dhcp_enabled` to `false` on the private network to confirm and a destroy and recreate should remove and recreate the network without DHCP enabled. I'd suspect though you'll end up without any IP address assigned to the second device in the guest.

If that does turn out to be the case, will want to log this issue with vagrant itself to have them add support for fedora 36 networking.
