### ISSUE TITLE
net-ssh version misread version 6.2.0.rc2 is actually between 2.6.5 and 7.0.0 but,  

### ISSUE THREAD

**Issue by snuffop** [vagrant-libvirt/vagrant-libvirt#1546]
*Describe the bug* Unable to Install the plugin due to a version
mismatch

*To Reproduce*
1. Go to shell
2. run vagrant plugin install vagrant-libvirt

Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5, < 7.0.0) and net-ssh (= 6.2.0.rc2)
  Activated net-ssh-6.2.0.rc2
  which does not match conflicting dependency (>= 2.6.5, < 7.0.0)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc2), 6.2.0.rc2 activated

  versus:
    net-scp (= 3.0.0), 3.0.0 activated, depends on
    net-ssh (>= 2.6.5, < 7.0.0)

  Gems matching net-ssh (>= 2.6.5, < 7.0.0):
    net-ssh-6.2.0.rc2

Arch Linux: latest Rolling
Vagrant: 2.3.0

**Comment by northy** [comment]
May be a problem in vagrant itself. Ran into the same problem, and managed to install `vagrant-libvirt` only by messing into the vagrant files (`/opt/vagrant/`) and forcing it to install `net-ssh = 6.1.0`.

**Comment by electrofelix** [comment]
@snuffop it is to do with vagrant as it uses bundler behind the scenes to manage the install of plugins. Looks like this is an occurrence of hashicorp/vagrant#12837. I've checked that using the pre-bundled vagrant 2.3.0 on vagrant doesn't have this issue. 

I suspect it's because something isn't handling the `rc2` suffix as suggested in the vagrant issue, so if you were to use `vagrant plugin install net-ssh --plugin-version 6.1.0` as suggested by the comment from @northy it might also resolve.

I will take a closer look at the issue on arch, but going to close this and any comments I have will be added to the upstream vagrant issue.

**Comment by snuffop** [comment]
the backout and install of older version  did the trick till the upstream is fixed  
```
pacman -U https://archive.archlinux.org/packages/v/vagrant/vagrant-2.2.19-2-x86_64.pkg.tar.zst
```
