### ISSUE TITLE
Error when updating domain settings: Error while creating domain: Libvirt failed to fully update the domain with the specified XML. Result differs from requested

### ISSUE THREAD

**Issue by rgl** [vagrant-libvirt/vagrant-libvirt#1556]
**Describe the bug**

After upgrading vagrant-libvirt 0.9.0 to 0.10.2 I no longer can start a ubuntu VM due to:

```
There was an error talking to Libvirt. The error message is shown
below:

Error while creating domain: Libvirt failed to fully update the domain with the specified XML. Result differs from requested:
--- requested
+++ result
     <apic/>
     <pae/>
   </features>
-  <cpu check="none" mode="host-passthrough">
-    
-    
-  </cpu>
+  <cpu check="none" mode="host-passthrough"/>
   <clock offset="utc"/>
   <on_poweroff>destroy</on_poweroff>
   <on_reboot>restart</on_reboot>

Typically this means there is a bug in the XML being sent, please log an issue
```

And in another box:

```
Error while creating domain: Libvirt failed to fully update the domain with the specified XML. Result differs from requested:
--- requested
+++ result
     <apic/>
     <pae/>
   </features>
-  <cpu check="none" mode="host-passthrough">
-    
-    
-  </cpu>
+  <cpu check="none" mode="host-passthrough"/>
   <clock offset="utc"/>
   <on_poweroff>destroy</on_poweroff>
   <on_reboot>restart</on_reboot>
       <target chassis="6" port="0x15"/>
       <address bus="0x00" domain="0x0000" function="0x5" slot="0x02" type="pci"/>
     </controller>
-    <controller index="0" type="virtio-serial">
-      <address bus="0x02" domain="0x0000" function="0x0" slot="0x00" type="pci"/>
-    </controller>
     <controller index="7" model="pcie-root-port" type="pci">
       <model name="pcie-root-port"/>
       <target chassis="7" port="0x16"/>
       <address bus="0x00" domain="0x0000" function="0x6" slot="0x02" type="pci"/>
     </controller>
+    <controller index="0" type="virtio-serial">
+      <address bus="0x02" domain="0x0000" function="0x0" slot="0x00" type="pci"/>
+    </controller>
     <interface type="network">
       <mac address="52:54:00:90:d7:7f"/>
       <source network="vagrant-libvirt"/>

Typically this means there is a bug in the XML being sent, please log an issue
```

**To Reproduce**
1. vagrant up

**Expected behavior**
I expect it to work.

**Versions (please complete the following information):**:
- Libvirt version: 6.0.0-0ubuntu8.16
- Vagrant version [output of `vagrant version`]: 2.3.0
- Vagrant flavour [Upstream or Distro]: Upstream.
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: Please see the attached log.

**Debug Log**
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/9414284/vagrant.log)

**A Vagrantfile to reproduce the issue:**

See https://github.com/rgl/ubuntu-vagrant/blob/master/example/Vagrantfile#L100-L118 and/or https://github.com/rgl/k0s-vagrant/blob/main/Vagrantfile.

Please note that these use [my own ubuntu box](https://github.com/rgl/ubuntu-vagrant), which has a base vagrant template in https://github.com/rgl/ubuntu-vagrant/blob/master/Vagrantfile.template

**Comment by electrofelix** [comment]
I forgot to add usage of https://github.com/postmodern/nokogiri-diff to ensure the comparison as the existing code is only good enough for helping avoid huge diffs but doesn't check if the contents are definitely identical

**Comment by electrofelix** [comment]
Or alternatively https://github.com/mbklein/equivalent-xml

Either need to be added at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/main/lib/vagrant-libvirt/action/start_domain.rb#L443-L451

**Comment by dcermak** [comment]
@electrofelix Is there any particular reason why you went with equivalent-xml instead of nokogiri-diff? equivalent-xml can be considered pretty much dead upstream, while nokogiri-diff has at least some activity. Would it be possible to switch? As the downstream package maintainer, I now have to include yet another ancient & unmaintained gem in openSUSE for vagrant-libvirt, which I would very much prefer to avoid.

**Comment by electrofelix** [comment]
@dcermak nokogiri-diff appears to return a list of diffs even when there wasn't any functional difference between two xml docs and it wasn't obvious how to exclude these. It seems to treat any whitespace and possibly element ordering differences as significant when they are not for libvirt, while equivalent-xml just worked.
I'm not attached to any particular library, just need something that can tell that the XML returned by libvirt as to what was applied is equivalent to what was requested.

It came as a surprise that libvirt doesn't provide any way to confirm that instead it's up to the application.
https://listman.redhat.com/archives/libvirt-users/2022-May/013563.html is where this started to be uncovered for me, and https://listman.redhat.com/archives/libvirt-users/2022-May/013575.html was the point at which it was revealed that it was expected to be checked by the application side.

Presumably the possible options are:
- equivalent-xml - https://github.com/mbklein/equivalent-xml: current
- nokogiri-diff - https://github.com/postmodern/nokogiri-diff/: unclear if it will work in the needed manner (elements placed in a different order likely treated as diffs as well)
- compare-xml - https://github.com/vkononov/compare-xml: not tried
- xml-simple - https://github.com/maik/xml-simple: it allows comparison using '==' due to use of ruby data structures for comparison

While the last release of equivalent-xml is from 2015, it was more recent than the last release of nokogiri-diff which was 2012. That combined with the number downloads compared to nokogiri and compare-xml, and that it worked out of the box is why it got used.

However I see xml-simple is very popular, so if that works for you and it's not too difficult to adopt, I'm happy to switch.

**Comment by dcermak** [comment]
I have given this a stab in #1565 with compare-xml. I tried xml-simple briefly, but it wouldn't work easily, as it considers whitespace in elements contents and breaks the comparison.
