### ISSUE TITLE
CPU vendor specified without CPU model

### ISSUE THREAD

**Issue by Nesaijn** [vagrant-libvirt/vagrant-libvirt#1673]
**Describe the bug**
When starting my vagrant machine I get the following output with an error message in it:

```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'generic/ubuntu2204' version '4.1.18' is up to date...
==> default: Starting domain.
==> default: Error when updating domain settings: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
==> default: Waiting for domain to get an IP address...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.122.8:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Host unreachable. Retrying...
    default: Warning: Host unreachable. Retrying...
==> default: Machine booted and ready!
==> default: Creating shared folders metadata...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

It did not appear the first time I created the machine. It started happening only after I stopped the machine with `vagrant halt`, I think after reboot and then bringing it up again with `vagrant up`.
This also happens to me with another system in which I am running the same OS namely Fedora 36.

I should also mention that the error message does not hinder me from using the vagrant machine. As of now I have not seen any other issues other that the error message popping up. Everything else works fine.

This error message also seemed to be an issue here #877 

**To Reproduce**
1. Successfully create a new vagrant machine with `vagrant up`
2. Stop the vagrant machine with `vagrant halt`
3. Reboot (?)
4. Start the vagrant machine again with `vagrant up`
5. See error message (hopefully)

**Expected behavior**
I expect the error message to not appear when starting the vm.

**Versions:**:
- Libvirt version: 8.1.0
- Vagrant version [output of `vagrant version`]: Vagrant 2.2.19
- Vagrant flavour [Upstream or Distro]: Distro
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.7.0, system)

```
$ rpm -qa | grep vagrant
vagrant-2.2.19-4.fc36.noarch
vagrant-libvirt-0.7.0-2.fc36.noarch
```

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/9996057/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "generic/ubuntu2204"
end
```

I also did a `virsh dumpxml` before running the `VAGRANT_LOG=debug vagrant up` and getting the error message, like mentioned in the issue I linked above:
[dumpxml.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/9996059/dumpxml.log)

**Comment by Nesaijn** [comment]
Seems to have been solved according to #996 
Will open up again if it is not the case

**Comment by electrofelix** [comment]
@Nesaijn if you'd like to confirm that it's gone with the most recent releases, you can follow the quick start install instructions for vagrant-libvirt at https://vagrant-libvirt.github.io/vagrant-libvirt/ to install the most recent release instead of the distro packaged one. The only thing is you'll need to set the option `qemu_use_session` as described at https://vagrant-libvirt.github.io/vagrant-libvirt/examples.html#qemu-session-support since fedora patch the plugin to enable this by default.

**Comment by Nesaijn** [comment]
@electrofelix When I get to it I will try it and report back. But the latest release of 10.8 is not the one with the mentioned fix, right?
Thank you for the comment!

**Comment by electrofelix** [comment]
That's possible, when I tested it seemed like the issues that you linked to was fixed in 0.10.8, however the CPU setting code has been updated as well since so the issue you encountered may only have been fixed by the latest code.

It should be possible to install using the following
```
vagrant plugin install vagrant-libvirt --plugin-version "0.10.9.pre.56" --plugin-source "https://rubygems.pkg.github.com/vagrant-libvirt" --plugin-prerelease
```

I haven't had a chance to test this though I do intend to check what is needed to install the latest gen published to the GitHub packages of this repo as I've been working on making it easier to pick up and try the very latest code as well as specific PRs. But it should be close enough I'm just not in front of a computer to check it properly at the moment.

**Comment by doudou** [comment]
I just had the same issue with vagrant-libvirt 0.18.8 and libvirt 6.0.0. In my case, it was after a halt, and the plugin would stop and not let me continue after the error.

The install from github's package repository would not work (I get a 401 Unauthorized on the gem index)

I built the gem from the git repo (master) and the error still happens.

~~~
==> default: Updating domain definition due to configuration change
==> default: Error when updating domain settings: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
Error while creating domain: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
d
~~~

In the debug output, I get

~~~
DEBUG start_domain: cpu_mode updated from 'custom' to 'host-model'
DEBUG start_domain: cpu_model text updated from Icelake-Server to ''
DEBUG start_domain: cpu_model fallback attribute updated from forbid to 'allow'
DEBUG start_domain: nested mode disabled for cpu by removing vmx feature
~~~

Note that I have not specified any model. The Vagrantfile only specifies the number of CPUs and memory. I'm having a similar issue with an ARM machine (on a x86 host), but I don't have the specific error message in that case.

**Comment by electrofelix** [comment]
Thanks, that debug helps and confirms that libvirt has changed behaviour here. I'll have another look as I think that output should help me come up with a straight forward fix

**Comment by electrofelix** [comment]
Turns out that github doesn't allow anonymous downloads and vagrant doesn't provide a way to use a `~/.gemrc` to provide credentials for a private rubygems package repo.

Though at least it can be downloaded directly from https://github.com/vagrant-libvirt/vagrant-libvirt/packages/1659776 and installed as a local gem.

I think, what the problem might be is failure to correct update the XML to defaults (which would involve removing the `<vendor>` and `features` elements) after they have previously been configured on the domain.

So the bug appears to be mainly an issue with older libvirt releases, combined with not being cleaning up properly when reverting to default values.

The default values for config settings referenced would be:
* `cpu_mode`: `host-model`
* `cpu_model`: `''`
* `cpu_fallback`: `'allow'`

Changing to these values would match with not having any such config values set. However it's unclear where the previous values of `custom`, `Icelake-Server` and `forbid` would have come from, unless they were previously set and then removed?

@doudou would you be able to provide me with a `virsh dumpxml <domain>` from when your VM is halted and also attach a full debug log (should contain the XML being sent).

**Comment by doudou** [comment]
OK, so ... Doing `up --no-provision`, `halt` and then `up` again just worked with 0.10.8... Go figure.

I'll update if I manage to trigger the bug again. But maybe I did a test with a machine that had been created with a version of vagrant-libvirt and then did an `up` on it ?

**Comment by electrofelix** [comment]
I think if you bring the machine up with the cpu-mode set to 'custom', halt it and then bring it up with the setting removed, it will trigger this, though I've yet to confirm

**Comment by electrofelix** [comment]
I've done some experimenting and I think that it's likely I'll need to add a request to retrieve the domcapabilities and determine the correct default for fallback based on that. It appears sometimes what is sent to libvirt gets converted to different output so a `host-model` can result in `custom` instead of `host-model`. Possibly retrieving the details from the domcapabilities to look at what host-model settings should resolve to, will allow skipping changing them if they correspond to the expected results.

**Comment by Jeansen** [comment]
Oh..funny. I just found out, that `virsh dumpxml` spits out different XML if the vm is running or shut down. But there is a --inactive flag which will generate almost the same XML generated by vagrant-libvirt. Anyway, I think this error should not happen no matter the XML origin ...
