### ISSUE TITLE
Allow setting nic name for management network like you can for public/private networks.

### ISSUE THREAD

**Issue by ykuksenko** [vagrant-libvirt/vagrant-libvirt#1701]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to set the nic name for management interfaces on vm with the same parameter (`:libvirt__iface_name`) that is used for public and private networks.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ofuro** [comment]
It's already available, they forgot to put it in the documentation:

https://vagrant-libvirt.github.io/vagrant-libvirt/version/0.11.2/examples.html#:~:text=libvirt.management_network_device%20%3D%20%27virbr0%27

`xxx.management_network_device = ""`

**Comment by electrofelix** [comment]
Good spot, I completely missed that was the correct option, probably because it's also named differently to the option for private/public NICs. I might look to rename with backwards compatible handling to be consistent across the different interfaces.

**Comment by ykuksenko** [comment]
I tried using `xxx.management_network_device = ""`. It does not seem to work for me. Though the way it is documented made me think that would would set the network bridge name not the vm management interface name. 

I tried setting the management bridge name also but could not find a variable that worked for that either. It is possible I just did it wrong.

**Comment by electrofelix** [comment]
@ykuksenko I was thinking that setting of the device name to be used to for the interface of the domain wasnt in place when I linked the other issue to this one. Didn't look closely enough at the option the above comment suggested as just assumed they had spotted something I missed. I'll try to get around to looking closely and explaining the options, but can be reasonably sure that there is not an option to control the device name created on the host to correspond to the interface that is attached to the domain for the management network. This was recently extended for public networks to help with supporting vlan tagging on the host for interfaces associated with a collection of VMs. So I'm presuming something similar is needed here

**Comment by ofuro** [comment]
> I tried using `xxx.management_network_device = ""`. It does not seem to work for me. Though the way it is documented made me think that would would set the management network bridge name not the vm management interface name.
> 
> I tried setting the management bridge name with that variable and it did not work. It seems to me that the bridge device name for the management network is hard coded to `virbr0`.

For some reason, yes it default to `virbr0` even when using `xxx.management_network_device = ""` .
For now, the only way to use a different bridge would be to set it manually in virsh:
```
<network ipv6='no'>
  <name>vagrant-mgmt</name>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='br0' stp='on' delay='0'/>
  <mac address='xx:xx:xx:xx:xx:xx'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.2' end='192.168.121.254'/>
    </dhcp>
  </ip>
</network>

```

Alongside those options:
`xxx.management_network_name = 'vagrant-mgmt'`
`xxx.management_network_keep = true` 

That way, it would match the network name `vagrant-mgmt`.
If your conf is correct, vagrant will try to start the network XML defined  instead of creating one.

The domain XML part is auto-generated based on what was set in the network XML.
Therefore, the domain will use `vagrant-mgmt` as source and a TAP adapter will be created `vnet0`, and referenced in the domain XML for use.


And, if you want to use a different TAP adapter, then yes we need a new setting to be addedd in vagrant-libvirt.
