### ISSUE TITLE
Throws error with brew installed libvirt on M1 Mac.

### ISSUE THREAD

**Issue by l-monninger** [vagrant-libvirt/vagrant-libvirt#1713]
**Describe the bug**
`vagrant plugin install vagrant-libvirt` throws error with brew installed libvirt on M1 Mac.

**To Reproduce**
1. `brew install libvirt`
2. `brew services start libvirt`
3. `vagrant plugin install vagrant-libvirt`

**Expected behavior**
Plugins picks up on libvirtd being installed and is able to proceed with configuration.

**Screenshots**

**Versions (please complete the following information):**:
- Libvirt version: 9.0.0
- Vagrant version [output of `vagrant version`]: 2.3.4
- Vagrant flavour [Upstream or Distro]:  Distro
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/l-monninger/.vagrant.d/gems/2.7.6/gems/ruby-libvirt-0.8.0/ext/libvirt
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.7.0 -r ./siteconf20230123-52221-uu353u.rb extconf.rb
Looking for libvirt using pkg-config
checking for virConnectOpen() in -lvirt... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
        --with-virt-dir
        --without-virt-dir
        --with-virt-include
        --without-virt-include=${virt-dir}/include
        --with-virt-lib
        --without-virt-lib=${virt-dir}/lib
        --with-virtlib
        --without-virtlib
extconf.rb:44:in `<main>': No working libvirt installation found (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/l-monninger/.vagrant.d/gems/2.7.6/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/l-monninger/.vagrant.d/gems/2.7.6/gems/ruby-libvirt-0.8.0 for inspection.
Results logged to /Users/l-monninger/.vagrant.d/gems/2.7.6/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/gem_make.out
```

**A Vagrantfile to reproduce the issue:**
This happens on install.

**Comment by l-monninger** [comment]
Seems like this may be similar to https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1269

**Comment by jmara** [comment]
We experience the same problem getting this plugin running on M1/2 Macbooks. Any recommendation / additional info we could supply?

**Comment by electrofelix** [comment]
The underlying problem is that vagrant for Mac is distributed as an x86_64 binary, while m1/m2 arch is arm64. This means that libvirt is installed as an arm64 lib, while the embedded ruby environment bundled into vagrant from which plugins must work is x86_64. For pure ruby plugins, this isn't an issue, but for vagrant-libvirt which uses fog-libvirt and in turn uses ruby-libvirt, it is. The ruby-libvirt gem is a native extension which needs to be linked against libvirt and the ruby it will be used from, and since these end up as 2 different architectures, the extension building cannot locate a libvirt library that is compatible to link against.

One option is to wait for vagrant to release with new plugin architecture where the vagrant binary is golang and it uses gRPC to talk to plugins that can be in any language or architecture. This would mean the install of vagrant-libvirt would have to combine ruby + it's dependencies itself, however it could then use the same arch as libvirt on the machine.

The alternatives involve changing all the backend calls in vagrant-libvirt to remove the dependency on fog-libvirt/ruby-libvirt by either wrapping virsh or using xml-rpc to talk to the libvirt daemon directly.

My suspicion is that trying to wrap virsh wouldn't be sufficient to as some details are not exposed (I can't recall off hand which, just that there was difficultly extracting some information in certain cases that appears not yet to be exposed via the CLI).

Switching to xml-rpc would likely involve moving code that calls fog-libvirt and/or ruby-libvirt into a separate driver class that can subsequently replaced with one using xml-rpc to talk directly to the libvirt server without needing anything to be compiled or linked against it similar to https://github.com/digitalocean/go-libvirt.

While some time ago I started trying to abstract some bits into a driver module, there is a lot more that would need to be done.

In the mean time you could look to install ruby via homebrew and make use of bundle to install both this gem and vagrant directly in the same way the tests are executed. See https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1671#issuecomment-1312457093

Even with this workaround you'll likely find the networking to be an issue as libvirt on Mac may still not yet support creating the networks needed to ssh in the VM. It's possible that a combination of port forwarding using qemu forwarding described in https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1017#issuecomment-740164115 and https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1337#issuecomment-974833765 and some mac specific tweaks to have the ruby bundle install approach work out of the box might be the best first step. Unfortunately I've not been able to get the hostfwd approach to work on linux machines so there might be some limitations there.

I have also read about a project implementing their own interpreter to work with qemu agent and therefore provide a way to imitate entering the VM and providing a console. This also sounds potentially complex, however a QemuAgentCommunicator for provisioning steps to remove the need for an initial network to exist might make it easier to modify things inside the guest if SSH access is not needed otherwise.

Existing issues: #1671, #1337, #1017, and #497 show that this is a long standing issue, so obviously anything that can help move it forward would be well received.

**Comment by electrofelix** [comment]
Going to close this in favour of tracking all the issues with installing on arm64 for MacOS under #1205, a comment on that issue suggests a possible workaround for now https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1205#issuecomment-1542775740 and there is another issue #1703 covers using vmnet to create networks, which should be possible to be reference now due to the addition of the `management_network_iface_name` option (provided you don't use `vnetX` as the device naming).
