### ISSUE TITLE
Vagrant suspend does not free RAM

### ISSUE THREAD

**Issue by sswastik02** [vagrant-libvirt/vagrant-libvirt#1795]
**Describe the bug**
Despite being mentioned in the [docs](https://developer.hashicorp.com/vagrant/docs/v2.3.7/cli/suspend), `vagrant suspend` stops processes but does not free up RAM

**To Reproduce**
1. Use the below `Vagrantfile` to provision a VM
2. Run `vagrant suspend` while watching the RAM consumption of your system
3. Resume the VM using `vagrant resume` then run `vagrant halt` to see the difference.

**Expected behavior**
The CPU load reduces and also the RAM frees up

**Versions (please complete the following information):**:
- Libvirt version: 8.0.0
- Vagrant version [output of `vagrant version`]:2.3.7
- Vagrant flavour [Upstream or Distro]: Ubuntu 22.04.2 LTS
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
```
vagrant-libvirt (0.12.2, global)
vagrant-share (2.0.0, global)
```
**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`

[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/13800836/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<-SCRIPT
echo "Changing Password"
echo -e 'password\npassword' | sudo passwd vagrant
apt update -y
apt install -y stress
stress --cpu 1 --vm 4&
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "generic/ubuntu2204"



  # Specifying private network to make it accessible through host computer
  config.vm.network "public_network", :dev=>"enp1s0", use_dhcp_assigned_default_route: true, dhcp: true

  # Provisioning Server using provider
  config.vm.provider :libvirt do |vm|
    vm.memory=1024
    vm.cpus=1
    vm.graphics_type="none"
  end

  config.vm.provision "shell",
    inline: $script

end

```

**Comment by electrofelix** [comment]
It looks like an option to change the suspend behaviour was introduced about 8 years ago with https://github.com/vagrant-libvirt/vagrant-libvirt/pull/470. While the issue https://github.com/vagrant-libvirt/vagrant-libvirt/issues/411 refers to the vagrant documentation as having this behaviour when I look back at the old documentation https://github.com/hashicorp/vagrant/blob/v1.8.0/website/docs/source/v2/cli/suspend.html.md that is from around that time, it suggests that the RAM should be freed as well which means managed save should be the default instead of pause. Looking at libvirt releases managed save was available since 2010.

At this point to solve your problem, just set the `suspend_mode` to the `managedsave`, for this to become the default would require a warning to be emitted about the current default warning end-users and then switch in a year or two.

**Comment by sswastik02** [comment]
Ok, whatever is mentioned in the docs is not the default.
Can you please elaborate on the modifying `suspend_mode`, do you mean in the above `Vagrantfile` with `config.vm.suspend_ mode`?

**Comment by electrofelix** [comment]
It's a provider based option, so modifying the block you have in the config above to look like the following should be enough:
```
  config.vm.provider :libvirt do |vm|
    vm.memory=1024
    vm.cpus=1
    vm.graphics_type="none"
    vm.suspend_mode="managedsave"
  end
```

**Comment by sswastik02** [comment]
Thank you so much, that seemed to work.
However, the documentation should be changed to reflect these options I feel.

**Comment by sswastik02** [comment]
Closing this issue, including the option `managedsave` as mentioned here in this [comment](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1795#issuecomment-1873237980) makes sure RAM is also freed. This takes more time than the default `pause`
