### ISSUE TITLE
Should always use ssh proxy when connecting to remote libvirt

### ISSUE THREAD

**Issue by sciurus** [vagrant-libvirt/vagrant-libvirt#221]
You can connect to libvirt on a remote host without tunneling over ssh. If you don't set _connect_via_ssh_ to tunnel the libvirt connection over ssh, we don't use the remote host as an ssh proxy when connecting to the VMs. This means the connection, which needs to go over the management network that is private to the remote host, will always fail.

**Comment by infernix** [comment]
I could not reproduce this with 0.0.33 other than by specifying an uri and editing that hosts libvirtd.conf to allow tcp, e.g. `uri = 'qemu+tcp://server/system'`

With this vagrantfile:
```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "alxgrh/debian-jessie-x86_64"

  config.vm.provider :libvirt do |libvirt|
    libvirt.host= "server"
    libvirt.connect_via_ssh = false
    libvirt.username = "root"
    libvirt.password = "*****"
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.nested = true
    libvirt.volume_cache = 'none'
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
```

I'm just getting complaints that my certificates don't match and so I can't seem to reproduce it that way. Could be due to my libvirt version.

In any case, I think the point here is that it is indeed impossible with the current version to connect to any remote libvirt host while keeping basic vagrant functionality working. The primary reason today is twofold:

- We're using `ip_command = %q[ awk "/$mac/ {print \$1}" /proc/net/arp ]` on the host where vagrant is executed to get the IP for the booted VM; this will fail whenever this command isn't executed on the host where the VM is running
- Even if we run the `ip_command` on the host where the VM is running, if the host where vagrant is being executed cannot connect to the assigned management IP, ssh commands to the VM will indeed fail.

What's needed is to map out the various ways of how we support connecting to remote libvirt instances and what the caveats are. Once that's clear, we can make valid assumptions on what flags we should enable by default.

**Comment by electrofelix** [comment]
Config support for setting and extracting information from `@uri` has gone through an overhaul in the recent release along with fixes for proxy command.

The setting `@connect_via_ssh` will be enabled automatically if the remote connection uri contains `ssh` in the transport specification.

For connections such as `qemu+tcp://...` probably should not automatically enable ssh because this url is passed to libvirt telling it to connect directly to a specific host over tcp. Given that the management network IP address are now retrieved via libvirt's API, any the updates to the config now allow for a custom `@proxy_command` to connect to the remote system, I think this is as resolved as it can be, and best wait until there are clear requirements identifying edge cases that we should cover.
