### ISSUE TITLE
Port mapping: collision not handled

### ISSUE THREAD

**Issue by flavio** [vagrant-libvirt/vagrant-libvirt#321]
It looks like port collisions are not detected by vagrant-libvirt.

How to reproduce the bug:
- Start box1, map port 8080 of the box to port 8080 of the host
- Start box2, map port 8080 of the box to port 8080 of the host
- Access port 8080 on the host system

Outcome: the service running on box1 is being accessed.

Expected outcome: vagrant notices the port collision, notifies the user and if `auto_correct` is enabled uses a different port on the host for the service running inside of box2.

**Comment by bexelbie** [comment]
I am not providing a patch at this time, but a bit more information.  The root cause appears to be that the port maps are implemented using the -L option to an ssh to create a tunnel.  The ssh commands succeeds no matter what, so vagrant-libvirt isn't seeing an error.  We need to check the ssh output for the line (something like) `bind: Address in use` and trap on that.

**Comment by muelli** [comment]
hm. that sounds awful. Also bad, but maybe programmatically easier is to either bind() on the port yourself and see whether that works or to connect() to the port to see whether there is anything listening on it.

**Comment by lwh** [comment]
You can make it fail if you use the ssh option ExitOnForwardFailure=yes
