### ISSUE TITLE
default synced folder implementation is non-deterministic

### ISSUE THREAD

**Issue by danwinship** [vagrant-libvirt/vagrant-libvirt#419]
README.md says "vagrant-libvirt supports bidirectional synced folders via nfs or 9p and unidirectional via rsync. The default is nfs.". But this doesn't actually seem to be true; 'nfs' and 'rsync' have the same priority in vagrant, and it seems to be non-deterministic which of the two gets picked. (On my machine, 'rsync' is the default for vagrant-libvirt boxes, unless overridden by the Vagrantfile.)

I'm not sure if this is fixable from the vagrant-libvirt end (though if not, the docs should be fixed at least). The just-merged https://github.com/mitchellh/vagrant/pull/5013 might help?

**Comment by leehambley** [comment]
+1

**Comment by infernix** [comment]
I think the docs should be updated since I've only ever seen it default to rsync, not nfs. The doc author probably specifically referred to the bidirectional protocols only, since rsync is one-way. Commit was 752a8df2ba3c86096315f5bdfdf920b789255b9d

But there's more: https://github.com/pradels/vagrant-libvirt/pull/170 states that both rsync and nfs have prio 5:
```
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/rsync/plugin.rb:      synced_folder("rsync", 5) do
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/nfs/plugin.rb:      synced_folder("nfs", 5) do
```

So the default then should depend on host capability tests and/or plugin inclusion order, as per https://github.com/pradels/vagrant-libvirt/pull/170#issuecomment-42108392

We clearly cannot change the priority in vagrant so i am just guessing that rsync is loaded before nfs and that's why it's the default.

**Comment by lelutin** [comment]
Hi there, vagrant has been defaulting to an nfs share for the `/vagrant` mount for a while now for me. Is there still some non-determinism happening or was it fixed somehow between 2016 and now?

**Comment by danwinship** [comment]
I don't use vagrant any more so I don't know

**Comment by electrofelix** [comment]
Most likely the order files are read in ruby changed to be more deterministic which meant that the nfs plugin was being loaded before rsync.

However whether it'll use nfs will depend on the host having the required packages for the host to have nfs installed, so if you don't have them installed, it'll skip over trying to use them. Similarly if you don't have rsync installed it'll skip trying to use them, which means that the order is dependent on what packages are currently installed on the host.

Seems like the best recommendation is to be explicit and or use the config option `config.vm.allowed_synced_folder_types` to control the order explicitly.

Plan on closing this by documentation.
