### ISSUE TITLE
Installing plugin on latest vagrant fails due to gem version constraint

### ISSUE THREAD

**Issue by xsrb** [vagrant-libvirt/vagrant-libvirt#448]
Just in case this issue isn't known about:
Happened on a fresh install of Fedora 22
vagrant: 1.7.4
```bash
 vagrant plugin install libvirt

The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "nokogiri":
  In Gemfile:
    vagrant (= 1.7.4) ruby depends on
      nokogiri (= 1.6.3.1) ruby

    libvirt (>= 0) ruby depends on
      nokogiri (~> 1.4.3) ruby
```

**Comment by ichilton** [comment]
Same problem here on a clean Arch install:

```
$ vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4
 
You're running an up-to-date version of Vagrant!
```

```
$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "nokogiri":
  In Gemfile:
    vagrant (= 1.7.4) ruby depends on
      nokogiri (= 1.6.3.1) ruby

    libvirt (>= 0) ruby depends on
      nokogiri (~> 1.4.3) ruby
```

Is there a workaround?

I wonder if vagrant-libvirt will work with 1.6.3.1 if the dependancy was raised to match the vagrant one.

Ian

**Comment by ssbilkhu** [comment]
I'm experiencing the same error as above when doing:

<pre> vagrant plugin install libvirt </pre>

when I use the command from the documetation

<pre>
[root@MASKEDHOST]# vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" 
compiling generator.c
make: gcc: Command not found
make: *** [generator.o] Error 127

Gem files will remain installed in /root/.vagrant.d/gems/gems/json-1.8.3 for inspection.
Results logged to /root/.vagrant.d/gems/gems/json-1.8.3/ext/json/ext/generator/gem_make.out
</pre>

I get that error

**Comment by mkutsevol** [comment]
@ssbilkhu , hi!
try to install at least gcc
**make: gcc: Command not found**
or better something like build-essential package (it's an ubuntu package)

**Comment by ssbilkhu** [comment]
@mkutsevol , hello!

I'm on a machine using Centos 7 as the host OS.  Also I should of mentioned that I'm using vagrant verison 1.7.4

**Comment by ichilton** [comment]
This is a different problem - please open a new issue to avoid distraction from the issue in hand.

**Comment by jschwartzenberg** [comment]
I've got the same issue on CentOS 7.

**Comment by savermyas** [comment]
The same issue on Ubuntu 14.04 server

**Comment by jakub-olczyk** [comment]
Similar issue on Debian Sid. The output:
```
$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "ffi":
  In Gemfile:
    vagrant (= 1.7.4) ruby depends on
      listen (>= 0) ruby depends on
        rb-inotify (>= 0.9) ruby depends on
          ffi (>= 0.5.0) ruby

    vagrant (= 1.7.4) ruby depends on
      childprocess (>= 0) ruby depends on
        ffi (>= 1.0.11, ~> 1.0) ruby

    libvirt (>= 0) ruby depends on
      ffi (~> 0.6.3) ruby
```

**Comment by electrofelix** [comment]
The correct name for the plugin is vagrant-libvirt, suggest that you try:
`vagrant plugin install vagrant-libvirt`

You're attempting to install the `libvirt` gem which is https://rubygems.org/gems/libvirt, which is not the same as this plugin -> https://rubygems.org/gems/vagrant-libvirt.

**Comment by ichilton** [comment]
That is true, well spotted!

**Comment by jalevin** [comment]
A side note- if you miss-type "vagrant-libvirt" for something like "vagrant-libvrt" it will also throw the gem error. Watch for typos :)

**Comment by blues-man** [comment]
This issue should be closed or rejected since the name of the plugin was incorrectly used, the [README](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/README.md) also shows **vagrant-libvirt**

**Comment by jakethesnake2x** [comment]
Same issue using windows however it is vagrant that says it can't run because it is missing nokogiri.
