### ISSUE TITLE
Use libvirt DHCP leases API

### ISSUE THREAD

**Issue by danielshahaf** [vagrant-libvirt/vagrant-libvirt#451]
Hello,

README.md says:

> You may wonder how vagrant-libvirt knows the IP address a VM received.
> Libvirt doesn't provide a standard way to find out the IP address of a running
> domain. But we do know the MAC address of the virtual machine's interface on
> the management network. Libvirt is closely connected with dnsmasq, which acts as
> a DHCP server. dnsmasq writes lease information in the `/var/lib/libvirt/dnsmasq`
> directory. Vagrant-libvirt looks for the MAC address in this file and extracts
> the corresponding IP address.

However, there does exist a libvirt API for finding the IP address of a running domain:

```
% hostname
alice.localdomain
% virsh -c qemu+tcp://bob.localdomain/system net-dhcp-leases default --mac=52:54:00:2e:f1:bb 
 Expiry Time          MAC address        Protocol  IP address                Hostname        Client ID or DUID
-------------------------------------------------------------------------------------------------------------------
 2015-09-01 09:49:44  52:54:00:2e:f1:bb  ipv4      192.168.122.23/24         archer          ff:00:2e:…
```

vagrant-libvirt should use that API instead of parsing `/var/lib/libvirt/dnsmasq`, for two reasons:
- to avoid depending on libvirt implementation details (such as its use of dnsmasq)
- to support the case that vagrant-libvirt and libvirtd run on different hosts (as in the example)

Or, if that is already the case, then README should be updated to reflect that :).

**Comment by pronix** [comment]
I will wait your PR with implementation.

**Comment by danielshahaf** [comment]
The current implementation is this:

```
lib/vagrant-libvirt/driver.rb:37:        ip_command = %q[ awk "/$mac/ {print \$1}" /proc/net/arp ]
```

Replacing this by a `virsh net-dhcp-leases` call is easy, but what network name should I pass? Shall I hardcode the network name "default'?

**Comment by pronix** [comment]
use libvirt methods please.
or fog or something else, but not virsh

**Comment by danielshahaf** [comment]
Alright, can I hardcode the network name "default"? If not, how do I get the network name? Couldn't find it in the docs.

**Comment by danielshahaf** [comment]
The ruby-libvirt bindings [expose the `dhcp_leases` method in master](http://libvirt.org/git/?p=ruby-libvirt.git;a=blob;f=ext/libvirt/network.c;h=7c77d730bc9d1c5b4d044873a049ed1f78560b34;hb=HEAD#l287). That support isn't yet released. I presume it will be released in ruby-libvirt 0.5.3.

**Comment by nehaljwani** [comment]
ruby-libvirt 0.6.0 has already been released: http://libvirt.org/ruby/news.html

**Comment by EmmanuelKasper** [comment]
The current /proc/net/arp handling seems to be broken when the dhcp client running inside the domain uses systemd-networkd ( no arp entries are created, see debian bug report  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838637 ) 
Getting the IP adress via fog and libvirt would fix this issue.  It seems fog added the necessary code in 
https://github.com/fog/fog-libvirt/pull/11.

**Comment by infernix** [comment]
This should be possible to implement now with the updated ruby-libvirt/fog-libvirt versions.

**Comment by booxter** [comment]
One other reason to switch to libvirt API is that after hypervisor reboot, the leases file for libvirt is empty, and so if you then resume the machine, you can then ping it, but vagrant ssh fails with:

...
 INFO warden: Calling IN action: #<Proc:0x005621faa62490@/usr/share/vagrant/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SSHExec:0x005621faa007e0>
 INFO driver: Timeout at waiting for an ip address for machine default
 INFO driver: No arp table entry found for machine default
ERROR warden: Error occurred: The provider for this Vagrant-managed machine is reporting that it

That's because the dnsmasq file doesn't contain the lease. To make it work, I then need to go into the machine via console or other means, and systemctl restart network, at which point the in-machine DHCP client requests a lease again, and dnsmasq registers it in its file.

If we would use libvirt API, we would not have this problem, because it always knows about MAC to address mapping.

**Comment by nehaljwani** [comment]
> If we would use libvirt API, we would not have this problem, because it always knows about MAC to address mapping.

That's not entirely true. When a lease expires, dnsmasq sends a 'DEL' event to the leaseshelper program used by libvirt, which helps in maintaining the leases database. When the 'DEL' event is received, the helper program removes the entry from it's database. Before libvirt v2.4.0, libvirt used to automatically remove the leases which had expired while reporting them regardless of whether there was a 'DEL' event or not. This was fixed by the patch https://github.com/libvirt/libvirt/commit/1dcbb27402be9ce1e21979cf74ae5c577aca5f90

Also, the libvirt DHCPLeases API, as of today, maintains a database of leases only for libvirt-managed networks.

**Comment by booxter** [comment]
The use case that I talk about doesn't involve lease expiration (the lease is valid, it's just that dnsmasq is not aware of it because it hasn't persisted the status file between reboots).

**Comment by dthpulse** [comment]
Getting same issue. Any update on this?
