### ISSUE TITLE
Multiple interfaces and routes

### ISSUE THREAD

**Issue by moozer** [vagrant-libvirt/vagrant-libvirt#473]
I am trying to set up a linux box using vagrant and libvirt. This has become routine and the libvirt plugins work well for me.

Currently I am setting up a linux box with two interfaces.
* eth0: vagrant-libvirt management lan
* eth1: LAN_A

I want to have the DHCP on eth1 to set the default route, not eth0
Can I somehow specify it in my Vagrantfile?

Perhaps it is related to #451 ?

-- 

From Vagrantfile
```
  config.vm.define "serverA" do |serverA|
    serverA.vm.box = "deb8-base"
    serverA.vm.synced_folder "shared", "/vagrant", type: "9p"
    serverA.vm.hostname = "serverA"

    # not setting IP address
    # specifying that DHCP trumps mgnt as gateway
    serverA.vm.network :private_network, 
      :libvirt__network_name => "LAN_A",
      :libvirt__forward_mode => "none"
  end
```

From /etc/network/interfaces
```
  # The primary network interface
  allow-hotplug eth0
  iface eth0 inet dhcp
  #VAGRANT-BEGIN
  # The contents below are automatically generated by Vagrant. Do not modify.
  auto eth1
  iface eth1 inet dhcp
      post-up route del default dev $IFACE || true
  #VAGRANT-END
``` 

And the route
```
 $ ip route show
 default via 192.168.121.1 dev eth0 
 10.100.10.0/24 dev eth1  proto kernel  scope link  src 10.100.10.230 
 192.168.121.0/24 dev eth0  proto kernel  scope link  src 192.168.121.191 
```

**Comment by moozer** [comment]
My solution is to use 
:auto_config => false

something like this
>   serverA.vm.network :private_network, 
>     :libvirt__network_name => "LAN_A",
>      :libvirt__forward_mode => "none",
>      :auto_config=> false

and have the provisioning handle /etc/network/interfaces

**Comment by infernix** [comment]
That would be a valid way, and I'm not sure if there's anything better. It's also not related to #451 directly. Since we depend on DHCP working on eth0, I don't think there's an easy solution to this, but some other ideas are:

- Change the dhcp client config on the guest to not accept a default gateway from its eth0 lease
- Change the management network mode to something other than `nat` 

That last option turns out to be undocumented; I will add some documentation for it.
