### ISSUE TITLE
Feature request: Adding custom XML? Passthrough of RNG

### ISSUE THREAD

**Issue by bailsman** [vagrant-libvirt/vagrant-libvirt#576]
Hi, I need entropy in my VM and the easiest solution for me (since there's only 1 vm) is to pass my host's entropy through to the VM.

I would like to add the below to the devices section:

```
<devices>
   <rng model='virtio'>
     <backend model='random'>/dev/random</backend>
   </rng>
</devices>
```

Is there any way to do this from my Vagrantfile?

I guess I could make a pull request that makes a flag to add this specific device or not, but perhaps it's cleaner to be allowed to add arbitrary devices or even merge arbitrary XML.

What do you think?

**Comment by infernix** [comment]
I don't think it's a good idea to allow arbitrary XML in the Vagrantfile because it can never be checked for syntax errors or invalid or missing options. Instead, this should simply be implemented as a new flag.

If you want to send a PR for this, I suggest to implement a flag called `rng_model` with the only possible option being `random`(`egd` could be done at a later point) and then add `rng_backend` as an additional optional flag which can be set to `random` or `hwrng`as per the docs at https://libvirt.org/formatdomain.html#elementsRng. This would leave room for a future `egd` implementation without having to rewrite or change flags.

A simple `if @rng_model` can be used to add this device to the XML if it's defined in the Vagrantfile.

**Comment by danielkza** [comment]
@infernix: libvirt provides XML schemas that can be used to validate inputs. Check out the source of the [virt-xml-validate](https://github.com/libvirt/libvirt/blob/master/tools/virt-xml-validate.in) utility. Providing support for manual XML additions would make vagrant-libvirt much more flexible without requiring manual support for every single libvirt feature, which I guess will simply never happen.

**Comment by Archenoth** [comment]
It's a big dirty hack, but a workaround could be to write something to `/dev/urandom` on boot.
For example, I have a shell provision that runs this `:always`:

```sh
# Seed the PRNG in the background, or else Tomcat won't know how to
# session
cat /dev/vda1 > /dev/urandom &
```

Though note that the result here is possibly predictable since the entropy has a chance of being the same if the drive is read only. Also depending on the size of your virtual drive, you may want to use something else anyway.

**Comment by infernix** [comment]
@danielkza I still don't think it's a good idea; arbitrary XML, even when we validate it, may conflict with XML we generate, and to start writing checks for this arbitrary XML so that it doesn't conflict seems an awful lot of work for something like adding code to support rng.

And it is not all that much work to add this; as an example, look at the DTB support commit: https://github.com/vagrant-libvirt/vagrant-libvirt/commit/dc1a8d421fbb451dc168fef36fcd7dce92fe26a1 plus the readme update https://github.com/vagrant-libvirt/vagrant-libvirt/commit/9fe4d4c68d136bd4f02e25a01a2ea8ae81b80158

So if someone sends a PR I'll happily review/test/merge :+1:

**Comment by danielkza** [comment]
@infernix Adding the XML supports adds much more possibilities than just the RNG, it allows the full amount of customization that libvirt provides for everything, and makes it unecessary to add special support for every libvirt feature available now or the future. Browsing through the issues I see dozens that are nothing but requests to support for different libvirt features.

**Comment by infernix** [comment]
@danielkza again, happy to review/test/merge a PR :)

**Comment by danielkza** [comment]
@infernix I'll need to think a little about the best way to do it. I'm not too familiar with the vagrant-libvirt codebase, but I'll try to get something running in the next week.

**Comment by ruzickap** [comment]
Are there any news about it?

**Comment by pronix** [comment]
are there any pull requests ?

**Comment by rmohr** [comment]
Hi,

I created #654, a very basic implementation which allows passing in the `random` backend.

**Comment by electrofelix** [comment]
Looks like this is the same as #791, since this partially focused on rnd and that has been implemented to a degree, I think better to close this and can consider custom XML in 791.
