### ISSUE TITLE
Support 'vagrant share'

### ISSUE THREAD

**Issue by Dreamsorcerer** [vagrant-libvirt/vagrant-libvirt#611]
==> default: The provider this machine is backed by ('libvirt') doesn't
==> default: support telling Vagrant Share what address it is reachable at.
==> default: Vagrant Share will attempt to use 127.0.0.1 with forwarded ports
==> default: to find the address. Please contact the provider maintainer to fix
==> default: this error.

**Comment by infernix** [comment]
This does indeed seem unsupported. I'll flag as enhancement.

**Comment by electrofelix** [comment]
Looks like this may well have been fixed by #1036, currently trying to test vagrant-share locally just to be sure.

Note that vagrant-share requires that you use virtualbox for a proxy vm, so even if you are using vagrant-libvirt, still need virtualbox installed as well, unless support is added to vagrant-share itself to be able to use libvirt as a provider.

**Comment by Dreamsorcerer** [comment]
I'll just close it as fixed then. I'm not actually using vagrant anymore, so won't test it myself.

**Comment by electrofelix** [comment]
I've confirmed that it is possible to start vagrant-share once virtualbox is available, though it does require further config of ngrok to ensure you have the required auth token for the sharing to for it to start up fully, and there appears to be various issues in having virtualbox run along side kvm/libvirt, so it might not work in many situations because vagrant-share depends on having a proxy vm in virtualbox.
