### ISSUE TITLE
using private_network with nodhcp instead of vagrant-libvirt with DHCP interface network

### ISSUE THREAD

**Issue by stephencooke** [vagrant-libvirt/vagrant-libvirt#613]
### Steps to reproduce
1. setup private network options 
extract of my code below,

			srv.vm.network :private_network, 
  				:ip => 192.168.101.2,
  				:libvirt__host_ip => 192.168.101.1,
  				:libvirt__dhcp_enabled => false,
  				:libvirt__forward_mode => nat,
  				:libvirt__network_name => nodhcp,
  				:libvirt__netmask => 255.255.255.0
  
### Expected behaviour
Should start a network interface and use it, on eth0,  that is connected to nodhcp network this doesnt happen and the interace is defined as eth1

Tell us what should happen
Ideally this setup should replace the existing DHCP/NAT default interface on eth0

### Actual behaviour
Tell us what happens instead
The defined interface doesnt replace the DHCP/NAT interface eth0,  it is defined as eth1
### System configuration
**OS/Distro version:**:
CentOS Linux release 7.2.1511 (Core) 
**Libvirt version:**

**Output of `vagrant version; vagrant plugin list`:**
vagrant version; 
Installed Version: 1.8.4
Latest Version: 1.8.4

vagrant plugin list
vagrant-libvirt (0.0.33)
vagrant-share (1.1.5, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
extract from Vagrantfile, I use arrays to hold the servers data
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

...	
...	

servers.each do |servers|
		config.vm.box = servers["box"]
		config.vm.define servers["name"] do |srv|
			srv.vm.hostname = servers["hostname"]
			#this doesnt replace the default network, you still get a DHCP connection.
			srv.vm.network :private_network, 
  				:ip => servers["ip"],
  				:libvirt__host_ip => servers["libvirt__host_ip"],
  				:libvirt__dhcp_enabled => servers["libvirt__dhcp_enabled"],
  				:libvirt__forward_mode => servers["libvirt__forward_mode"],
  				:libvirt__network_name => servers["libvirt__network_name"],
  				:libvirt__netmask => servers["libvirt__netmask"]
  				#:libvirt__dhcp_start =>  servers["libvirt__dhcp_start"]
  				#:libvirt__dhcp_stop => servers["libvirt__dhcp_stop"]
  						
			srv.vm.network :public_network, 
				:auto_config => 'false', 
				:type => 'bridge', 
				:mode => 'bridge',
				:dev => servers["public_dev"], 
				:ip => servers["public_ip"], 
				:netmask => servers["public_mask"]
		
			srv.vm.network :public_network, 
				:auto_config => 'false', 
				:type => 'bridge', 
				:mode => 'bridge',
				:dev => servers["private_dev"], 
				:ip => servers["private_ip"], 
				:netmask => servers["private_mask"]
		
			srv.vm.provider :libvirt do |domain|
					domain.memory = servers["memory"]
					domain.cpus = servers["cpus"]
					#domain.machine_virtual_size = servers["disksize"]
			end
		end
	end

...
...
end 
```

Is it possible to setup so that the private network is used instead of the vagrant-libvirt, I have defined a network called nodhcp which has DHCP disabled.

The guest machine being given settings from DHCP is something I am trying to avoid as this gets in the way when you want to build a replacement DNS/DHCP server.

**Comment by infernix** [comment]
That's not how private_network works. It will always create an extra interface. Vagrant needs the first interface that comes up to sit on the management_network so that it can connect to it and manage the VM.

If you want to replace eth0 you need to look here https://github.com/vagrant-libvirt/vagrant-libvirt#management-network but you won't be able to do that without dhcp; the Vagrant images all boot and send out a DHCP request by which Vagrant learns its IP, and you cannot use Vagrant if you break that function.

For your DHCP server, I suggest you just configure it to listen on eth1 inside the VM. You are free to completely ignore eth0 after the VM is provisioned.

**Comment by stephencooke** [comment]
OK, thanks for the information.  Would it be possible move my question to a request to allow in a future version of the software 
static ip assignment of the first interface and not use DHCP? for the management-network.

**Comment by infernix** [comment]
No, because it is entirely against the design philosophy. The management network is there to allow Vagrant access to the VM and by not using DHCP we cannot know the IP address of the booted VM because we cannot alther the box VM network configuration until after it booted. 

You're free to shutdown eth0 once the VM is booted and provisioned though.

**Comment by pronix** [comment]
@stephencooke you can configure dnsmasq as notAuthoritative dhcp server

**Comment by stephencooke** [comment]
@pronix , that may be worth a shot.  I take it this would have to go into the hosts /etc/dnsmasq.* setup

I will look into it
