### ISSUE TITLE
Add ability to specify SCSI controller model

### ISSUE THREAD

**Issue by epienbroek** [vagrant-libvirt/vagrant-libvirt#633]
With vagrant-libvirt it is possible to specify additional disks (https://github.com/vagrant-libvirt/vagrant-libvirt#additional-disks). When adding an additional disk it is possible to specify which bus type should be used.

I've noticed some odd behaviour when adding an additional disk with bus type 'scsi'. Whenever a disk gets added with bus type 'scsi' an additional SCSI controller also gets added to the VM (if necessary). 

This automatically added SCSI controller is using the 'Hypervisor Default' model according to virt-manager. In testing I found out that RHEL7 guests are unable to detect this SCSI controller while RHEL6 guests work fine (host is Fedora 24).

In further research I discovered that upstream qemu (which Fedora also carries) uses LSI as the default SCSI controller model. It turns out that RHEL7 doesn't have support for this specific LSI SCSI controller any more (kernel module sym53c8xx) while it was still supported in RHEL6. 

When I manually change the SCSI controller model from 'Hypervisor Default' to 'virtio-scsi' in virt-manager the SCSI controller gets detected properly in both RHEL6 and RHEL7.

Would it be possible to extend vagrant-libvirt so that a SCSI controller model can be set instead of the relying on the default model?

**Comment by infernix** [comment]
From the libvirt docs:

> A scsi controller has an optional attribute model, which is one of 'auto', 'buslogic', 'ibmvscsi', 'lsilogic', 'lsisas1068', 'lsisas1078', 'virtio-scsi' or 'vmpvscsi'.

So while this is definitely possible, we do not explicitly define controllers in the domain XML when we submit this to libvirt. Therefore in order to support that, we would have to either

a) implement full controller support
or
b) submit the initial XML and then alter it

b) generally just sounds like a bad idea, and a) is quite a bit of work because once we start adding controllers we have to add *all* type of controllers so as to not cause a conflict on the bus.

So I'm open to it and I see its usefulness but it doesn't look like a quick fix is possible.

**Comment by electrofelix** [comment]
#692 is a start at looking at this, could do with some help in looking at it. We had success with just adding the controller for scsi without needing to add other controllers, but for a proper configuration would probably need to support identifying scsi devices to use the correct controller and confirm that libvirt is able to auto add any other controllers needed.
