### ISSUE TITLE
vagrant-libvirt seems to not inform user about new box version

### ISSUE THREAD

**Issue by daks** [vagrant-libvirt/vagrant-libvirt#713]
### Steps to reproduce
1. create a custom vagrant libvirt box
2. create a JSON description file which reference this box at version 1.0
3. host both on a HTTP server
4. create a Vagrantfile which points to this JSON file
5. vagrant up && vagrant destroy
6. create a new version 2.0 of your box
7. vagrant up again

### Expected behaviour
I expect Vagrant to inform me that there is a new version of my box available on the server. It seems to work well when I create a Virtualbox box but not when it's libvirt.

### Actual behaviour
No message about new box version.

### System configuration
**OS/Distro version:**: Debian Jessie/Stretch amd64

**Libvirt version:** 2.4

**Output of `vagrant version; vagrant plugin list`:**
sahara (0.0.17)
vagrant-libvirt (0.0.36)
vagrant-mutate (1.2.0)
vagrant-scp (0.5.7)
vagrant-share (1.1.6, system)
vagrant-snapshot (0.0.1)
vagrant-vbguest (0.13.0)

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
Box versioning isn't supported yet.

**Comment by daks** [comment]
ok, thanks for the reply

**Comment by lelutin** [comment]
Hi there!

I can see that some manner of versioning support was added by #294 -- e.g. we now have the version tag in the libvirt storage image name.

however, this issue is still present : vagrant-libvirt does not recognize new versions of boxes and does not act accordingly.

I've encountered the same problem as initially described by @daks -- when upgrading a box with vagrant box update I get the new version of the box in `~/.vagrant.d/boxes`, but then running `vagrant up` on a vagrant project that uses this box does nothing about the new version. it just spawns the VM with the old version of the storage image that's already present in libvirt.

it would be nice to:

 * warn users about the new box version
   * this could be done now before the rest is implemented, vagrant-libvirt would mention that the libvirt storage contains an image that is older than the more recent box version that we have locally and tell users that they should destroy the image known by libvirt if they want the new one to be uploaded.
 * upload the new image to libvirt
 * delete the old version of the image if there are no vagrant projects currently using it
 * start VM with new image file

**Comment by daks** [comment]
@lelutin do you have current versions of vagrant and vagrant-libvirt plugin? Because it seems that this bug is now fixed, since #849. I just tried and I got the message about a new available box.

```
$ vagrant box list|grep debian-stretch
foo/debian-stretch          (libvirt, 2018-05-25)

$ vagrant destroy

$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'foo/debian-stretch' is up to date...
==> default: A newer version of the box 'foo/debian-stretch' for provider 'libvirt' is
==> default: available! You currently have version '2018-05-25'. The latest is version
==> default: '2018-08-13'. Run `vagrant box update` to update.
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

$ vagrant box list|grep debian-stretch
foo/debian-stretch          (libvirt, 2018-05-25)
foo/debian-stretch          (libvirt, 2018-08-13)
```

I'm not completely sure but it seems that Vagrant also update base box uploaded on libvirt storage after a destroy & up.

**Comment by electrofelix** [comment]
@lelutin what version of vagrant-libvirt are you running? `0.0.43` should contain the changes needed to retrieve a box update if available as mentioned by @daks above.

**Comment by lelutin** [comment]
@daks @electrofelix I have vagrant 2.0.2 and vagrant-libvirt 0.0.43 (from debian unstable packages)

vagrant does indeed update the box in local storage (in `~/.vagrant.d/boxes`) when there's a new one. however the image stored by libvirt stays the same if I look with `virsh vol-list default`

I haven't tried yet to destroy and up again. I'll try to test it out soon

**Comment by lelutin** [comment]
hmm it seems to have updated the storage too .. I'm sorry for the noise then -_-;
