### ISSUE TITLE
Usage with Windows dev VMs

### ISSUE THREAD

**Issue by joerg** [vagrant-libvirt/vagrant-libvirt#808]
Microsoft has some official VM images for IE development purposes. I have not been able to run one of these with Vagrant and was wondering if anyone already was able to do so? I simply downloaded the vagrant image, imported the box and used vagrant-mutate to convert it to libvirt. Now I can start the image but I ran into hundreds of errors trying to get it up. With a simple, pretty much empty, Vagrantfile the windows network does not work for me:
```
Vagrant.configure("2") do |config|
  # config.vm.communicator = "winrm"
  # config.winrm.username = "IEUser"
  # config.winrm.password = "Passw0rd!"
  config.vm.box = "MSEdge - Win10"
end
```

So, did anyone get this running with libvirt? It seems to work with VirtualBox quite well: https://gist.github.com/andreptb/57e388df5e881937e62a

**Comment by infernix** [comment]
Virtualbox emulation is different from KVM emulation. It's likely that you need to match the Virtualbox hardware to be the exact same with KVM in order to even boot it; generally we do not recommend mutating boxes but to use direct libvirt ready boxes off of Atlas but I'm sure MS doesn't build libvirt boxes.

I suggest playing with it within virt-manager (setting the right disk controller/nic/display/whatever), and once that works, to then apply those settings in a Vagrantfile for vagrant-libvirt. Without that, you'd have to build the image from scratch to work properly with KVM. Unfortunately that's all out of scope for vagrant-libvirt, so i'm closing this but feel free to reopen if it's actually booting correctly and Vagrant still is giving issues.
