### ISSUE TITLE
QA Jobs not running

### ISSUE THREAD

**Issue by zdw** [vagrant-libvirt/vagrant-libvirt#829]
### Steps to reproduce
1. Look at vagrant-libvirt github page: https://github.com/vagrant-libvirt/vagrant-libvirt#qa-status
2. Look at the Jenkins job list of QA jobs: https://jenkins.infernix.net/job/vagrant-libvirt-qa/

### Expected behaviour
QA Jobs would have run sometime within the last 10 months.

### Actual behaviour
They haven't been run

Maybe remove this section of the page, or switch to another QA provider?

**Comment by infernix** [comment]
They're running on my server at home, and I haven't been able to keep up. We can't run them anywhere generic since it requires a full nested KVM stack which AFAIK no QA service provides.

The other issue is that for each release I have to update README which is cumbersome (git commit to repo).

But I agree, it's useless if not ran; if I can't get around to fixing it I will remove it sometime soon[tm].

**Comment by electrofelix** [comment]
Have started migrating the QA jobs to run using github actions using `qemu` for full emulation instead of needing `kvm`. It won't test nested virtualization, but it should be possible to test individual OS's this way provided they don't take too long.

**Comment by electrofelix** [comment]
These are now run over at https://github.com/vagrant-libvirt/vagrant-libvirt-qa using docker machines to ensure build against the correct OS libraries.
