### ISSUE TITLE
Ignoring interface name option

### ISSUE THREAD

**Issue by xaoc2** [vagrant-libvirt/vagrant-libvirt#874]
### Steps to reproduce
1. node.vm.network :private_network,
      :dev => "eth1",
      :libvirt__network_name => "vagrant_net",
      :libvirt__network_address => '192.168.100.0',
      :ip => "192.168.100.10#{node_number}"
2. Use ansible provisioner
3. vagrant up
4. repeat many times, until provisioning some node fails
5. check /etc/network/interfaces

### Expected behaviour
```
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
pre-up sleep 2
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 192.168.100.104
      netmask 255.255.255.0
#VAGRANT-END
```

### Actual behaviour

eth0 is used twice, instead of eth0 and eth1 and that's why it belongs only to management network and has it's dhcp address.

```
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
pre-up sleep 2
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth0
iface eth0 inet static
      address 192.168.100.104
      netmask 255.255.255.0
#VAGRANT-END
```
### System configuration
**OS/Distro version:**:
Ubuntu 17.10
**Libvirt version:**
libvirt-bin   3.6.0-1ubuntu6.3
**Output of `vagrant version; vagrant plugin list`:**
```
vagrant-libvirt (0.0.43)
vagrant-mutate (1.2.0)
```
**A Vagrantfile to reproduce the issue:**

Insert Vagrantfile inside quotes here (remove sensitive data if needed
```
INTNET_NAME = [*('A'..'Z')].sample(8).join
VAGRANTFILE_API_VERSION = 2
NODE_COUNT = 5
HOME_DIR = "/home/user"
array = []

bootstrap = <<SCRIPT
echo begin shell provisioning...
SCRIPT

NODE_COUNT.times do |i|
  array << "node#{i +=1}"
end


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.host_name = "ubuntu"
  config.ssh.insert_key = false
  config.vm.provider "libvirt" do |libvirt|
    libvirt.memory = 2048
    libvirt.cpus = 4
    libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
    libvirt.mgmt_attach = "false"
  end

  NODE_COUNT.times do |i|
    node_number = 1 + i
    node_id = "node#{node_number}"
    puts "node#{node_number}"
    config.vm.define node_id do |node|
      node.vm.box = "peru/ubuntu-16.04-server-amd64"
      node.vm.hostname = "#{node_id}.intranet.local"
      node.vm.network :private_network,
        :dev => "eth1",
        :libvirt__network_name => "vagrant_net",
        :libvirt__network_address => '192.168.100.0',
        :ip => "192.168.100.10#{node_number}"
    end
  end

  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.inventory_path = "./hosts.ini"
    ansible.playbook = "../../playbook.yml"
    ansible.sudo = true
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream
2.0.3

**Comment by electrofelix** [comment]
Sorry it's taken a while. `:dev` only has an impact on public interfaces for vagrant-libvirt and there it is only configuring which interface on the host should be used as a physical interface for the public network https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#public-network-options

Looking at the code https://github.com/vagrant-libvirt/vagrant-libvirt/blob/585cf6dd6769b8abd33e75fb72a17812e8dfd778/lib/vagrant-libvirt/action/create_network_interfaces.rb#L197-L234, I can't see how it would ever suggest to vagrant to use eth0 since very explicitly the first slot should always be skipped based on https://github.com/vagrant-libvirt/vagrant-libvirt/blob/585cf6dd6769b8abd33e75fb72a17812e8dfd778/lib/vagrant-libvirt/action/create_network_interfaces.rb#L201, which means the second slot will always have an interface of 1. That means given the management network is always slot 0 for vagrant-libvirt, if there is any attempt to configure a second network it will always start with interface 1.

Looking at vagrant and how it retrieves the list of interfaces from the guest, I do see one commit https://github.com/hashicorp/vagrant/commit/a73fb9c1391971c4999de46950dc690f93f1aa0f where the comment suggests that sometimes lo was included in the list of interfaces returned which would change the order matching.

e.g. if the expected was `['eth0', 'eth1']` and what was returned was `['lo', 'eth0', 'eth1']`, then the interface 1 would match `eth0` as interface 0 would have been `lo`.

Can see a hint of this with https://github.com/hashicorp/vagrant/commit/a73fb9c1391971c4999de46950dc690f93f1aa0f#diff-737f0b9528a112adb2db951f6b204b412ebf02bbdf59db41d0fd7b54148430a1R39

Given this commit was released in 2.1.5, I'm guessing that this was an intermittent issue in vagrant upstream rather than ourselves. Based on this, I'm going to close it.
