### ISSUE TITLE
During vagrant reload, VM stucks in halted state.

### ISSUE THREAD

**Issue by vinayakshnd** [vagrant-libvirt/vagrant-libvirt#877]
### Steps to reproduce
1.  Use `vagrant-reload` plugin in Vagrantfile to reboot machines after provisioning.
2.   vagrant up --provider=libvirt
3.  VMs get provisioned, shell provision gets executed and during reload VM stucks in halted state with 
```10:09:38 ==> NODE-torpedo-dev-2-a-colo-7: Running provisioner: reload...
10:09:38 ==> NODE-torpedo-dev-2-a-colo-7: Halting domain...
10:09:38 ==> NODE-torpedo-dev-2-a-colo-4: Starting domain.
10:09:38 ==> NODE-torpedo-dev-2-a-colo-4: Error when updating domain settings: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
``` 
error.

### Expected behaviour
Libvirt VMs should reboot cleanly

### Actual behaviour
VM stucks in halted state.

### System configuration
**OS/Distro version:**:
CentOS7
**Libvirt version:**
libvirt version: 3.2.0, package: 14.el7_4.9 (CentOS BuildSystem <http://bugs.centos.org>, 2018-03-07-13:51:24, x86-01.bsys.centos.org)

**Output of `vagrant version; vagrant plugin list`:**

```
Installed Version: 2.0.1
Latest Version: 2.0.3
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v2.0.3/CHANGELOG.md
vagrant-libvirt (0.0.43)
vagrant-mutate (1.2.0)
vagrant-reload (0.0.1)
vagrant-share (1.1.9, system)

```
**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
10:09:38 ==> NODE-dev-2-a-colo-7: Running provisioner: reload...
10:09:38 ==> NODE-dev-2-a-colo-7: Halting domain...
10:09:38 ==> NODE-dev-2-a-colo-4: Starting domain.
10:09:38 ==> NODE-dev-2-a-colo-4: Error when updating domain settings: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: CPU vendor specified without CPU model
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = OS_IMAGE
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # Override
    config.vm.provider :libvirt do |v,override|
        override.vm.synced_folder '.', '/home/vagrant/sync', disabled: true
    end

    (1..NODES.to_i).each do |i|
        config.vm.define "NODE-#{STACK_NAME}-#{i}" do |node|
            node.vm.hostname = "NODE-#{STACK_NAME}-#{i}"
            node.vm.network :public_network, 
		:dev => "br0",
		:mode => "bridge",
		:type => "bridge",
		:network_name => "ens7f0"

            
            (0..DISKS.to_i-1).each do |d|
                node.vm.provider :libvirt do  |lv|
                    lv.storage_pool_name = "pool1"
                    driverletters = ('b'..'z').to_a
                    lv.storage :file, :device => "vd#{driverletters[d]}", :path => "atomic-disk-#{STACK_NAME}-#{i}-#{d}.disk", :size => '128G'
                    lv.memory = INSTANCE_MEM
                    lv.cpus = INSTANCE_CPUS
                    lv.volume_cache = LIBVIRT_DISK_CACHE
                    lv.default_prefix = "vagrant"
                end

           end
             node.vm.provision "shell", path: "post_provisioning.sh", :args => "#{IMAGE} #{INSTALL_DOCKER}" 
             node.vm.provision :reload   
        end
    end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro

**Comment by jasonwalsh** [comment]
Hey @vinayakshnd, I am also experiencing this issue with a custom box created via Packer using Ubuntu 16.04.4 LTS (Xenial Xerus) as the guest OS.

Out of curiosity, which Vagrant box are you using? Also, am I correct assuming that you are running libvirt locally?

**Comment by vinayakshnd** [comment]
Yes @jasonwalsh Yes I am running libvirt locally.

**Comment by krzys-h** [comment]
I just ran into the same issue, it seems you can work around the issue like this:
```ruby
  config.vm.provider "libvirt" do |domain|
    # workaround a bug in libvirt-reload?
    # https://github.com/vagrant-libvirt/vagrant-libvirt/issues/877
    domain.cpu_mode = 'host-model'
    domain.cpu_model = 'qemu64'
  end
```

**Comment by electrofelix** [comment]
I suspect there is a bug in how the following code is modifying the model unnecessarily
https://github.com/vagrant-libvirt/vagrant-libvirt/blob/cf51e451a0fc80605aae952137af457a27bfe885/lib/vagrant-libvirt/action/start_domain.rb#L102-L120

possibly even it's just https://github.com/vagrant-libvirt/vagrant-libvirt/blob/cf51e451a0fc80605aae952137af457a27bfe885/lib/vagrant-libvirt/action/start_domain.rb#L110-L114 where it should only look to modify the model if the config has an value.

**Comment by electrofelix** [comment]
@krzys-h would you be able to provide the XML of the VM before you do the reload? Because I'm not reproducing the error locally I'm guessing something is being added by libvirt to the XML that is not accounted for so I'm not confident that where I'm modifying is definitely the source of the issue.

If you can remove your workaround, then confirm that you still hit the issue. Then if you can just do the `vagrant up` step and then `vagrant halt`. After this call `virsh list --all` or `virsh -c qemu:///system list --all` to see which you need to perform a dumpxml and then it's `virsh <-c option if needed> dumpxml vagrant-libvirt_default`. The trailing part of the VM `default` will depend on whether you've named the VM or not. If you have used something like `config.vm.define "NODE-#{STACK_NAME}-#{i}"` then it should be `vagrant-default_NODE-#{STACK_NAME}-#{i}` withe variables replaced.

That should allow me to add the resulting xml to a test fixture in the unit tests and work and then correct how the config is getting applied.

**Comment by electrofelix** [comment]
@krzys-h if you have a chance could you try to reproduce the original issue using the following Vagrantfile as it will grab the domain XML generated that will be processed on the reload and then you can dump the final XML subsequently.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.box_check_update = true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.cpus = 2
    libvirt.memory = 2048
  end

  config.trigger.before :reload do |t|
    t.info = "Bringing up your Vagrant guest machine!"
    t.ruby do |env, machine|
      `virsh -c #{machine.provider_config.uri} dumpxml vagrant-libvirt_#{machine.name.to_s} > pre_reload.xml`
    end
  end
  config.vm.provision :reload
end
```

I've added a PR #1345 so that in the future a debug log will emit the XML seen at these points in time to help deal where the local hardware won't trigger the same behaviour due to libvirt emitting different values either due to the version or the host hardware.

**Comment by electrofelix** [comment]
I believe it's possible this bug is fixed, so barring information confirming that the issue still exists, it will automatically close in 30 days. If someone can reproduce this, the latest releases >= 0.6.0 contain improved debugging that will show what XML was used to attempt to start the domain with, so it should be relatively trivial to fix in such cases.

**Comment by PeterNerlich** [comment]
This is probably a different bug entirely, but I also had that `CPU vendor specified without CPU model` message when running `vagrant up --provision` on a halted or running VM (to clearify: I didn't use vagrant reload).
I tried specifying `cpu_mode` and `cpu_model` as suggested above and could not see a change after multiple tries, but when removing it again suddenly the message disappeared. It seems to be sporadically occurring, but I always noticed it after suspending the VM (though maybe only because vagrant then also fails to connect to it again – as I said, probably different issue).
This was on `vagrant-libvirt-0.6.2`, I just updated to 0.7.0 and didn't see the message. But I didn't see it immediately before either, so that's probably not a valid data point.

**Comment by electrofelix** [comment]
@PeterNerlich some timing, just before the bot closed the issue automatically ;-)

If you can try capturing the domain XML before bringing the VM up using:
```
# check system
virsh -c qemu:///system list --all
# check session
virsh -c qemu:///session list --all
```

identify the domain and then run the following with the corresponding connection and domain name:
```
virsh -c <connection> dumpxml <domain>
```
That will provide us with the XML that is seen by vagrant-libvirt before it attempts to update any settings that changed.

Next step is to capture what it attempts to send to libvirt to start the domain. The 0.6.0 releases and above contain some additional debug logging so if you can reproduce it when capturing the debug log with `VAGRANT_LOG=debug vagrant up --provision 2>&1 | tee vagrant.log` it will capture this  as well.

Then when logging the issue (if it's not gone) can attach the original XML as well as the log file and that should be enough to establish what happened.

**Comment by PeterNerlich** [comment]
Alright, I will try to remember doing this as soon as I see the message again.
