### ISSUE TITLE
Ansible "synchronize" module fails when private & public networks are defined

### ISSUE THREAD

**Issue by ticktockhouse** [vagrant-libvirt/vagrant-libvirt#922]
### Steps to reproduce
1. Vagrantfile with Ansible provisioner
2. Vagrant box is on a remote libvirt instance and has a "private" and "public" network interface defined
3. Add playbook/role which uses ansible "synchronize" module with "remote_src" option

### Expected behaviour
Ansible should sync to remote "public" IP (or should have that option somehow)

### Actual behaviour
Ansible syncs to private IP

### System configuration
**OS/Distro version:**:
Local - Ubuntu 18.04 Remote Ubuntu 18.04

**Libvirt version:**
4.0.0-1

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 2.0.2
```
Vagrant was unable to check for the latest version of Vagrant.
Please check manually at https://www.vagrantup.com
vagrant-libvirt (0.0.43, system)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**

https://gist.github.com/ticktockhouse/1ed3a4e9f21eb85997d246cba5172416

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

vmhost = "my.vm.host"
vmname = "myvm"
storage_pool = "ssd-2"

Vagrant.configure("2") do |config|
  config.vm.define "#{vmname}" do |vmconfig|
    vmconfig.vm.box =  "generic/ubuntu1604"
    vmconfig.vm.network "public_network",
       :dev => 'br0',
       use_dhcp_assigned_default_route: true
    vmconfig.vm.synced_folder './', '/vagrant', type: 'rsync'
    vmconfig.vm.provider :libvirt do |domain|
      domain.memory = 16384
      domain.cpus = 2
    end
  end

  # Options for libvirt vagrant provider.
  config.vm.provider :libvirt do |libvirt, override|
    libvirt.driver = "kvm"
    libvirt.host = "#{vmhost}"
    libvirt.connect_via_ssh = "true"
    libvirt.username = "root"
    #libvirt.password = "secret"
    libvirt.storage_pool_name = "ssd-2"
    override.ssh.proxy_command = "ssh -l root #{vmhost} nc -N %h %p"
  end

  config.vm.provision "shell", inline: "apt-get -y install python"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "debug.yml"
    ansible.config_file = "ansible.cfg"
    ansible.verbose = "vv"
  end    
end
```

**Are you using upstream vagrant package or your distros package?**

Distro

**Comment by electrofelix** [comment]
This appears to have been an issue with ansible itself failing to include the ssh proxy command that is added by vagrant to the ansible command, within the synchronize rsync execution.

https://github.com/ansible/ansible/pull/15306 is the upstream bug, where it indicates that ansible is not fully cascading all of the ssh parameters from the play context.

https://gist.github.com/ticktockhouse/1ed3a4e9f21eb85997d246cba5172416#file-gistfile1-txt-L485 shows the version of ansible used during this was 2.6. 

https://gist.github.com/ticktockhouse/1ed3a4e9f21eb85997d246cba5172416#file-gistfile1-txt-L368-L438 shows a successful connection within normal vagrant with the proxy command being used `:proxy=>#<Net::SSH::Proxy::Command:0x00005653efff72f8 @command_line_template="ssh -l root vmhost2.office1.sq nc -N %h %p"` 

While the rsync command at https://gist.github.com/ticktockhouse/1ed3a4e9f21eb85997d246cba5172416#file-gistfile1-txt-L2735 does not contain the necessary ssh calls to pass through the referenced proxy.

It appears to have been fixed with 2.14 based on what I'm seeing in https://github.com/ansible/ansible/commit/a521b70217a9d949402c8ce563c01f6460435301

Based on this, I'm going to close it. Sorry it took so long to be able to follow up on it.
