### ISSUE TITLE
Unprivileged VMs

### ISSUE THREAD

**Issue by fakhraee** [vagrant-libvirt/vagrant-libvirt#926]
The plugin currently asks for sudo password when creating new machines, eventhough the user that runs "vagrant", is a member of "libvirt" and "kvm" groups and It'd be great if the new vm is created in the unprivileged user space and not with the root privilege. 

Thanks

**Comment by electrofelix** [comment]
On Ubuntu 16.04 my user is a member of the `libvirtd` group and can create the VMs as a normal user with the system /etc/profile.d/libvirt-uri.sh containing `LIBVIRT_DEFAULT_URI="qemu:///system"` without needing sudo (also use 9p for folder sharing instead of nfs).

If you're finding that you cannot create VMs as a user without using sudo, then it's likely that virt-manager would result in the same behaviour.

Other than that we're limited to people volunteering time to add the necessary changes to change how to set up the disk images in a way that would work for users using `LIBVIRT_DEFAULT_URI="qemu:///session"`.

**Comment by fakhraee** [comment]
Thanks @electrofelix 
I'm closing this issue 'cos it's a duplicate of #272
