### ISSUE TITLE
Option to use plain qemu to manage VM's

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#957]
libvirt is cool and all, but unfortunately requires a lot of tender love and care to setup, especially with Ruby and especially on non-Linux host machines. For my purposes, it would actually be more useful to have a Vagrant plugin that uses qemu directly, rather than targeting libvirt.

What do you think of having the option for vagrant-libvirt to run qemu commands directly? Or, how hard would it be to create a "vagrant-qemu" plugin?

**Comment by electrofelix** [comment]
In general the main problem is around permissions, one of the main benefits of libvirt is that most linux distributions are set up to allow libvirt to perform certain actions as uid 0.

I'm sure it's possible to do the same with direct access to /dev/kvm as packer makes use of this directly, but at the same time it doesn't have any need to setup complex networks.

There was a vangrant-kvm plugin previously that was abandoned in favour of this one I believe due to problems impending support for additional functionality.

Might be worth revitalising that plugin if the limited functionality works for you, or maybe look at using a docker image containing vagrant + vagrant-libvirt. Maybe we could add an example one under this org, or add the other plugin if you think it's worth taking that on

**Comment by mykaul** [comment]
libvirt also abstracts different versions of QEMU/KVM command line API, and feature set.

**Comment by mcandre** [comment]
Don't get me wrong, I think libvirt is great! It's just that libvirt contributors currently support only Linux hosts, whereas qemu supports many different host platforms.

This matters to me, because I am designing my Vagrant boxes to help developers easily cross-compile their apps for lots of different platforms. I know that I could enable ARM, MIPS, RISC, and so on for my fellow developers with libvirt, but that would be at the expense of requiring developers to always build from Linux hosts. And not even Linux-within-mac/Windows, but in fact booting fully from Linux! This wrecks the goal of being able to build *from* and *to* different platforms.

Maybe libvirt will get better mac and Windows support in the future, but for now, qemu, or paying $$$ for dedicated Linux build hosts, are the only options. That's why it is so important to me that Vagrant gets a plain vanilla qemu plugin, in addition to the libvirt plugin.

**Comment by mykaul** [comment]
@mcandre - if you want them to run on different platform, you need to look at the Vagrant level - run on the VMs on either VirtualBox (on Windows, Mac) or libvirt (on Linux) ?

**Comment by mcandre** [comment]
@mykaul That's my entire point: libvirt requires a Linux host, to the exclusion of a lot of developer machines out there. While we wait for libvirt to improve support for non-Linux hosts, we could go ahead and wrap qemu in a Vagrant plugin, so that Windows and macOS hosts can enjoy non-x86 guest VM's managed with Vagrant.

**Comment by mcandre** [comment]
Eh, I gave up on waiting for this feature and just got a dedicated Linux host. I'll be telling my Vagrant users that for qemu VM's, they'll need to follow suit.

**Comment by electrofelix** [comment]
@mcandre I'm not sure how you vagrant-libvirt could have implemented this in a practical manner. As suggested before the better approach would be to resurrect vagrant-kvm, or look to create a vagrant-qemu plugin, there are too many differences in providing suitable options and corresponding behaviour to embed here
