### ISSUE TITLE
Compilation error installing plugin in opensuse

### ISSUE THREAD

**Issue by pablochacin** [vagrant-libvirt/vagrant-libvirt#962]
### Steps to reproduce
1. install upstream vagrant 2.2.2

2.install missing dependencies 
sudo zypper install  libxslt-devel libxml2-devel libvirt-devel   libguestfs-devel ruby-devel gcc

3. install plugin 
CONFIGURE_ARGS='with-libvirt-lib=/usr/lib with-libvirt-include=/usr/include/libvirt'  vagrant plugin install vagrant-libvirt

### Expected behaviour
Pluin should be installed

### Actual behaviour
Compilation error
```
compiling domain.c
In file included from domain.c:26:0:
/tmp/.mount_vagranN6moNK/usr/include/ruby-2.4.0/ruby/backward/st.h:2:2: warning: #warning use "ruby/st.h" instead of bare "st.h" [-Wcpp]
 #warning use "ruby/st.h" instead of bare "st.h"
  ^~~~~~~
In file included from /tmp/.mount_vagranN6moNK/usr/include/ruby-2.4.0/ruby.h:33:0,
                 from domain.c:24:
domain.c: In function ‘ruby_libvirt_domain_init’:
domain.c:5760:29: error: ‘VIR_DOMAIN_QEMU_AGENT_COMMAND_BLOCK’ undeclared (first use in this function); did you mean ‘HAVE_CONST_VIR_DOMAIN_QEMU_AGENT_COMMAND_BLOCK’?
                     INT2NUM(VIR_DOMAIN_QEMU_AGENT_COMMAND_BLOCK));
```

There are several of those. 

### System configuration
**OS/Distro version:**: Opensuse 15 leap

**Libvirt version:** 4.0.0

**Output of `vagrant version; vagrant plugin list`:** 2.2.2

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`** N/A

**A Vagrantfile to reproduce the issue:** N/A

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by electrofelix** [comment]
@pablochacin this suggests there is some issue in locating the libvirt header files, so most likely we're missing some package from the installation instructions or the installation path no longer matches the one passed via `CONFIGURE_ARGS`. Can you check if you have the file `/usr/include/libvirt/libvirt-qemu.h` or look to see if it is placed under a different path to `/usr/include/libvirt`?

Can you confirm that you tried installing with just `vagrant plugin install vagrant-libvirt` without the CONFIGURE_ARGS? I'm assuming that didn't work which is why you tried using it.

I do notice that `with-libvirt-lib=/usr/lib` doesn't indicate that it's `lib64`, so I'm wondering if you've got the 32bit version of vagrant installed? as SUSE OpenLeap has a separate package for 32bit libvirt called libvirt-devel-32bit (https://software.opensuse.org/package/libvirt-devel-32bit)

Looking at the contents of that package:
```
rpm -qlp ~/Downloads/libvirt-devel-32bit-6.0.0-lp152.9.3.1.x86_64.rpm 
warning: /home/baileybd/Downloads/libvirt-devel-32bit-6.0.0-lp152.9.3.1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
/usr/lib/libvirt-admin.so
/usr/lib/libvirt-lxc.so
/usr/lib/libvirt-qemu.so
/usr/lib/libvirt.so
```

which would suggest they would be required.

If I look at https://software.opensuse.org/package/libvirt-libs I see it contains the following libraries:
```
/usr/lib64/libvirt-admin.so.0
/usr/lib64/libvirt-admin.so.0.6000.0
/usr/lib64/libvirt-lxc.so.0
/usr/lib64/libvirt-lxc.so.0.6000.0
/usr/lib64/libvirt-qemu.so.0
/usr/lib64/libvirt-qemu.so.0.6000.0
/usr/lib64/libvirt.so.0
/usr/lib64/libvirt.so.0.6000.0
```
So might be worth checking the paths are correct for the architecture of libvirt and vagrant you are looking to compile against.

**Comment by electrofelix** [comment]
https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#opensuse should cover this and additionally https://github.com/vagrant-libvirt/vagrant-libvirt-qa validates an installation script against openSUSE 15 as well https://github.com/vagrant-libvirt/vagrant-libvirt-qa/blob/main/scripts/install.bash which takes care of any patching of libraries in vagrant automatically. See https://github.com/vagrant-libvirt/vagrant-libvirt-qa/actions/runs/3392960026/jobs/5639755945 for a successful run with openSUSE.
