### ISSUE TITLE
VNC port shown as "-1"

### ISSUE THREAD

**Issue by mcandre** [vagrant-libvirt/vagrant-libvirt#992]
When the VNC port is not customized, then it behaves as 5900 by default, according to documentation.

https://www.rubydoc.info/gems/vagrant-libvirt/0.0.24

And in practice, VNC clients such as Remmina are able to connect to localhost:5900 for a vagrant-libvirt guest. However, the Vagrant console log ends up showing the VNC port as `-1`, which is harder for users to make sense of. Could we have this printed out as the default port number, to match the behavior?

**Comment by electrofelix** [comment]
The port number is only resolved by libvirt when the domain is started, so it's not possible to output as part of the standard info printed about the configuration, it could only be outputted after the domain is started, not sure if there is a standard API to retrieve that.

The reason you can't assume it's 5900 is because if there are other VMs running then libvirt will assign the next available port, when doing a multi machine bring up, what this will be is non-deterministic, have to wait to see what gets assigned to each VM.
